# Initializing kcat values for PAMparametrizer

In this notebook, we give an overview of how an initial set of turnover number can be obtained. To enable this, we use multiple databases to map kcat values obtained from machine learning (from the [GotEnzymes](https://metabolicatlas.org/gotenzymes) database) to the proteins and reactions in the model using the gene-protein-reaction associations.

Before we start, we have to set up all the package and files required. Adjust the filenames and paths as desired.

In [1]:
import pandas as pd
import os
from cobra.io import read_sbml_model
import matplotlib.pyplot as plt
import re
import numpy as np
import datetime

from PAModelpy.utils.pam_generation import merge_enzyme_complexes, get_protein_gene_mapping, _parse_gpr

if os.path.split(os.getcwd())[1]=='i1_preprocessing':
    os.chdir('../..')

DEFAULT_PROT_MW = 39959.4825 #g/mol
DEFAULT_KCAT =  11.0 #/s median value from BRENDA
DEFAULT_PROT_LENGTH = 325 # amino acids, data from E.coli (Zhang J. Protein-length distributions for the three domains of life. Trends Genet. 2000 Mar16(3):107-9.PubMed ID10689349)


PAM_DATA_FILE_PATH = os.path.join('Data', 'proteinAllocationModel_iJN1463_EnzymaticData_240807.xlsx')
UNIPROT_FILE_PATH = os.path.join('Data', 'Databases','uniprotkb_pputidakt2240_240807.xlsx')

GOTENZYMES_FILE_PATH = os.path.join('Data','Databases', 'GotEnzymes_ppu_240807.json')

Loading PAModelpy modules version 0.0.4.6

In [2]:
#output file path
# Create a datetime object for the current date
current_date = datetime.datetime.now()
# Format the date as yymmdd
formatted_date = current_date.strftime('%y%m%d')

OUTPUT_FILE_PATH = os.path.join('Results', '1_preprocessing', f'proteinAllocationModel_iJN1463_EnzymaticData_{formatted_date}.xlsx')
AE_OUTPUT_FILE_PATH = os.path.join('Results', '1_preprocessing', f'{formatted_date}_ppu_ActiveEnzymeInformation_GotEnzymes.xlsx')

## 0. Download information from different databases
1. **Metabolic model stoichiometries and reactions: [BiGG database](http://bigg.ucsd.edu/)**
- Get your model! Or use your own reaction identifiers
- In this example we will use the iJN1463 model for [*Pseudomonas putida* KT2240](http://bigg.ucsd.edu/models/iJN1463)
- Important: the identifiers must me mappable to uniprot (or another enzyme identifier database) and KEGG (for mapping to GotEnzymes)

2. **Turnover numbers: [GotEnzymes](https://metabolicatlas.org/gotenzymes)**
- Go to the [API of the Metabolic Atlas](https://metabolicatlas.org/api/v2/#/GotEnzymes/gotEnzymes)
- Use the `GET\gotenzymes\enzymes?` functionality, click `Try it out`
- Here we filled in `ppu` (*P. putida* strain KT2240) for `organism` and `10000` for `pagination[pageSize]`. The rest was left empty
- Click execute and a json file with all the information will be generated
- Once the webpage is finished processing your query, scroll down and copy/download the resulting json file
- Note: GotEnzymes gives the locus tag, ec number, reaction id and compound for each protein. The latter 2 are given as KEGG identifiers, which we subsequently have to map to BiGG identifiers in order to match with the model. Therefore, we need to use other databases

3. **Gene-Protein-Reaction relations: [UniprotKB](https://www.uniprot.org/)**
- Got to the [Uniprot knowledge base](https://www.uniprot.org/) and used advanced search to query for your organism. For *P. putida* we used [this](https://www.uniprot.org/uniprotkb?query=%22pseudomonas+putida%22+AND+%28organism_id%3A160488%29) (strain: *Pseudomonas putida (strain ATCC 47054 / DSM 6125 / CFBP 8728 / NCIMB 11950 / KT2440)*) webpage
- Click download, select `format`:`Excel` and select the following: 
    - `Uniprot Data -> Names & Taxonomy`: `Gene Names`
    - `Uniprot Data -> Sequences`: `length`, `mass`
    - `Uniprot Data -> Function`: `RheaID`
- Mark `Compressed` as `No`
- Download the resulting Excel file

## 1. Get information from the BiGG model

In the metabolic model itself is already quite some information stored. In order to obtain up-to-date information on the enzymes related to the reaction, we will need to obtain the kegg reaction ID, the reactants, the product and the gene-protein relation.

In [3]:
#load the model
model = read_sbml_model(os.path.join('Models', 'iJN1463.xml'))

#make a id mapping and create a mapping dataframe
id_mapper_df = pd.DataFrame(columns = ['rxn_id', 'kegg_id', 'rhea_id', 'mnx_id','Reactants','Products','EC', 'GPR'])
for rxn in model.reactions:
    #skip transport reactions and ATP maintenance requirement
    if 'ex' in rxn.id or 'EX' in rxn.id or rxn.id == 'ATPM':
        continue
    to_append= []   
    to_append.append(rxn.annotation['bigg.reaction'])
    #not all reactions are annotated with a KEGG ID in the model
    try: 
        to_append.append(rxn.annotation['kegg.reaction'])
    except:
        to_append.append(np.nan)
    try: 
        to_append.append(rxn.annotation['rhea'])
    except:
        to_append.append(np.nan)
    try: 
        to_append.append(rxn.annotation['metanetx.reaction'])
    except:
        to_append.append(np.nan)
    try:
        to_append.append([reac.annotation['kegg.compound'] for reac in rxn.reactants])
    except:
        to_append.append([])
    try: 
        to_append.append([prod.annotation['kegg.compound'] for prod in rxn.products])
    except:
        to_append.append([])
    if 'ec-code' in rxn.annotation.keys():
        to_append.append(rxn.annotation['ec-code'])
        to_append.append(rxn.gene_reaction_rule)
        id_mapper_df.loc[len(id_mapper_df)] = to_append
    else:
        to_append.append(np.nan)
        #ignore entries without enzyme and gpr relation
        if rxn.gene_reaction_rule =='':
            continue
        else:
            to_append.append(rxn.gene_reaction_rule)
        id_mapper_df.loc[len(id_mapper_df)] = to_append

print('Number of reactions in the mapping dataframe: ',len(id_mapper_df))
print('Number of reactions mapped to KEGG identifier: ', len(id_mapper_df.kegg_id.dropna()))
print('Number of reactions mapped to rhea identifier: ', len(id_mapper_df.rhea_id.dropna()))
print('Number of reactions mapped to MetaNetX identifier: ', len(id_mapper_df.mnx_id.dropna()))
id_mapper_df.head()

Set parameter Username
Academic license - for non-commercial use only - expires 2025-03-06
Number of reactions in the mapping dataframe:  2007
Number of reactions mapped to KEGG identifier:  698
Number of reactions mapped to rhea identifier:  777
Number of reactions mapped to MetaNetX identifier:  1375

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174
1,1P2CBXLCYCL,NaN,NaN,NaN,[C01110],[],NaN,PP_s0001
2,1P2CBXLR,NaN,NaN,NaN,[],"[C00006, [C00148, C16435]]",NaN,PP_3591
3,1PPDCRc,R02203,"[12525, 12526, 12527, 12524]",MNXR94711,"[C04092, C00080, C00005]","[C00408, C00006]","[1.5.1.1, 1.5.1.25, 1.5.1.21]",PP_3591
4,1PY4h3cAH,NaN,NaN,NaN,[],[],NaN,PP_1257

## 2. Get all the protein information

Besides information about the reactions, we need the relation to the proteins in order to establish a protein allocation model. We do this using the gene-protein-reaction association obtained from the BIGG model. The genes is the model can be mapped to the Uniprot accessions, which can be mapped to the KEGG reactions using the Rhea database.

### 2.1 Parse the BIGG gene-protein-reaction associations

In [4]:
#You need to adjust this to find the geneid/locustag for your microbe
locustag_regex =r'\b(PP_\d{4})\b'
def extract_locustag_numbers(text):
    return re.findall(locustag_regex, text)

id_mapper_df['b_number'] = id_mapper_df['GPR'].apply(extract_locustag_numbers)
id_mapper_df = id_mapper_df.explode('b_number', ignore_index=True)
id_mapper_df

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174,PP_1602
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174,PP_4174
2,1P2CBXLCYCL,NaN,NaN,NaN,[C01110],[],NaN,PP_s0001,NaN
3,1P2CBXLR,NaN,NaN,NaN,[],"[C00006, [C00148, C16435]]",NaN,PP_3591,PP_3591
4,1PPDCRc,R02203,"[12525, 12526, 12527, 12524]",MNXR94711,"[C04092, C00080, C00005]","[C00408, C00006]","[1.5.1.1, 1.5.1.25, 1.5.1.21]",PP_3591,PP_3591
...,...,...,...,...,...,...,...,...,...
3760,4HTHRS,R05086,"[30659, 30662, 30660, 30661]",MNXR95024,"[[C00001, C01328], C06055]","[C06056, C00009]","[4.2.3.1, 4.2.3]",PP_1471 or PP_0662,PP_0662
3761,4MBZALDH,R05282,NaN,MNXR95030,"[C06757, C00003]","[C06758, C00080, C00004]","[1.1.1.90, 1.1.1.21]",pWW0_128,NaN
3762,4MBZDH,NaN,NaN,MNXR95031,"[C06758, [C00001, C01328], C00003]","[C00080, C00004, C01454]","[1.2.1.3, 1.2.1.28, 1.2.1.7]",pWW0_131,NaN
3763,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN
3764,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN

### 2.2 Parse the Uniprot data for merging

In [5]:
# load the uniprot information
uniprot_df = pd.read_excel(UNIPROT_FILE_PATH)
#get the gene id from the gene names
uniprot_df['b_number'] = uniprot_df['Gene Names'].str.extract(locustag_regex)
uniprot_df = uniprot_df.drop('Gene Names', axis=1)
uniprot_df

/home/samiralvdb/Software/anaconda3/envs/PAModelpy/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Entry,Protein names,Length,Mass,Rhea ID,b_number
0,Q88CC1,2-oxoadipate dioxygenase/decarboxylase (EC 1.1...,464,51372,RHEA:71787,PP_5260
1,Q88E10,Methyl-accepting chemotaxis protein McpS,639,68764,NaN,PP_4658
2,Q88E47,"Homogentisate 1,2-dioxygenase (HGDO) (EC 1.13....",433,48011,RHEA:15449,PP_4621
3,Q88F88,Pyoverdine export ATP-binding/permease protein...,654,69687,NaN,PP_4210
4,Q88FF8,Quinone reductase (EC 1.6.5.2) (Chromate reduc...,186,20354,RHEA:46160 RHEA:46164 RHEA:44372 RHEA:44368,PP_4138
...,...,...,...,...,...,...
5524,Q88RW2,Transcriptional regulator,119,13492,NaN,PP_0017
5525,Q88RW3,TniQ family protein,638,71170,NaN,PP_0016
5526,Q88RW4,Transposon protein,319,36304,NaN,PP_0015
5527,Q88RW5,Transposase,652,74345,NaN,PP_0014
5528,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14,1529,NaN,NaN

### 2.3 Match Uniprot to BIGG data

In [6]:
id_mapper_with_protein = pd.merge(id_mapper_df, uniprot_df, on='b_number', how='left')

id_mapper_with_protein

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number,Entry,Protein names,Length,Mass,Rhea ID
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174,PP_4174,Q88FC4,3-hydroxydecanoyl-[acyl-carrier-protein] dehyd...,171.0,18791.0,RHEA:13097 RHEA:41860 RHEA:23568
2,1P2CBXLCYCL,NaN,NaN,NaN,[C01110],[],NaN,PP_s0001,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN
3,1P2CBXLCYCL,NaN,NaN,NaN,[C01110],[],NaN,PP_s0001,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN
4,1P2CBXLR,NaN,NaN,NaN,[],"[C00006, [C00148, C16435]]",NaN,PP_3591,PP_3591,Q88GX6,Delta 1-piperideine-2-carboxylate reductase (E...,332.0,35143.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,4MBZDH,NaN,NaN,MNXR95031,"[C06758, [C00001, C01328], C00003]","[C00080, C00004, C01454]","[1.2.1.3, 1.2.1.28, 1.2.1.7]",pWW0_131,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN
3866,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN
3867,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN
3868,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN
3869,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN

### 3. Match the BiGG model reactiona and enzymes to the kcats from GotEnzymes
Find first all enzymes for a reaction, then for each enzyme determine if the kcats from GotEnzymes are for a forward or reverse reaction

In [7]:
id_mapper_final = id_mapper_with_protein
id_mapper_final = id_mapper_final.rename({'Entry':'enzyme_id'}, axis=1)
id_mapper_final = id_mapper_final.explode('kegg_id', ignore_index=True)
id_mapper_final = id_mapper_final.explode('EC', ignore_index=True)

# id_mapper_final = id_mapper_final.drop_duplicates(subset = ['kegg_id'])
id_mapper_final.head()

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number,enzyme_id,Protein names,Length,Mass,Rhea ID
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.85,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.86,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
2,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.61,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
3,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.59,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
4,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.-,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097

In [8]:
#get the json file from GotEnzymes and parse into workable format
#read in the json file obtained from gotEnzymes (for 'eco')
eco_enzymes_json = pd.read_json(GOTENZYMES_FILE_PATH)
#convert to a readible format
eco_enzymes = eco_enzymes_json.enzymes.to_list()
eco_enzymes_df = pd.DataFrame(eco_enzymes)

#ensure there is only one ec number per row
eco_enzymes_df['ec_number'] = eco_enzymes_df['ec_number'].str.split(pat=';')
eco_enzymes_df = eco_enzymes_df.explode('ec_number', ignore_index=True)
eco_enzymes_df = eco_enzymes_df.dropna(axis=0, subset=['ec_number'])
eco_enzymes_df = eco_enzymes_df.drop(['organism', 'domain'], axis = 1)
eco_enzymes_df.head()

      gene reaction_id ec_number compound  kcat_values
0  PP_0004      R08701             C00101       3.6784
1  PP_0004      R08701             C00037       1.4164
2  PP_0004      R08701             C03479       3.2723
3  PP_0005      R08701             C00101       2.4913
4  PP_0005      R08701             C03479       2.1913

In [9]:
# match BiGG and GotEnzymes based on gene id
eco_enzymes_merged = id_mapper_final.merge(eco_enzymes_df, 
                              left_on =['b_number', 'kegg_id'], 
                              right_on = ['gene', 'reaction_id'],
                             how = 'left').drop(['gene', 'reaction_id'], axis=1).rename({'b_number':'gene'}, axis=1)
eco_enzymes_merged

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,Protein names,Length,Mass,Rhea ID,ec_number,compound,kcat_values
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.85,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.86,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
2,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.61,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
3,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.59,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
4,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.-,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8279,4MBZDH,NaN,NaN,MNXR95031,"[C06758, [C00001, C01328], C00003]","[C00080, C00004, C01454]",1.2.1.7,pWW0_131,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,NaN,NaN,NaN
8280,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN,NaN,NaN,NaN
8281,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,NaN,NaN,NaN
8282,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN,NaN,NaN,NaN
8283,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,NaN,NaN,NaN

### 6. Extract directionalities and gapfill
Reactions which are associated with an enzyme, but not with a kcat from GotEnzymes will be assignes
a default kcat and if required a default molmass.

In [21]:
# Get directionalities and fill in the gaps
eco_enzymes_mapped = eco_enzymes_merged.copy()
import numpy as np

# Default direction
eco_enzymes_mapped['direction'] = 'f'
eco_enzymes_mapped['Length'] = eco_enzymes_mapped['Length'].fillna(DEFAULT_PROT_LENGTH)


# Assign direction for rows with kcat values
eco_enzymes_mapped['direction'] = np.where(
    eco_enzymes_mapped['kcat_values'].notna() & eco_enzymes_mapped['compound'].isin(eco_enzymes_mapped['Products']), 
    'b',
    eco_enzymes_mapped['direction']
)

# Assign default genes for unmappable proteins
eco_enzymes_mapped.loc[
    (eco_enzymes_mapped['GPR'] == '') & eco_enzymes_mapped['EC'].notna(),
    ['gene', 'GPR', 'enzyme_id']
] = eco_enzymes_mapped.apply(lambda row: [
    f'Gene_{row.rxn_id}_{row.EC}',
    f'Gene_{row.rxn_id}_{row.EC}',
    f'Enzyme_{row.rxn_id}_{row.EC}'
], axis=1, result_type="expand")


# Assign enzyme IDs if missing but gene information is available
eco_enzymes_mapped['enzyme_id'] = np.where(
    eco_enzymes_mapped['enzyme_id'].isna() & eco_enzymes_mapped['GPR'].str.len() > 0,
    eco_enzymes_mapped['gene'].apply(lambda x: f'Enzyme_{x}' if isinstance(x, str) else None),
    eco_enzymes_mapped['enzyme_id']
)

# Handle specific cases
#PP_s0001 is a gene which is not mappable
eco_enzymes_mapped.loc[eco_enzymes_mapped['GPR'] == 'PP_s0001', ['gene', 'enzyme_id']] = eco_enzymes_mapped.apply(
    lambda row: ('PP_s0001', f'Enzyme_s0001_{row.rxn_id}'),
    axis=1, result_type="expand"
)
#pWW0 is a suffix included in the gene ids for genes on a plasmid
eco_enzymes_mapped.loc[
    eco_enzymes_mapped['GPR'].str.contains('pWW0', na=False), 
    'gene'
] = eco_enzymes_mapped['GPR']

# Assign default kcat and mass values where missing
eco_enzymes_mapped['kcat_values'] = np.where(
    eco_enzymes_mapped['kcat_values'].isna() & eco_enzymes_mapped['enzyme_id'].notna(),
    DEFAULT_KCAT,
    eco_enzymes_mapped['kcat_values']
)

eco_enzymes_mapped['Mass'] = np.where(
    eco_enzymes_mapped['Mass'].isna() & (eco_enzymes_mapped['GPR'].str.len() > 2),
    DEFAULT_PROT_MW,
    eco_enzymes_mapped['Mass']
)
#clean up the dataframe
eco_enzymes_mapped = eco_enzymes_mapped.drop(['ec_number', 'compound'], axis=1).rename({'Mass':'molMass'}, axis =1)

In [26]:
protein2gene, gene2protein = get_protein_gene_mapping(eco_enzymes_mapped, model)


# Ensure the enzyme complexes are merged on one row
eco_enzymes_final = merge_enzyme_complexes(eco_enzymes_mapped, gene2protein)

# Save the adjusted dataframe or continue processing
eco_enzymes_final.drop_duplicates(subset = ['rxn_id', 'enzyme_id', 'direction'], inplace = True)

In [ ]:
#save the dataframe
# eco_enzymes_mapped = eco_enzymes_mapped.drop_duplicates(subset = ['rxn_id', 'gene', 'direction'],
#                                                        ignore_index=True)
# eco_enzymes_mapped.to_excel(AE_OUTPUT_FILE_PATH)

### 7. Save the dataframe to the proper format for building PAMs

In [27]:
other_sheets = pd.read_excel(PAM_DATA_FILE_PATH, sheet_name = None)
del other_sheets['ActiveEnzymes']
# Save it to a new excel file
with pd.ExcelWriter(OUTPUT_FILE_PATH) as writer:
    eco_enzymes_mapped.to_excel(writer, sheet_name='ActiveEnzymes', index=False)
    for sheet_name, sheet in other_sheets.items():
        if sheet_name == 'ExcessEnzymes': sheet_name = 'UnusedEnzyme'
        sheet.to_excel(writer, sheet_name = sheet_name, index=False)