# Initializing kcat values for PAMparametrizer

In this notebook, we give an overview of how an initial set of turnover number can be obtained. To enable this, we use multiple databases to map kcat values obtained from machine learning (from the [GotEnzymes](https://metabolicatlas.org/gotenzymes) database) to the proteins and reactions in the model using the gene-protein-reaction associations.

Before we start, we have to set up all the package and files required. Adjust the filenames and paths as desired. Importantly, make sure to **adjust the regular expression in the cell below** in order to find the gene names associated with the organism you want to model.

In [1]:
import pandas as pd
import os
from cobra.io import load_json_model, read_sbml_model
import matplotlib.pyplot as plt
import re
import numpy as np
import datetime

if os.path.split(os.getcwd())[1]=='i1_preprocessing':
    os.chdir('../..')
    
from PAModelpy.utils.pam_generation import merge_enzyme_complexes, get_protein_gene_mapping, _parse_gpr


DEFAULT_PROT_MW = 39959.4825 #g/mol
DEFAULT_KCAT =  13.7 #/s median value from BRENDA

PAM_DATA_FILE_PATH = os.path.join('Data', 'proteinAllocationModel_iML1515_EnzymaticData_new.xls')
UNIPROT_FILE_PATH = os.path.join('Data', 'Databases','uniprotkb_cglutamicumATCC13032_250124.xlsx')
NCBI_FILE_PATH = os.path.join('Data','Cglutanicum_phenotypes','NCBI_genes_corynglutatcc13032_250207.tsv')
GOTENZYMES_FILE_PATH = os.path.join('Data','Databases', 'GotEnzymes_cgl_250124.json')

Loading PAModelpy modules version 0.0.4.6

In [2]:
#output file path
# Create a datetime object for the current date
current_date = datetime.datetime.now()
# Format the date as yymmdd
formatted_date = current_date.strftime('%y%m%d')

OUTPUT_FILE_PATH = os.path.join('Results', '1_preprocessing', f'proteinAllocationModel_iCGB21FR_EnzymaticData_{formatted_date}.xlsx')
AE_OUTPUT_FILE_PATH = os.path.join('Results', '1_preprocessing', f'{formatted_date}_cgl_ActiveEnzymeInformation_GotEnzymes.xlsx')

Relatively complicated regex because of complex gene names

1. WP_\d+_\d+: Matches identifiers starting with WP_ followed by digits (\d+), an underscore, and more digits.
2. |: Alternation operator to separate different patterns.
3. lcl_NC_\d+_\d+_prot_: Matches strings starting with lcl_NC_, followed by digits, an underscore, more digits, _prot_, and then:

    - WP_\d+_\d+_\d+: Matches WP_ identifiers with an additional _ and digits at the end.
    - |\d+: Matches a plain numeric sequence following _prot_.

4. |: Alternation operator for the next part.
5. cgl\d{4}: Matches strings starting with cgl followed by exactly 4 digits.

In [3]:
#You need to adjust this to find the geneid/locustag for your microbe
locustag_regex =r'(?:WP_\d+_\d+|lcl_NC_\d+_\d+_prot_(?:WP_\d+_\d+_\d+|\d+)|[cC]gl\d{4}|[cC]g\d{4})'

## 0. Download information from different databases
1. **Metabolic model stoichiometries and reactions: [BioModels](https://www.ebi.ac.uk/biomodels/)**
- Get your model! Or use your own reaction identifiers
- In this example we will use the iCGB21FR model for [*Corynebacterium glutamicum* ATCC 13032](https://www.ebi.ac.uk/biomodels/MODEL2102050001#Overview)

2. **Turnover numbers: [GotEnzymes](https://metabolicatlas.org/gotenzymes)**
- Go to the [API of the Metabolic Atlas](https://metabolicatlas.org/api/v2/#/GotEnzymes/gotEnzymes)
- Use the `GET\gotenzymes\enzymes?` functionality, click `Try it out`
- Here we filled in `cgl` (*C. glutanicum* ATCC 13032) for `organism` and `10000` for `pagination[pageSize]`. The rest was left empty
- Click execute and a json file with all the information will be downloaded

3. **Gene-Protein-Reaction relations: [UniprotKB](https://www.uniprot.org/)**
- Go to the [Uniprot knowledge base](https://www.uniprot.org/) and used advanced search to query for your organism. For *C. glutanicum* we used [this](https://www.uniprot.org/uniprotkb?query=(taxonomy_id:196627)) webpage
- Click download, select `format`:`Excel` and select the following: 
    - `Uniprot Data -> Names & Taxonomy`: `Gene Names`
    - `Uniprot Data -> Sequences`: `length`, `mass`
    - `Uniprot Data -> Function`: `RheaID`
- Download the resulting Excel file

4. **NCBI gene id to KEGG gene id mapping**: [NCBI database](https://www.ncbi.nlm.nih.gov/)
- The model identifiers for this model are in NCBI format, but we need the KEGG locus tag ids to map the genes to the corresponding Uniprot ids. Therefore, we use the mapping provided by NCBI.
- Go to the NCBI gene list for *C. glutanicum* on [NCBI genes](https://www.ncbi.nlm.nih.gov/gene/?term=Corynebacterium+glutamicum+ATCC+13032)
- On the top left click `send to`, select `file` and `text`

## 1. Get information from the model

In the metabolic model itself is already quite some information stored. In order to obtain up-to-date information on the enzymes related to the reaction, we will need to obtain the kegg reaction ID, the reactants, the product and the gene-protein relation.

In [4]:
def create_id_mapper_from_model(model):
    expand=False

    #make a id mapping and create a mapping dataframe
    id_mapper_df = pd.DataFrame(columns = ['rxn_id', 'kegg_id', 'rhea_id', 'mnx_id','Reactants','Products','EC', 'GPR'])
    for rxn in model.reactions:
        #skip transport reactions and ATP maintenance requirement
        if 'ex' in rxn.id or 'EX' in rxn.id or rxn.id == 'ATPM':
            continue
        to_append= []   

        to_append.append(rxn.id)
        #not all reactions are annotated with a KEGG ID in the model
        try: 
            to_append.append(rxn.annotation['kegg.reaction'])
        except:
            to_append.append(np.nan)
        try: 
            to_append.append(rxn.annotation['rhea'])
        except:
            to_append.append(np.nan)
        try: 
            to_append.append(rxn.annotation['metanetx.reaction'])
        except:
            to_append.append(np.nan)
        try:
            to_append.append([reac.annotation['kegg.compound'] for reac in rxn.reactants])
        except:
            to_append.append([])
        try: 
            to_append.append([prod.annotation['kegg.compound'] for prod in rxn.products])
        except:
            to_append.append([])
        if 'ec-code' in rxn.annotation.keys():
            #if there are multiple enzymes make seperate lists
            if isinstance(rxn.annotation['ec-code'], list) and expand:
                info = to_append.copy()
                for i in range(len(rxn.annotation['ec-code'])):
                    #make a new row for each enzyme by copying the previous information
                    info = to_append.copy()
                    ec= rxn.annotation['ec-code'][i]
                    info.append(ec)
                    #add gpr
                    info.append(rxn.gene_reaction_rule)
                    #add to df
                    id_mapper_df.loc[len(id_mapper_df)] = info
            else:
                to_append.append(rxn.annotation['ec-code'])
                to_append.append(rxn.gene_reaction_rule)
                id_mapper_df.loc[len(id_mapper_df)] = to_append
        else:
            to_append.append(np.nan)
            #ignore entries without enzyme and gpr relation
            if rxn.gene_reaction_rule =='':
                continue
            else:
                to_append.append(rxn.gene_reaction_rule)
            id_mapper_df.loc[len(id_mapper_df)] = to_append

    #remove entries without GRP relation or Ec number


    print('Number of reactions in the mapping dataframe: ',len(id_mapper_df))
    print('Number of reactions mapped to KEGG identifier: ', len(id_mapper_df.kegg_id.dropna()))
    print('Number of reactions mapped to rhea identifier: ', len(id_mapper_df.rhea_id.dropna()))
    print('Number of reactions mapped to MetaNetX identifier: ', len(id_mapper_df.mnx_id.dropna()))
    return id_mapper_df

print('mapping the ids from the iCW773 model')
id_mapper_icw = create_id_mapper_from_model(load_json_model(os.path.join('Models', 'iCW773_Niu2022.json')))

print('\nmapping the ids from the iCGB21FR model')
model =read_sbml_model(os.path.join('Models', 'iCGB21FR.xml'))
id_mapper_icg = create_id_mapper_from_model(model)

mapping the ids from the iCW773 model
Set parameter Username
Academic license - for non-commercial use only - expires 2025-03-06

SBML package 'layout' not supported by cobrapy, information is not parsed
https://juser.fz-juelich.de/record/188973 does not conform to 'http(s)://identifiers.org/collection/id' or'http(s)://identifiers.org/COLLECTION:id

Number of reactions in the mapping dataframe:  804
Number of reactions mapped to KEGG identifier:  0
Number of reactions mapped to rhea identifier:  0
Number of reactions mapped to MetaNetX identifier:  0

mapping the ids from the iCGB21FR model
Number of reactions in the mapping dataframe:  1147
Number of reactions mapped to KEGG identifier:  491
Number of reactions mapped to rhea identifier:  643
Number of reactions mapped to MetaNetX identifier:  1120

In [5]:
id_mapper_df = pd.merge(id_mapper_icg, id_mapper_icw[['rxn_id', 'GPR']], on='rxn_id', how = 'left')
id_mapper_df

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR_x,GPR_y
0,2AGPEAT160,NaN,NaN,MNXR94760,[],[],2.3.1.40,,NaN
1,2AGPEAT180,NaN,NaN,MNXR94762,[],[],2.3.1.40,,NaN
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or lc...,Cgl1176
3,3HAD140,R04568,NaN,MNXR94879,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[4.2.1.61, 2.3.1.86, 2.3.1.-, 2.3.1.85, 4.2.1.59]",,Cgl0289
4,3MBt2pp,NaN,NaN,MNXR94916,"[C00080, C08262]","[C08262, C00080]",NaN,lcl_NC_006958_1_prot_WP_011013917_1_810,NaN
...,...,...,...,...,...,...,...,...,...
1142,Ca2t2,NaN,NaN,NaN,"[C00076, C00080]","[C00076, C00080]",NaN,WP_011014107_1,NaN
1143,CAT,R00009,"[20309, 20310, 20311, 20312]",MNXR96455,"[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[1.11.1.21, 1.11.1.6]",WP_011013509_1,Cgl0255
1144,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,
1145,PRFGS_1,NaN,"[17129, 17131, 17130, 17132]",MNXR138721,"[[C00002, C00002;D08646], C04376, [C00064, C00...","[[C00008, C00008;G11113], C04640, [C00025, C00...",6.3.5.3,lcl_NC_006958_1_prot_WP_003854010_1_2470,NaN
1146,PYRt,NaN,NaN,MNXR103384,[C00022],[C00022],NaN,WP_011014733_1,NaN

### Map the NCBI gene names to KEGG gene names

In the iCGB21FR model, the gene names are by default the ncbi gene names. To map the gene-protein-reaction associations to the corresponding uniprot peptide identifiers, we need to map the model gene names to the kegg gene names.

In [6]:
ncbi_genes = pd.read_csv(NCBI_FILE_PATH,sep = '\t')
ncbi_genes.head()

,tax_id,Org_name,GeneID,CurrentID,Status,Symbol,Aliases,description,other_designations,map_location,chromosome,genomic_nucleotide_accession.version,start_position_on_the_genomic_accession,end_position_on_the_genomic_accession,orientation,exon_count,OMIM,Unnamed: 17
0,196627,Corynebacterium glutamicum ATCC 13032,1019166,0,live,CGL_RS05895,"CGL_RS05895, NCgl1136",homoserine dehydrogenase,homoserine dehydrogenase,NaN,NaN,NC_003450.3,1242507.0,1243844.0,plus,0,NaN,NaN
1,196627,Corynebacterium glutamicum ATCC 13032,1019114,0,live,CGL_RS05635,"CGL_RS05635, NCgl1084",multifunctional oxoglutarate decarboxylase/oxo...,multifunctional oxoglutarate decarboxylase/oxo...,NaN,NaN,NC_003450.3,1172498.0,1176163.0,minus,0,NaN,NaN
2,196627,Corynebacterium glutamicum ATCC 13032,1020564,0,live,CGL_RS13060,"CGL_RS13060, NCgl2528",diaminopimelate dehydrogenase,diaminopimelate dehydrogenase,NaN,NaN,NC_003450.3,2786754.0,2787716.0,minus,0,NaN,NaN
3,196627,Corynebacterium glutamicum ATCC 13032,92792280,0,live,trpL,CGL_RS15555,trp operon leader peptide,trp operon leader peptide,NaN,NaN,NC_003450.3,3233152.0,3233205.0,plus,0,NaN,NaN
4,196627,Corynebacterium glutamicum ATCC 13032,1020138,0,live,pimB,"CGL_RS10855, NCgl2106",GDP-mannose-dependent monoacylated alpha-(1-6)...,GDP-mannose-dependent monoacylated alpha-(1-6)...,NaN,NaN,NC_003450.3,2317631.0,2318776.0,minus,0,NaN,NaN

In [ ]:
from Bio import SeqIO

# Replace with the path to your GPFF file or URL to download it
gpff_file_bielfeld = "Data/Cglutanicum_phenotypes/GCA_000196335.1_ASM19633v1_protein.gpff"  # Use a local file or an online URL
gpff_file_kyoto = "Data/Cglutanicum_phenotypes/GCF_000011325.1_ASM1132v1_protein.gpff"  # Use a local file or an online URL

bielefeld_records = SeqIO.parse(gpff_file_bielfeld, "genbank")
kyoto_records = SeqIO.parse(gpff_file_kyoto, "genbank")

# Parse the GPFF file
i=0

from collections import defaultdict

mapping = defaultdict(list)

while i<10:
    for record in bielefeld_records:
        # Loop over the features to find db_xrefs
        for feature in record.features:
            if "db_xref" in feature.qualifiers:
                reference = dict()
                for db_xref in feature.qualifiers["db_xref"]:
                    ref = db_xref.strip().split(':')
                    reference[ref[0]] = ref[1]
                for rec in kyoto_records:
                    if record.seq == rec.seq:
                        mapping[rec.id].append(reference)
            
    
print(mapping)

{'taxon': '196627'}
{'GOA': 'Q8NUD8', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NUD7'}
{'taxon': '196627'}
{'GOA': 'Q8NUD6', 'InterPro': 'IPR022637', 'UniProtKB/TrEMBL': 'Q8NUD6'}
{'taxon': '196627'}
{'GOA': 'Q6M8X7', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'InterPro': 'IPR023007'}
{'taxon': '196627'}
{'GOA': 'Q6M8X6', 'InterPro': 'IPR020568', 'UniProtKB/TrEMBL': 'Q6M8X6'}
{'taxon': '196627'}
{'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q8NUD2'}
{'taxon': '196627'}
{'InterPro': 'IPR003740', 'UniProtKB/TrEMBL': 'Q8NUD1'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NUD0'}
{'taxon': '196627'}
{'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NUC9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NUC8'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NUC7'}
{'taxon': '196627'}
{'GOA': 'Q8NUC6', 'InterPro': 'IPR024946', 'UniProtKB/TrEMBL': 'Q8NUC6'}
{'taxon': '196627'}
{'InterPro': 'IPR021949', 'UniProtKB/TrEMBL': 'Q8NUC5'}
{'taxon': '196627'}
{'GOA': 'Q6M8W7', 'InterPro': 'IPR018383'}
{'taxon': '196627'}
{'GOA': 'Q8NUC3', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NUC3'}
{'taxon': '196627'}
{'InterPro': 'IPR018958', 'UniProtKB/TrEMBL': 'Q8NUC2'}
{'taxon': '196627'}
{'GOA': 'Q8NUC1', 'InterPro': 'IPR003834', 'UniProtKB/TrEMBL': 'Q8NUC1'}
{'taxon': '196627'}
{'GOA': 'Q6M8W3', 'InterPro': 'IPR012336', 'UniProtKB/TrEMBL': 'Q6M8W3'}
{'taxon': '196627'}
{'GOA': 'Q8NUB9', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NUB9'}
{'taxon': '196627'}
{'GOA': 'Q6M8W1', 'InterPro': 'IPR001915', 'UniProtKB/TrEMBL': 'Q6M8W1'}
{'taxon': '196627'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8V9'}
{'taxon': '196627'}
{'taxon': '196627'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8V8'}
{'taxon': '196627'}
{'GOA': 'Q6M8V7', 'InterPro': 'IPR019953', 'UniProtKB/TrEMBL': 'Q6M8V7'}
{'taxon': '196627'}
{'GOA': 'Q6M8Y9', 'InterPro': 'IPR025831', 'UniProtKB/TrEMBL': 'Q6M8Y9'}
{'taxon': '196627'}
{'InterPro': 'IPR015943', 'UniProtKB/TrEMBL': 'Q8NUB3'}
{'taxon': '196627'}
{'GOA': 'Q8NUB2', 'InterPro': 'IPR006129', 'UniProtKB/TrEMBL': 'Q8NUB2'}
{'taxon': '196627'}
{'GOA': 'Q8NUB1', 'InterPro': 'IPR029022', 'UniProtKB/TrEMBL': 'Q8NUB1'}
{'taxon': '196627'}
{'GOA': 'Q8NUB0', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NUB0'}
{'taxon': '196627'}
{'InterPro': 'IPR028082', 'UniProtKB/TrEMBL': 'Q8NUA9'}
{'taxon': '196627'}
{'GOA': 'Q8NUA8', 'InterPro': 'IPR001851', 'UniProtKB/TrEMBL': 'Q8NUA8'}
{'taxon': '196627'}
{'GOA': 'Q8NUA7', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NUA7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8Y1'}
{'taxon': '196627'}
{'GOA': 'Q6M8Y0', 'InterPro': 'IPR029000', 'UniProtKB/TrEMBL': 'Q6M8Y0'}
{'taxon': '196627'}
{'GOA': 'Q8NUA4', 'InterPro': 'IPR022764', 'UniProtKB/TrEMBL': 'Q8NUA4'}
{'taxon': '196627'}
{'GOA': 'Q6M8Z3', 'InterPro': 'IPR029022', 'UniProtKB/TrEMBL': 'Q6M8Z3'}
{'taxon': '196627'}
{'GOA': 'Q8NUA3', 'InterPro': 'IPR018060', 'UniProtKB/TrEMBL': 'Q8NUA3'}
{'taxon': '196627'}
{'GOA': 'Q8NUA1', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NUA1'}
{'taxon': '196627'}
{'InterPro': 'IPR013113', 'UniProtKB/TrEMBL': 'Q8NUA0'}
{'taxon': '196627'}
{'GOA': 'Q8NU99', 'InterPro': 'IPR009619'}
{'taxon': '196627'}
{'GOA': 'Q8NU98', 'InterPro': 'IPR017441'}
{'taxon': '196627'}
{'GOA': 'Q8NU97', 'InterPro': 'IPR017441'}
{'taxon': '196627'}
{'GOA': 'Q8NU96', 'InterPro': 'IPR012338', 'UniProtKB/TrEMBL': 'Q8NU96'}
{'taxon': '196627'}
{'GOA': 'Q6M8V5', 'InterPro': 'IPR001182', 'UniProtKB/TrEMBL': 'Q6M8V5'}
{'taxon': '196627'}
{'GOA': 'Q6M8V4', 'InterPro': 'IPR015655', 'UniProtKB/TrEMBL': 'Q6M8V4'}
{'taxon': '196627'}
{'InterPro': 'IPR008984', 'UniProtKB/TrEMBL': 'Q8NU93'}
{'taxon': '196627'}
{'InterPro': 'IPR022128', 'UniProtKB/TrEMBL': 'Q6M8V2'}
{'taxon': '196627'}
{'GOA': 'Q8NU91', 'UniProtKB/TrEMBL': 'Q8NU91'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU90'}
{'taxon': '196627'}
{'GOA': 'Q8NU88', 'InterPro': 'IPR012941', 'UniProtKB/TrEMBL': 'Q8NU88'}
{'taxon': '196627'}
{'GOA': 'Q8NU89', 'InterPro': 'IPR029510', 'UniProtKB/TrEMBL': 'Q8NU89'}
{'taxon': '196627'}
{'InterPro': 'IPR001763', 'UniProtKB/TrEMBL': 'Q6M8U7'}
{'taxon': '196627'}
{'GOA': 'Q6M8U6', 'InterPro': 'IPR002781', 'UniProtKB/TrEMBL': 'Q6M8U6'}
{'taxon': '196627'}
{'GOA': 'Q8NU85', 'InterPro': 'IPR001763', 'UniProtKB/TrEMBL': 'Q8NU85'}
{'taxon': '196627'}
{'GOA': 'Q8NU84', 'InterPro': 'IPR021309', 'UniProtKB/TrEMBL': 'Q8NU84'}
{'taxon': '196627'}
{'InterPro': 'IPR003735', 'UniProtKB/TrEMBL': 'Q6M8U3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU82'}
{'taxon': '196627'}
{'InterPro': 'IPR023577', 'UniProtKB/TrEMBL': 'Q8NU81'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU80'}
{'taxon': '196627'}
{'InterPro': 'IPR014867', 'UniProtKB/TrEMBL': 'Q6M8T9'}
{'taxon': '196627'}
{'GOA': 'Q8NU78', 'InterPro': 'IPR002523', 'UniProtKB/TrEMBL': 'Q8NU78'}
{'taxon': '196627'}
{'InterPro': 'IPR028116', 'PDB': '3N4H', 'UniProtKB/TrEMBL': 'Q8NU77'}
{'taxon': '196627'}
{'GOA': 'Q6M8T6', 'InterPro': 'IPR014743', 'UniProtKB/TrEMBL': 'Q6M8T6'}
{'taxon': '196627'}
{'GOA': 'Q8NU75', 'InterPro': 'IPR006419', 'UniProtKB/TrEMBL': 'Q8NU75'}
{'taxon': '196627'}
{'GOA': 'Q6M8T4', 'InterPro': 'IPR029060', 'UniProtKB/TrEMBL': 'Q6M8T4'}
{'taxon': '196627'}
{'GOA': 'Q8NU73', 'UniProtKB/TrEMBL': 'Q8NU73'}
{'taxon': '196627'}
{'GOA': 'Q6M8T2', 'InterPro': 'IPR014738', 'UniProtKB/TrEMBL': 'Q6M8T2'}
{'taxon': '196627'}
{'GOA': 'Q8NU71', 'InterPro': 'IPR029151', 'UniProtKB/TrEMBL': 'Q8NU71'}
{'taxon': '196627'}
{'GOA': 'Q8NU70', 'InterPro': 'IPR024187', 'UniProtKB/TrEMBL': 'Q8NU70'}
{'taxon': '196627'}
{'GOA': 'Q8NU69', 'InterPro': 'IPR029753', 'UniProtKB/TrEMBL': 'Q8NU69'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU68'}
{'taxon': '196627'}
{'GOA': 'P46396', 'InterPro': 'IPR024177'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU67'}
{'taxon': '196627'}
{'GOA': 'Q6M8S6', 'InterPro': 'IPR016694', 'UniProtKB/TrEMBL': 'Q6M8S6'}
{'taxon': '196627'}
{'GOA': 'Q8NU65', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NU65'}
{'taxon': '196627'}
{'GOA': 'Q6M8S4', 'InterPro': 'IPR013108', 'UniProtKB/TrEMBL': 'Q6M8S4'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU63'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8S2'}
{'taxon': '196627'}
{'GOA': 'Q6M8S1', 'InterPro': 'IPR029035', 'UniProtKB/TrEMBL': 'Q6M8S1'}
{'taxon': '196627'}
{'GOA': 'Q8NU60', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q8NU60'}
{'taxon': '196627'}
{'GOA': 'Q8NU59', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q8NU59'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8R8'}
{'taxon': '196627'}
{'GOA': 'Q8NU57', 'InterPro': 'IPR023187', 'UniProtKB/TrEMBL': 'Q8NU57'}
{'taxon': '196627'}
{'GOA': 'Q9RHM6', 'InterPro': 'IPR012010'}
{'taxon': '196627'}
{'GOA': 'Q79VJ4', 'InterPro': 'IPR002019'}
{'taxon': '196627'}
{'GOA': 'Q79VJ3', 'InterPro': 'IPR017951'}
{'taxon': '196627'}
{'GOA': 'Q9RHM3', 'InterPro': 'IPR012406'}
{'taxon': '196627'}
{'GOA': 'Q79VJ2', 'InterPro': 'IPR002639'}
{'taxon': '196627'}
{'GOA': 'Q79VJ1', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q79VJ0', 'InterPro': 'IPR002669'}
{'taxon': '196627'}
{'GOA': 'Q8NU56', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q8NU56'}
{'taxon': '196627'}
{'GOA': 'Q8NU55', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NU55'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU54'}
{'taxon': '196627'}
{'GOA': 'Q8NU53', 'InterPro': 'IPR020575', 'UniProtKB/TrEMBL': 'Q8NU53'}
{'taxon': '196627'}
{'GOA': 'Q6M8Q7', 'InterPro': 'IPR018953', 'UniProtKB/TrEMBL': 'Q6M8Q7'}
{'taxon': '196627'}
{'InterPro': 'IPR029035', 'UniProtKB/TrEMBL': 'Q8NU51'}
{'taxon': '196627'}
{'GOA': 'Q8NU50', 'InterPro': 'IPR029061', 'UniProtKB/TrEMBL': 'Q8NU50'}
{'taxon': '196627'}
{'InterPro': 'IPR025711', 'UniProtKB/TrEMBL': 'Q6M8Q4'}
{'taxon': '196627'}
{'GOA': 'Q8NU48', 'InterPro': 'IPR029041', 'UniProtKB/TrEMBL': 'Q8NU48'}
{'taxon': '196627'}
{'GOA': 'Q8NU47', 'InterPro': 'IPR023210', 'UniProtKB/TrEMBL': 'Q8NU47'}
{'taxon': '196627'}
{'GOA': 'Q6M8Q1', 'InterPro': 'IPR004697', 'UniProtKB/TrEMBL': 'Q6M8Q1'}
{'taxon': '196627'}
{'GOA': 'Q6M8Q0', 'InterPro': 'IPR017439', 'UniProtKB/TrEMBL': 'Q6M8Q0'}
{'taxon': '196627'}
{'InterPro': 'IPR003807', 'UniProtKB/TrEMBL': 'Q8NU44'}
{'taxon': '196627'}
{'InterPro': 'IPR020264', 'UniProtKB/TrEMBL': 'Q8NU43'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8P7'}
{'taxon': '196627'}
{'GOA': 'Q8NU41', 'InterPro': 'IPR018356', 'UniProtKB/TrEMBL': 'Q8NU41'}
{'taxon': '196627'}
{'InterPro': 'IPR029068', 'UniProtKB/TrEMBL': 'Q6M8P5'}
{'taxon': '196627'}
{'GOA': 'Q8NU39', 'InterPro': 'IPR029033', 'UniProtKB/TrEMBL': 'Q8NU39'}
{'taxon': '196627'}
{'GOA': 'Q8NU38', 'InterPro': 'IPR023027', 'UniProtKB/TrEMBL': 'Q8NU38'}
{'taxon': '196627'}
{'GOA': 'Q8NU37', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NU37'}
{'taxon': '196627'}
{'GOA': 'Q6M8P1', 'InterPro': 'IPR018356', 'UniProtKB/TrEMBL': 'Q6M8P1'}
{'taxon': '196627'}
{'GOA': 'Q6M8P0', 'InterPro': 'IPR018485', 'UniProtKB/TrEMBL': 'Q6M8P0'}
{'taxon': '196627'}
{'GOA': 'Q9X713', 'InterPro': 'IPR014729'}
{'taxon': '196627'}
{'GOA': 'Q9X712', 'InterPro': 'IPR015813'}
{'taxon': '196627'}
{'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NU34'}
{'taxon': '196627'}
{'GOA': 'Q8NU33', 'InterPro': 'IPR011034'}
{'taxon': '196627'}
{'GOA': 'Q8NU32', 'InterPro': 'IPR014922', 'UniProtKB/TrEMBL': 'Q8NU32'}
{'taxon': '196627'}
{'GOA': 'Q8NU31', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q8NU31'}
{'taxon': '196627'}
{'GOA': 'Q6M8N6', 'InterPro': 'IPR023214', 'UniProtKB/TrEMBL': 'Q6M8N6'}
{'taxon': '196627'}
{'GOA': 'Q8NU29', 'InterPro': 'IPR011004', 'UniProtKB/TrEMBL': 'Q8NU29'}
{'taxon': '196627'}
{'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NU28'}
{'taxon': '196627'}
{'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NU27'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8N2'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU25'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU24'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU23'}
{'taxon': '196627'}
{'GOA': 'Q8NU22', 'InterPro': 'IPR029044', 'UniProtKB/TrEMBL': 'Q8NU22'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU21'}
{'taxon': '196627'}
{'InterPro': 'IPR020683', 'UniProtKB/TrEMBL': 'Q8NU19'}
{'taxon': '196627'}
{'GOA': 'Q79VI9', 'InterPro': 'IPR002781', 'UniProtKB/TrEMBL': 'Q79VI9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8M4'}
{'taxon': '196627'}
{'GOA': 'Q8NU17', 'InterPro': 'IPR005115', 'UniProtKB/TrEMBL': 'Q8NU17'}
{'taxon': '196627'}
{'InterPro': 'IPR005184', 'UniProtKB/TrEMBL': 'Q8NU16'}
{'taxon': '196627'}
{'GOA': 'Q9X4N0', 'InterPro': 'IPR009010'}
{'taxon': '196627'}
{'InterPro': 'IPR010281', 'UniProtKB/TrEMBL': 'Q8NU15'}
{'taxon': '196627'}
{'GOA': 'Q8NU14', 'InterPro': 'IPR017516', 'UniProtKB/TrEMBL': 'Q8NU14'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8L9'}
{'taxon': '196627'}
{'GOA': 'Q6M8L8', 'InterPro': 'IPR002781', 'UniProtKB/TrEMBL': 'Q6M8L8'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8L7'}
{'taxon': '196627'}
{'GOA': 'Q6M8L6', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q6M8L6'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NU09'}
{'taxon': '196627'}
{'GOA': 'Q6M8L4', 'InterPro': 'IPR024688', 'UniProtKB/TrEMBL': 'Q6M8L4'}
{'taxon': '196627'}
{'GOA': 'Q8NU07', 'InterPro': 'IPR027450', 'UniProtKB/TrEMBL': 'Q8NU07'}
{'taxon': '196627'}
{'GOA': 'Q6M8L2', 'InterPro': 'IPR011257', 'UniProtKB/TrEMBL': 'Q6M8L2'}
{'taxon': '196627'}
{'GOA': 'Q8NU05', 'InterPro': 'IPR001123', 'UniProtKB/TrEMBL': 'Q8NU05'}
{'taxon': '196627'}
{'GOA': 'Q8NU04', 'InterPro': 'IPR002942', 'UniProtKB/TrEMBL': 'Q8NU04'}
{'taxon': '196627'}
{'GOA': 'Q8NU03', 'InterPro': 'IPR029068', 'UniProtKB/TrEMBL': 'Q8NU03'}
{'taxon': '196627'}
{'GOA': 'Q8NU02', 'InterPro': 'IPR014048', 'UniProtKB/TrEMBL': 'Q8NU02'}
{'taxon': '196627'}
{'InterPro': 'IPR012338', 'UniProtKB/TrEMBL': 'Q6M8K7'}
{'taxon': '196627'}
{'GOA': 'Q6M8K6', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q6M8K6'}
{'taxon': '196627'}
{'InterPro': 'IPR013813', 'UniProtKB/TrEMBL': 'Q6M8K5'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8K4'}
{'taxon': '196627'}
{'GOA': 'Q6M8K3', 'InterPro': 'IPR024079', 'UniProtKB/TrEMBL': 'Q6M8K3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NTZ6'}
{'taxon': '196627'}
{'GOA': 'Q8NTZ5', 'InterPro': 'IPR026898', 'UniProtKB/TrEMBL': 'Q8NTZ5'}
{'taxon': '196627'}
{'GOA': 'Q8NTZ4', 'InterPro': 'IPR028978', 'PDB': '2P19', 'UniProtKB/TrEMBL': 'Q8NTZ4'}
{'taxon': '196627'}
{'GOA': 'Q8NTZ3', 'InterPro': 'IPR029056', 'PDB': '3PL2', 'UniProtKB/TrEMBL': 'Q8NTZ3'}
{'taxon': '196627'}
{'GOA': 'Q8NTZ2', 'InterPro': 'IPR013785', 'PDB': '3FOK', 'UniProtKB/TrEMBL': 'Q8NTZ2'}
{'taxon': '196627'}
{'GOA': 'Q8NTZ1', 'InterPro': 'IPR016163', 'UniProtKB/TrEMBL': 'Q8NTZ1'}
{'taxon': '196627'}
{'GOA': 'Q8NTZ0', 'InterPro': 'IPR024203', 'UniProtKB/TrEMBL': 'Q8NTZ0'}
{'taxon': '196627'}
{'GOA': 'Q6M8J5', 'InterPro': 'IPR029061', 'UniProtKB/TrEMBL': 'Q6M8J5'}
{'taxon': '196627'}
{'GOA': 'Q8NTY8', 'InterPro': 'IPR013022', 'UniProtKB/TrEMBL': 'Q8NTY8'}
{'taxon': '196627'}
{'GOA': 'Q8NTY7', 'InterPro': 'IPR023794'}
{'taxon': '196627'}
{'InterPro': 'IPR013022', 'UniProtKB/TrEMBL': 'Q6M8J2'}
{'taxon': '196627'}
{'GOA': 'Q8NTY5', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NTY5'}
{'taxon': '196627'}
{'GOA': 'Q8NTY4', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NTY4'}
{'taxon': '196627'}
{'InterPro': 'IPR006442', 'UniProtKB/TrEMBL': 'Q8NTY3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8I8'}
{'taxon': '196627'}
{'GOA': 'Q8NTY1', 'InterPro': 'IPR028082', 'PDB': '3GYB', 'UniProtKB/TrEMBL': 'Q8NTY1'}
{'taxon': '196627'}
{'GOA': 'Q8NTY0', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NTY0'}
{'taxon': '196627'}
{'GOA': 'Q8NTX9', 'InterPro': 'IPR013022', 'UniProtKB/TrEMBL': 'Q8NTX9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NTX8'}
{'taxon': '196627'}
{'GOA': 'Q8NTX7', 'InterPro': 'IPR019844', 'UniProtKB/TrEMBL': 'Q8NTX7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NTX6'}
{'taxon': '196627'}
{'InterPro': 'IPR027395', 'UniProtKB/TrEMBL': 'Q8NTX5'}
{'taxon': '196627'}
{'GOA': 'Q8NTX4', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q8NTX4'}
{'taxon': '196627'}
{'GOA': 'Q6M8H9', 'UniProtKB/TrEMBL': 'Q6M8H9'}
{'taxon': '196627'}
{'GOA': 'Q8NTX3', 'InterPro': 'IPR016181', 'UniProtKB/TrEMBL': 'Q8NTX3'}
{'taxon': '196627'}
{'GOA': 'Q6M8H7', 'InterPro': 'IPR028082', 'UniProtKB/TrEMBL': 'Q6M8H7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NTX1'}
{'taxon': '196627'}
{'GOA': 'Q8NTX0', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NTX0'}
{'taxon': '196627'}
{'GOA': 'Q6M3M7', 'InterPro': 'IPR025246', 'UniProtKB/TrEMBL': 'Q6M3M7'}
{'taxon': '196627'}
{'GOA': 'Q8NTW9', 'InterPro': 'IPR001610', 'UniProtKB/TrEMBL': 'Q8NTW9'}
{'taxon': '196627'}
{'GOA': 'Q8NTW8', 'InterPro': 'IPR029055', 'UniProtKB/TrEMBL': 'Q8NTW8'}
{'taxon': '196627'}
{'GOA': 'Q8NTW7', 'InterPro': 'IPR028261', 'UniProtKB/TrEMBL': 'Q8NTW7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8H0'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8G9'}
{'taxon': '196627'}
{'GOA': 'Q8NTW6', 'InterPro': 'IPR016602', 'UniProtKB/TrEMBL': 'Q8NTW6'}
{'taxon': '196627'}
{'GOA': 'Q8NTW5', 'InterPro': 'IPR027451', 'UniProtKB/TrEMBL': 'Q8NTW5'}
{'taxon': '196627'}
{'GOA': 'Q8NTW4', 'InterPro': 'IPR020963'}
{'taxon': '196627'}
{'GOA': 'Q8NTW3', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NTW3'}
{'taxon': '196627'}
{'GOA': 'Q8NTW2', 'InterPro': 'IPR016169', 'UniProtKB/TrEMBL': 'Q8NTW2'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8G3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NTW0'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NTV9'}
{'taxon': '196627'}
{'InterPro': 'IPR024047', 'UniProtKB/TrEMBL': 'Q6M8G0'}
{'taxon': '196627'}
{'GOA': 'Q6M8F9', 'InterPro': 'IPR007267', 'UniProtKB/TrEMBL': 'Q6M8F9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NTV6'}
{'taxon': '196627'}
{'GOA': 'Q8NTV5', 'InterPro': 'IPR015808', 'UniProtKB/TrEMBL': 'Q8NTV5'}
{'taxon': '196627'}
{'GOA': 'Q8NTV4', 'InterPro': 'IPR029044', 'UniProtKB/TrEMBL': 'Q8NTV4'}
{'taxon': '196627'}
{'InterPro': 'IPR029068', 'UniProtKB/TrEMBL': 'Q8NTV3'}
{'taxon': '196627'}
{'GOA': 'Q8NTV2', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NTV2'}
{'taxon': '196627'}
{'GOA': 'Q6M8F3', 'InterPro': 'IPR013525', 'UniProtKB/TrEMBL': 'Q6M8F3'}
{'taxon': '196627'}
{'GOA': 'Q6M8F2', 'InterPro': 'IPR015424', 'UniProtKB/TrEMBL': 'Q6M8F2'}
{'taxon': '196627'}
{'GOA': 'Q8NTU9', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NTU9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8F0'}
{'taxon': '196627'}
{'GOA': 'Q6M8E9', 'InterPro': 'IPR012675', 'UniProtKB/TrEMBL': 'Q6M8E9'}
{'taxon': '196627'}
{'GOA': 'Q6M8E8', 'InterPro': 'IPR001463', 'UniProtKB/TrEMBL': 'Q6M8E8'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8E7'}
{'taxon': '196627'}
{'InterPro': 'IPR025159', 'UniProtKB/TrEMBL': 'Q6M8E6'}
{'taxon': '196627'}
{'GOA': 'Q6M8E5', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q6M8E5'}
{'taxon': '196627'}
{'GOA': 'Q8NTU3', 'InterPro': 'IPR003448', 'UniProtKB/TrEMBL': 'Q8NTU3'}
{'taxon': '196627'}
{'GOA': 'Q8NTU2', 'InterPro': 'IPR001453', 'UniProtKB/TrEMBL': 'Q8NTU2'}
{'taxon': '196627'}
{'GOA': 'Q8NTU1', 'InterPro': 'IPR023046'}
{'taxon': '196627'}
{'GOA': 'Q8NTU0', 'InterPro': 'IPR005111', 'UniProtKB/TrEMBL': 'Q8NTU0'}
{'taxon': '196627'}
{'GOA': 'Q6M8E1', 'InterPro': 'IPR000515', 'UniProtKB/TrEMBL': 'Q6M8E1'}
{'taxon': '196627'}
{'GOA': 'Q8NTT8', 'InterPro': 'IPR005950', 'UniProtKB/TrEMBL': 'Q8NTT8'}
{'taxon': '196627'}
{'InterPro': 'IPR016155', 'UniProtKB/TrEMBL': 'Q6M8D9'}
{'taxon': '196627'}
{'GOA': 'Q8NTT6', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NTT6'}
{'taxon': '196627'}
{'InterPro': 'IPR007165', 'UniProtKB/TrEMBL': 'Q8NTT5'}
{'taxon': '196627'}
{'GOA': 'Q8NTT4', 'InterPro': 'IPR024892'}
{'taxon': '196627'}
{'InterPro': 'IPR024524', 'UniProtKB/TrEMBL': 'Q8NTT3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8D5'}
{'taxon': '196627'}
{'GOA': 'Q8NTT1', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NTT1'}
{'taxon': '196627'}
{'GOA': 'Q8NTT0', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NTT0'}
{'taxon': '196627'}
{'GOA': 'Q8NTS9', 'InterPro': 'IPR003042', 'UniProtKB/TrEMBL': 'Q8NTS9'}
{'taxon': '196627'}
{'GOA': 'Q6M8D1', 'InterPro': 'IPR006669', 'UniProtKB/TrEMBL': 'Q6M8D1'}
{'taxon': '196627'}
{'GOA': 'Q6M8D0', 'InterPro': 'IPR001898', 'UniProtKB/TrEMBL': 'Q6M8D0'}
{'taxon': '196627'}
{'GOA': 'Q6M8C9', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q6M8C9'}
{'taxon': '196627'}
{'InterPro': 'IPR023869', 'UniProtKB/TrEMBL': 'Q6M8C8'}
{'taxon': '196627'}
{'GOA': 'Q6M8C7', 'InterPro': 'IPR028883', 'UniProtKB/TrEMBL': 'Q6M8C7'}
{'taxon': '196627'}
{'InterPro': 'IPR008462', 'UniProtKB/TrEMBL': 'Q8NTS3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M8C5'}
{'taxon': '196627'}
{'GOA': 'Q8NTS1', 'InterPro': 'IPR004869', 'UniProtKB/TrEMBL': 'Q8NTS1'}
{'taxon': '196627'}
{'GOA': 'Q8NTS0', 'InterPro': 'IPR004803', 'UniProtKB/TrEMBL': 'Q8NTS0'}
{'taxon': '196627'}
{'InterPro': 'IPR003744', 'UniProtKB/TrEMBL': 'Q6M8C2'}
{'taxon': '196627'}
{'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NTR8'}
{'taxon': '196627'}
{'GOA': 'Q8NTR7', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NTR7'}
{'taxon': '196627'}
{'GOA': 'Q8NTR6', 'InterPro': 'IPR022380'}
{'taxon': '196627'}
{'GOA': 'Q8NTR5', 'InterPro': 'IPR015889', 'UniProtKB/TrEMBL': 'Q8NTR5'}
{'taxon': '196627'}
{'GOA': 'Q6M8B7', 'InterPro': 'IPR012337', 'UniProtKB/TrEMBL': 'Q6M8B7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NTR3'}
{'taxon': '196627'}
{'GOA': 'Q6M8B5', 'InterPro': 'IPR024551', 'PDB': '3PPL', 'UniProtKB/TrEMBL': 'Q6M8B5'}
{'taxon': '196627'}
{'InterPro': 'IPR020941', 'UniProtKB/TrEMBL': 'Q8NTR1'}
{'taxon': '196627'}
{'GOA': 'Q8NTR0', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NTR0'}
{'taxon': '196627'}
{'GOA': 'Q8NTQ9', 'InterPro': 'IPR004401'}
{'taxon': '196627'}
{'GOA': 'Q8NTQ8', 'InterPro': 'IPR023628'}
{'taxon': '196627'}
{'GOA': 'Q8NTQ7', 'InterPro': 'IPR029062', 'UniProtKB/TrEMBL': 'Q8NTQ7'}
{'taxon': '196627'}
{'GOA': 'Q8NTQ6', 'InterPro': 'IPR013564', 'UniProtKB/TrEMBL': 'Q8NTQ6'}
{'taxon': '196627'}

{'taxon': '196627'}
{'InterPro': 'IPR029068', 'UniProtKB/TrEMBL': 'Q8NRH4'}
{'taxon': '196627'}
{'GOA': 'Q8NRH3', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NRH3'}
{'taxon': '196627'}
{'GOA': 'Q6M689', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q6M689'}
{'taxon': '196627'}
{'InterPro': 'IPR017195', 'UniProtKB/TrEMBL': 'Q6M688'}
{'taxon': '196627'}
{'GOA': 'Q8NRH0', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NRH0'}
{'taxon': '196627'}
{'InterPro': 'IPR003339', 'UniProtKB/TrEMBL': 'Q8NRG9'}
{'taxon': '196627'}
{'GOA': 'Q8NRG8', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NRG8'}
{'taxon': '196627'}
{'GOA': 'Q8NRG7', 'InterPro': 'IPR004837', 'UniProtKB/TrEMBL': 'Q8NRG7'}
{'taxon': '196627'}
{'InterPro': 'IPR024078', 'UniProtKB/TrEMBL': 'Q6M683'}
{'taxon': '196627'}
{'InterPro': 'IPR011737', 'UniProtKB/TrEMBL': 'Q8NRG5'}
{'taxon': '196627'}
{'GOA': 'Q8NRG4', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NRG4'}
{'taxon': '196627'}
{'GOA': 'Q8NRG3', 'InterPro': 'IPR018219'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRG2'}
{'taxon': '196627'}
{'InterPro': 'IPR008526', 'UniProtKB/TrEMBL': 'Q8NRG1'}
{'taxon': '196627'}
{'GOA': 'Q8NRG0', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NRG0'}
{'taxon': '196627'}
{'InterPro': 'IPR014543', 'UniProtKB/TrEMBL': 'Q8NRF9'}
{'taxon': '196627'}
{'GOA': 'Q6M676', 'InterPro': 'IPR015797', 'UniProtKB/TrEMBL': 'Q6M676'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M675'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRF7'}
{'taxon': '196627'}
{'GOA': 'Q8NRF6', 'InterPro': 'IPR009003'}
{'taxon': '196627'}
{'GOA': 'Q8NRF5', 'InterPro': 'IPR012336', 'UniProtKB/TrEMBL': 'Q8NRF5'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRF4'}
{'taxon': '196627'}
{'InterPro': 'IPR014465', 'UniProtKB/TrEMBL': 'Q8NRF3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRF2'}
{'taxon': '196627'}
{'GOA': 'Q6M668', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q6M668'}
{'taxon': '196627'}
{'GOA': 'Q6M667', 'InterPro': 'IPR000914', 'UniProtKB/TrEMBL': 'Q6M667'}
{'taxon': '196627'}
{'GOA': 'Q8NRE9', 'InterPro': 'IPR024078'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M665'}
{'taxon': '196627'}
{'GOA': 'Q8NRE7', 'InterPro': 'IPR017900', 'UniProtKB/TrEMBL': 'Q8NRE7'}
{'taxon': '196627'}
{'GOA': 'Q8NRE6', 'InterPro': 'IPR019880', 'UniProtKB/TrEMBL': 'Q8NRE6'}
{'taxon': '196627'}
{'GOA': 'Q8NRE5', 'InterPro': 'IPR007267', 'UniProtKB/TrEMBL': 'Q8NRE5'}
{'taxon': '196627'}
{'GOA': 'Q8NRE4', 'InterPro': 'IPR003615', 'UniProtKB/TrEMBL': 'Q8NRE4'}
{'taxon': '196627'}
{'GOA': 'Q8NRE3', 'InterPro': 'IPR026586'}
{'taxon': '196627'}
{'GOA': 'Q46065', 'InterPro': 'IPR004841'}
{'taxon': '196627'}
{'GOA': 'Q79VH2', 'InterPro': 'IPR011004', 'UniProtKB/TrEMBL': 'Q79VH2'}
{'taxon': '196627'}
{'GOA': 'Q59284', 'InterPro': 'IPR011650', 'PDB': '3TX8'}
{'taxon': '196627'}
{'InterPro': 'IPR005269', 'UniProtKB/TrEMBL': 'Q8NRE2'}
{'taxon': '196627'}
{'GOA': 'Q6M657', 'InterPro': 'IPR011005', 'UniProtKB/TrEMBL': 'Q6M657'}
{'taxon': '196627'}
{'GOA': 'Q6M656', 'InterPro': 'IPR029044', 'UniProtKB/TrEMBL': 'Q6M656'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRD9'}
{'taxon': '196627'}
{'InterPro': 'IPR021465', 'UniProtKB/TrEMBL': 'Q8NRD8'}
{'taxon': '196627'}
{'GOA': 'Q8NRD7', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q8NRD7'}
{'taxon': '196627'}
{'GOA': 'Q8NRD6', 'InterPro': 'IPR023296', 'UniProtKB/TrEMBL': 'Q8NRD6'}
{'taxon': '196627'}
{'GOA': 'Q6M651', 'InterPro': 'IPR028098', 'UniProtKB/TrEMBL': 'Q6M651'}
{'taxon': '196627'}
{'GOA': 'Q8NRD4', 'InterPro': 'IPR029044'}
{'taxon': '196627'}
{'GOA': 'Q8NRD3', 'InterPro': 'IPR029063', 'PDB': '3DR5', 'UniProtKB/TrEMBL': 'Q8NRD3'}
{'taxon': '196627'}
{'GOA': 'Q6M649', 'InterPro': 'IPR014284', 'UniProtKB/TrEMBL': 'Q6M649'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRD1'}
{'taxon': '196627'}
{'GOA': 'Q8NRD0', 'InterPro': 'IPR018448'}
{'taxon': '196627'}
{'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NRC9'}
{'taxon': '196627'}
{'InterPro': 'IPR010406', 'UniProtKB/TrEMBL': 'Q8NRC8'}
{'taxon': '196627'}
{'GOA': 'Q8NRC7', 'InterPro': 'IPR011033', 'UniProtKB/TrEMBL': 'Q8NRC7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M644'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRC5'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M642'}
{'taxon': '196627'}
{'GOA': 'Q8NRC3', 'InterPro': 'IPR029061'}
{'taxon': '196627'}
{'GOA': 'Q8NRC2', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NRC2'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRC1'}
{'taxon': '196627'}
{'GOA': 'Q8NRC0', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NRC0'}
{'taxon': '196627'}
{'GOA': 'Q6M637', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q6M637'}
{'taxon': '196627'}
{'GOA': 'Q8NRB8', 'InterPro': 'IPR024726', 'UniProtKB/TrEMBL': 'Q8NRB8'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M635'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M634'}
{'taxon': '196627'}
{'GOA': 'Q8NRB5', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NRB5'}
{'taxon': '196627'}
{'GOA': 'Q8NRB4', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NRB4'}
{'taxon': '196627'}
{'GOA': 'Q8NRB3', 'InterPro': 'IPR013215'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRB2'}
{'taxon': '196627'}
{'GOA': 'Q6M630', 'InterPro': 'IPR020946', 'UniProtKB/TrEMBL': 'Q6M630'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NRB0'}
{'taxon': '196627'}
{'GOA': 'Q6M628', 'InterPro': 'IPR016035', 'UniProtKB/TrEMBL': 'Q6M628'}
{'taxon': '196627'}
{'GOA': 'Q8NRA8', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q8NRA8'}
{'taxon': '196627'}
{'GOA': 'Q8NRA7', 'InterPro': 'IPR016181', 'UniProtKB/TrEMBL': 'Q8NRA7'}
{'taxon': '196627'}
{'GOA': 'Q8NRA5', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NRA5'}
{'taxon': '196627'}
{'GOA': 'Q8NRA4', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NRA4'}
{'taxon': '196627'}
{'GOA': 'Q8NRA3', 'InterPro': 'IPR003317', 'UniProtKB/TrEMBL': 'Q8NRA3'}
{'taxon': '196627'}
{'GOA': 'Q8NRA2', 'InterPro': 'IPR002585', 'UniProtKB/TrEMBL': 'Q8NRA2'}
{'taxon': '196627'}
{'GOA': 'Q6M621', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q6M621'}
{'taxon': '196627'}
{'GOA': 'Q8NR99', 'InterPro': 'IPR020476', 'UniProtKB/TrEMBL': 'Q8NR99'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR98'}
{'taxon': '196627'}
{'GOA': 'Q8NR97', 'InterPro': 'IPR004841', 'UniProtKB/TrEMBL': 'Q8NR97'}
{'taxon': '196627'}
{'GOA': 'Q6M617', 'InterPro': 'IPR028618', 'UniProtKB/TrEMBL': 'Q6M617'}
{'taxon': '196627'}
{'GOA': 'Q8NR95', 'InterPro': 'IPR015893', 'PDB': '3AQT', 'UniProtKB/TrEMBL': 'Q8NR95'}
{'taxon': '196627'}
{'GOA': 'Q8NR94', 'InterPro': 'IPR003042', 'UniProtKB/TrEMBL': 'Q8NR94'}
{'taxon': '196627'}
{'GOA': 'Q8NR93', 'InterPro': 'IPR001670', 'UniProtKB/TrEMBL': 'Q8NR93'}
{'taxon': '196627'}
{'GOA': 'Q8NR92', 'InterPro': 'IPR015889', 'UniProtKB/TrEMBL': 'Q8NR92'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR91'}
{'taxon': '196627'}
{'InterPro': 'IPR025978', 'UniProtKB/TrEMBL': 'Q8NR90'}
{'taxon': '196627'}
{'GOA': 'Q79VH1', 'InterPro': 'IPR019900', 'UniProtKB/TrEMBL': 'Q79VH1'}
{'taxon': '196627'}
{'GOA': 'Q8NR89', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NR89'}
{'taxon': '196627'}
{'GOA': 'Q6M608', 'InterPro': 'IPR007527', 'UniProtKB/TrEMBL': 'Q6M608'}
{'taxon': '196627'}
{'GOA': 'Q8NR87', 'InterPro': 'IPR029052', 'UniProtKB/TrEMBL': 'Q8NR87'}
{'taxon': '196627'}
{'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NR86'}
{'taxon': '196627'}
{'GOA': 'Q8NR85', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q8NR85'}
{'taxon': '196627'}
{'InterPro': 'IPR006160', 'UniProtKB/TrEMBL': 'Q8NR84'}
{'taxon': '196627'}
{'InterPro': 'IPR007372', 'UniProtKB/TrEMBL': 'Q8NR83'}
{'taxon': '196627'}
{'GOA': 'Q8NR82', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NR82'}
{'taxon': '196627'}
{'InterPro': 'IPR007168', 'UniProtKB/TrEMBL': 'Q6M601'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M600'}
{'taxon': '196627'}
{'GOA': 'Q8NR79', 'InterPro': 'IPR018490', 'UniProtKB/TrEMBL': 'Q8NR79'}
{'taxon': '196627'}
{'GOA': 'Q8NR78', 'InterPro': 'IPR017969', 'UniProtKB/TrEMBL': 'Q8NR78'}
{'taxon': '196627'}
{'GOA': 'Q8NR77', 'InterPro': 'IPR027256', 'UniProtKB/TrEMBL': 'Q8NR77'}
{'taxon': '196627'}
{'GOA': 'Q8NR76', 'InterPro': 'IPR007685', 'UniProtKB/TrEMBL': 'Q8NR76'}
{'taxon': '196627'}
{'GOA': 'Q8NR75', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q8NR75'}
{'taxon': '196627'}
{'GOA': 'P35868', 'InterPro': 'IPR014729'}
{'taxon': '196627'}
{'GOA': 'P09890', 'InterPro': 'IPR029066'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR74'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR73'}
{'taxon': '196627'}
{'GOA': 'P08499', 'InterPro': 'IPR019811'}
{'taxon': '196627'}
{'GOA': 'P07128', 'InterPro': 'IPR020568'}
{'taxon': '196627'}
{'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NR72'}
{'taxon': '196627'}
{'GOA': 'Q8NR71', 'InterPro': 'IPR023234', 'UniProtKB/TrEMBL': 'Q8NR71'}
{'taxon': '196627'}
{'GOA': 'Q6M5Z0', 'InterPro': 'IPR020945', 'UniProtKB/TrEMBL': 'Q6M5Z0'}
{'taxon': '196627'}
{'GOA': 'Q8NR69', 'InterPro': 'IPR029263', 'UniProtKB/TrEMBL': 'Q8NR69'}
{'taxon': '196627'}
{'GOA': 'Q8NR68', 'InterPro': 'IPR027467', 'UniProtKB/TrEMBL': 'Q8NR68'}
{'taxon': '196627'}
{'GOA': 'Q6M5Y7', 'InterPro': 'IPR016196', 'UniProtKB/TrEMBL': 'Q6M5Y7'}
{'taxon': '196627'}
{'GOA': 'Q6M5Y6', 'InterPro': 'IPR001453', 'UniProtKB/TrEMBL': 'Q6M5Y6'}
{'taxon': '196627'}
{'GOA': 'Q8NR65', 'InterPro': 'IPR013425', 'UniProtKB/TrEMBL': 'Q8NR65'}
{'taxon': '196627'}
{'GOA': 'Q8NR64', 'InterPro': 'IPR013785', 'UniProtKB/TrEMBL': 'Q8NR64'}
{'taxon': '196627'}
{'GOA': 'Q8NR63', 'InterPro': 'IPR016169', 'PDB': '2P3H', 'UniProtKB/TrEMBL': 'Q8NR63'}
{'taxon': '196627'}
{'InterPro': 'IPR029044', 'UniProtKB/TrEMBL': 'Q8NR62'}
{'taxon': '196627'}
{'GOA': 'Q6M5Y1', 'InterPro': 'IPR020817', 'UniProtKB/TrEMBL': 'Q6M5Y1'}
{'taxon': '196627'}
{'GOA': 'Q8NR60', 'InterPro': 'IPR013785'}
{'taxon': '196627'}
{'GOA': 'Q8NR59', 'InterPro': 'IPR025110', 'UniProtKB/TrEMBL': 'Q8NR59'}
{'taxon': '196627'}
{'GOA': 'Q8NR58', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NR58'}
{'taxon': '196627'}
{'GOA': 'Q8NR57', 'InterPro': 'IPR014720'}
{'taxon': '196627'}
{'GOA': 'P0DJB1', 'InterPro': 'IPR029063'}
{'taxon': '196627'}
{'GOA': 'Q8NR55', 'InterPro': 'IPR017945', 'UniProtKB/TrEMBL': 'Q8NR55'}
{'taxon': '196627'}
{'GOA': 'Q8NR54', 'InterPro': 'IPR000715', 'UniProtKB/TrEMBL': 'Q8NR54'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5X5'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'H7C7K1'}
{'taxon': '196627'}
{'GOA': 'H7C6C5', 'InterPro': 'IPR000568', 'UniProtKB/TrEMBL': 'H7C6C5'}
{'taxon': '196627'}
{'GOA': 'H7C6C1', 'InterPro': 'IPR020537', 'UniProtKB/TrEMBL': 'H7C6C1'}
{'taxon': '196627'}
{'GOA': 'Q79VG9', 'InterPro': 'IPR028987'}
{'taxon': '196627'}
{'GOA': 'Q7DIC8', 'InterPro': 'IPR020781'}
{'taxon': '196627'}
{'GOA': 'Q79VG7', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q79VG6', 'InterPro': 'IPR023633'}
{'taxon': '196627'}
{'GOA': 'P42464', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q9ETA7', 'InterPro': 'IPR020546'}
{'taxon': '196627'}
{'InterPro': 'IPR019675', 'UniProtKB/TrEMBL': 'Q8NR50'}
{'taxon': '196627'}
{'GOA': 'Q8NR49', 'InterPro': 'IPR011856'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR48'}
{'taxon': '196627'}
{'GOA': 'Q8NR47', 'InterPro': 'IPR029068', 'UniProtKB/TrEMBL': 'Q8NR47'}
{'taxon': '196627'}
{'InterPro': 'IPR029756', 'UniProtKB/TrEMBL': 'Q6M5W4'}
{'taxon': '196627'}
{'GOA': 'Q8NR45', 'InterPro': 'IPR013766', 'UniProtKB/TrEMBL': 'Q8NR45'}
{'taxon': '196627'}
{'GOA': 'Q8NR44', 'InterPro': 'IPR011251', 'UniProtKB/TrEMBL': 'Q8NR44'}
{'taxon': '196627'}
{'GOA': 'Q8NR43', 'InterPro': 'IPR000515', 'UniProtKB/TrEMBL': 'Q8NR43'}
{'taxon': '196627'}
{'GOA': 'Q8NR42', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q8NR41', 'InterPro': 'IPR015168', 'UniProtKB/TrEMBL': 'Q8NR41'}
{'taxon': '196627'}
{'GOA': 'Q8NR40', 'InterPro': 'IPR017853'}
{'taxon': '196627'}
{'GOA': 'Q8NR39', 'InterPro': 'IPR026585'}
{'taxon': '196627'}
{'GOA': 'Q8NR37', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NR37'}
{'taxon': '196627'}
{'GOA': 'Q6M5V6', 'InterPro': 'IPR015797', 'UniProtKB/TrEMBL': 'Q6M5V6'}
{'taxon': '196627'}
{'GOA': 'Q6M5V5', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q6M5V5'}
{'taxon': '196627'}
{'GOA': 'Q8NR34', 'InterPro': 'IPR014730', 'UniProtKB/TrEMBL': 'Q8NR34'}
{'taxon': '196627'}
{'GOA': 'Q8NR33', 'InterPro': 'IPR029035', 'UniProtKB/TrEMBL': 'Q8NR33'}
{'taxon': '196627'}
{'GOA': 'Q8NR32', 'InterPro': 'IPR016454', 'UniProtKB/TrEMBL': 'Q8NR32'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR31'}
{'taxon': '196627'}
{'InterPro': 'IPR017508', 'UniProtKB/TrEMBL': 'Q8NR30'}
{'taxon': '196627'}
{'GOA': 'Q8NR29', 'InterPro': 'IPR017507', 'UniProtKB/TrEMBL': 'Q8NR29'}
{'taxon': '196627'}
{'GOA': 'Q8NR28', 'InterPro': 'IPR016181', 'UniProtKB/TrEMBL': 'Q8NR28'}
{'taxon': '196627'}
{'InterPro': 'IPR029063', 'PDB': '3GJY', 'UniProtKB/TrEMBL': 'Q8NR27'}
{'taxon': '196627'}
{'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NR26'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR25'}
{'taxon': '196627'}
{'GOA': 'Q8NR24', 'InterPro': 'IPR023382'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR23'}
{'taxon': '196627'}
{'GOA': 'Q8NR22', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NR22'}
{'taxon': '196627'}
{'GOA': 'Q6M5U2', 'InterPro': 'IPR013520', 'UniProtKB/TrEMBL': 'Q6M5U2'}
{'taxon': '196627'}
{'GOA': 'Q8NR20', 'InterPro': 'IPR018239'}
{'taxon': '196627'}
{'GOA': 'Q8NR19', 'InterPro': 'IPR002912', 'UniProtKB/TrEMBL': 'Q8NR19'}
{'taxon': '196627'}
{'GOA': 'Q8NR18', 'InterPro': 'IPR003837'}
{'taxon': '196627'}
{'GOA': 'Q8NR17', 'InterPro': 'IPR023631'}
{'taxon': '196627'}
{'GOA': 'Q8NR16', 'InterPro': 'IPR017938', 'UniProtKB/TrEMBL': 'Q8NR16'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5T8'}
{'taxon': '196627'}
{'GOA': 'Q8NR14', 'InterPro': 'IPR022953'}
{'taxon': '196627'}
{'GOA': 'Q8NR13', 'InterPro': 'IPR028082', 'UniProtKB/TrEMBL': 'Q8NR13'}
{'taxon': '196627'}
{'GOA': 'Q8NR12', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q8NR11', 'InterPro': 'IPR001851', 'UniProtKB/TrEMBL': 'Q8NR11'}
{'taxon': '196627'}
{'InterPro': 'IPR028082', 'UniProtKB/TrEMBL': 'Q8NR10'}
{'taxon': '196627'}
{'GOA': 'Q8NR09', 'InterPro': 'IPR023750'}
{'taxon': '196627'}
{'GOA': 'Q8NR08', 'InterPro': 'IPR016181', 'UniProtKB/TrEMBL': 'Q8NR08'}
{'taxon': '196627'}
{'InterPro': 'IPR002491', 'UniProtKB/TrEMBL': 'Q8NR07'}
{'taxon': '196627'}
{'GOA': 'Q8NR06', 'InterPro': 'IPR002657', 'UniProtKB/TrEMBL': 'Q8NR06'}
{'taxon': '196627'}
{'GOA': 'Q8NR05', 'InterPro': 'IPR023168'}
{'taxon': '196627'}
{'InterPro': 'IPR028939', 'UniProtKB/TrEMBL': 'Q6M5S9'}
{'taxon': '196627'}
{'InterPro': 'IPR023210', 'UniProtKB/TrEMBL': 'Q6M5S8'}
{'taxon': '196627'}
{'GOA': 'P94633', 'InterPro': 'IPR004777'}
{'taxon': '196627'}
{'GOA': 'P94632', 'InterPro': 'IPR017685'}
{'taxon': '196627'}
{'GOA': 'Q8NR03', 'InterPro': 'IPR016639', 'PDB': '3M1G', 'UniProtKB/TrEMBL': 'Q8NR03'}
{'taxon': '196627'}
{'InterPro': 'IPR011089', 'UniProtKB/TrEMBL': 'Q8NR02'}
{'taxon': '196627'}
{'InterPro': 'IPR011637', 'UniProtKB/TrEMBL': 'Q8NR01'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NR00'}
{'taxon': '196627'}
{'GOA': 'Q8NQZ9', 'InterPro': 'IPR020558'}
{'taxon': '196627'}
{'InterPro': 'IPR020535', 'UniProtKB/TrEMBL': 'Q6M5S3'}
{'taxon': '196627'}
{'GOA': 'P42531', 'InterPro': 'IPR010920'}
{'taxon': '196627'}
{'GOA': 'P42463', 'InterPro': 'IPR029061'}
{'taxon': '196627'}
{'GOA': 'Q79VG4', 'InterPro': 'IPR019455', 'UniProtKB/TrEMBL': 'Q79VG4'}
{'taxon': '196627'}
{'GOA': 'Q57179', 'InterPro': 'IPR013328'}
{'taxon': '196627'}
{'GOA': 'Q8NQZ7', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQZ7'}
{'taxon': '196627'}
{'GOA': 'Q8NQZ5', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQZ5'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQZ4'}
{'taxon': '196627'}
{'GOA': 'Q6M5R8', 'InterPro': 'IPR009100', 'UniProtKB/TrEMBL': 'Q6M5R8'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQZ2'}
{'taxon': '196627'}
{'GOA': 'Q8NQZ1', 'InterPro': 'IPR012349', 'UniProtKB/TrEMBL': 'Q8NQZ1'}
{'taxon': '196627'}
{'GOA': 'Q6M5R5', 'InterPro': 'IPR027470', 'UniProtKB/TrEMBL': 'Q6M5R5'}
{'taxon': '196627'}
{'InterPro': 'IPR004919', 'UniProtKB/TrEMBL': 'Q8NQY9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5R3'}
{'taxon': '196627'}
{'GOA': 'Q8NQY7', 'InterPro': 'IPR029752', 'UniProtKB/TrEMBL': 'Q8NQY7'}
{'taxon': '196627'}
{'InterPro': 'IPR019660', 'UniProtKB/TrEMBL': 'Q8NQY6'}
{'taxon': '196627'}
{'GOA': 'P94631', 'InterPro': 'IPR024084'}
{'taxon': '196627'}
{'InterPro': 'IPR015168', 'UniProtKB/TrEMBL': 'Q8NQY5'}
{'taxon': '196627'}
{'GOA': 'Q8NQY4', 'InterPro': 'IPR018821', 'UniProtKB/TrEMBL': 'Q8NQY4'}
{'taxon': '196627'}
{'GOA': 'Q6M5Q8', 'InterPro': 'IPR013520', 'UniProtKB/TrEMBL': 'Q6M5Q8'}
{'taxon': '196627'}
{'GOA': 'Q8NQY2', 'InterPro': 'IPR018833', 'PDB': '4DBH', 'UniProtKB/TrEMBL': 'Q8NQY2'}
{'taxon': '196627'}
{'GOA': 'Q6M5Q6', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q6M5Q6'}
{'taxon': '196627'}
{'GOA': 'Q8NQY0', 'InterPro': 'IPR015890', 'UniProtKB/TrEMBL': 'Q8NQY0'}
{'taxon': '196627'}
{'GOA': 'Q8NQX9', 'InterPro': 'IPR020751'}
{'taxon': '196627'}
{'GOA': 'Q8NQX8', 'InterPro': 'IPR010982', 'UniProtKB/TrEMBL': 'Q8NQX8'}
{'taxon': '196627'}
{'InterPro': 'IPR021354', 'UniProtKB/TrEMBL': 'Q6M5Q3'}
{'taxon': '196627'}
{'InterPro': 'IPR023393', 'UniProtKB/TrEMBL': 'Q8NQX6'}
{'taxon': '196627'}
{'GOA': 'Q8NQX5', 'InterPro': 'IPR015893', 'UniProtKB/TrEMBL': 'Q8NQX5'}
{'taxon': '196627'}
{'InterPro': 'IPR023393', 'UniProtKB/TrEMBL': 'Q8NQX4'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQX3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5P8'}
{'taxon': '196627'}
{'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQW9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQW8'}
{'taxon': '196627'}
{'GOA': 'Q8NQW7', 'InterPro': 'IPR025747'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5P5'}
{'taxon': '196627'}
{'GOA': 'Q6M5P4', 'InterPro': 'IPR011833', 'UniProtKB/TrEMBL': 'Q6M5P4'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQW3'}
{'taxon': '196627'}
{'GOA': 'Q8NQW2', 'InterPro': 'IPR001763', 'UniProtKB/TrEMBL': 'Q8NQW2'}
{'taxon': '196627'}
{'GOA': 'Q8NQW1', 'InterPro': 'IPR002781', 'UniProtKB/TrEMBL': 'Q8NQW1'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQW0'}
{'taxon': '196627'}
{'GOA': 'Q8NQV9', 'InterPro': 'IPR006674', 'UniProtKB/TrEMBL': 'Q8NQV9'}
{'taxon': '196627'}
{'GOA': 'Q8NQV8', 'InterPro': 'IPR029016', 'UniProtKB/TrEMBL': 'Q8NQV8'}
{'taxon': '196627'}
{'GOA': 'P58946', 'InterPro': 'IPR018136'}
{'taxon': '196627'}
{'GOA': 'Q8NQV7', 'InterPro': 'IPR015937'}
{'taxon': '196627'}
{'GOA': 'Q6M5N7', 'InterPro': 'IPR029033', 'UniProtKB/TrEMBL': 'Q6M5N7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQV4'}
{'taxon': '196627'}
{'GOA': 'Q8NQV3', 'InterPro': 'IPR016040'}
{'taxon': '196627'}
{'GOA': 'Q8NQV2', 'InterPro': 'IPR016185'}
{'taxon': '196627'}
{'InterPro': 'IPR021903', 'UniProtKB/TrEMBL': 'Q6M5N5'}
{'taxon': '196627'}
{'GOA': 'Q8NQV0', 'InterPro': 'IPR016188'}
{'taxon': '196627'}
{'GOA': 'Q8NQU9', 'InterPro': 'IPR018085'}
{'taxon': '196627'}
{'GOA': 'Q6M5N3', 'InterPro': 'IPR019986', 'UniProtKB/TrEMBL': 'Q6M5N3'}
{'taxon': '196627'}
{'GOA': 'Q8NQU7', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQU7'}
{'taxon': '196627'}
{'GOA': 'Q79VG3', 'InterPro': 'IPR011053', 'UniProtKB/TrEMBL': 'Q79VG3'}
{'taxon': '196627'}
{'GOA': 'Q8NQU6', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q8NQU6'}
{'taxon': '196627'}
{'GOA': 'Q8NQU5', 'InterPro': 'IPR014729'}
{'taxon': '196627'}
{'GOA': 'Q8NQ10', 'InterPro': 'IPR029039', 'UniProtKB/TrEMBL': 'Q8NQ10'}
{'taxon': '196627'}
{'GOA': 'Q8NQ09', 'InterPro': 'IPR029009', 'UniProtKB/TrEMBL': 'Q8NQ09'}
{'taxon': '196627'}
{'GOA': 'Q6M4X2', 'InterPro': 'IPR006076', 'UniProtKB/TrEMBL': 'Q6M4X2'}
{'taxon': '196627'}
{'GOA': 'Q8NQ07', 'InterPro': 'IPR015807'}
{'taxon': '196627'}
{'GOA': 'Q8NQ06', 'InterPro': 'IPR001279', 'UniProtKB/TrEMBL': 'Q8NQ06'}
{'taxon': '196627'}
{'GOA': 'Q6M4X0', 'InterPro': 'IPR029000', 'UniProtKB/TrEMBL': 'Q6M4X0'}
{'taxon': '196627'}
{'GOA': 'Q8NQ03'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M4W8'}
{'taxon': '196627'}

{'taxon': '196627'}
{'GOA': 'Q6M2J6', 'InterPro': 'IPR006680', 'UniProtKB/TrEMBL': 'Q6M2J6'}
{'taxon': '196627'}
{'GOA': 'Q8NMD2', 'InterPro': 'IPR013785', 'UniProtKB/TrEMBL': 'Q8NMD2'}
{'taxon': '196627'}
{'GOA': 'Q8NMD1', 'InterPro': 'IPR000600', 'UniProtKB/TrEMBL': 'Q8NMD1'}
{'taxon': '196627'}
{'GOA': 'Q8NMD0', 'InterPro': 'IPR013785'}
{'taxon': '196627'}
{'InterPro': 'IPR011040', 'UniProtKB/TrEMBL': 'Q8NMC8'}
{'taxon': '196627'}
{'GOA': 'Q6M2J2', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q6M2J2'}
{'taxon': '196627'}
{'GOA': 'Q6M5M9', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q6M5M9'}
{'taxon': '196627'}
{'GOA': 'Q8NQU3', 'InterPro': 'IPR010065', 'UniProtKB/TrEMBL': 'Q8NQU3'}
{'taxon': '196627'}
{'GOA': 'Q6M5M7', 'InterPro': 'IPR001638', 'UniProtKB/TrEMBL': 'Q6M5M7'}
{'taxon': '196627'}
{'InterPro': 'IPR009677', 'UniProtKB/TrEMBL': 'Q8NQU1'}
{'taxon': '196627'}
{'InterPro': 'IPR007163', 'UniProtKB/TrEMBL': 'Q8NQU0'}
{'taxon': '196627'}
{'GOA': 'Q6M5M4', 'InterPro': 'IPR013762', 'UniProtKB/TrEMBL': 'Q6M5M4'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5M3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQT7'}
{'taxon': '196627'}
{'InterPro': 'IPR011235', 'UniProtKB/TrEMBL': 'Q8NQT6'}
{'taxon': '196627'}
{'InterPro': 'IPR025354', 'UniProtKB/TrEMBL': 'Q8NQT5'}
{'taxon': '196627'}
{'InterPro': 'IPR019270', 'UniProtKB/TrEMBL': 'Q8NQT4'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQT3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5L7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5L6'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQT1'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQT0'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5L3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5L2'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQS8'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQS7'}
{'taxon': '196627'}
{'GOA': 'Q8NQS6', 'InterPro': 'IPR009003', 'UniProtKB/TrEMBL': 'Q8NQS6'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQS5'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQS4'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQS3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQS2'}
{'taxon': '196627'}
{'GOA': 'Q6M5K4', 'InterPro': 'IPR029060', 'UniProtKB/TrEMBL': 'Q6M5K4'}
{'taxon': '196627'}
{'GOA': 'Q6M5K3', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q6M5K3'}
{'taxon': '196627'}
{'GOA': 'Q6M5K2', 'InterPro': 'IPR010982', 'UniProtKB/TrEMBL': 'Q6M5K2'}
{'taxon': '196627'}
{'GOA': 'Q8NQR8', 'InterPro': 'IPR023210', 'UniProtKB/TrEMBL': 'Q8NQR8'}
{'taxon': '196627'}
{'GOA': 'Q6M5K0', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q6M5K0'}
{'taxon': '196627'}
{'GOA': 'Q8NQR5', 'InterPro': 'IPR022967', 'UniProtKB/TrEMBL': 'Q8NQR5'}
{'taxon': '196627'}
{'GOA': 'Q46072', 'InterPro': 'IPR018113'}
{'taxon': '196627'}
{'GOA': 'P58897', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'InterPro': 'IPR029050', 'UniProtKB/TrEMBL': 'Q6M5J8'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5J7'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5J6'}
{'taxon': '196627'}
{'GOA': 'Q8NQR2', 'InterPro': 'IPR023186', 'UniProtKB/TrEMBL': 'Q8NQR2'}
{'taxon': '196627'}
{'GOA': 'Q8NQR1', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NQR1'}
{'taxon': '196627'}
{'GOA': 'Q8NQR0', 'InterPro': 'IPR029056', 'UniProtKB/TrEMBL': 'Q8NQR0'}
{'taxon': '196627'}
{'GOA': 'Q8NQQ9', 'InterPro': 'IPR028082', 'PDB': '3BIL', 'UniProtKB/TrEMBL': 'Q8NQQ9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5J1'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5J0'}
{'taxon': '196627'}
{'GOA': 'Q6M5I9', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q6M5I9'}
{'taxon': '196627'}
{'GOA': 'Q8NQQ6', 'InterPro': 'IPR014729', 'UniProtKB/TrEMBL': 'Q8NQQ6'}
{'taxon': '196627'}
{'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q8NQQ5'}
{'taxon': '196627'}
{'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NQQ4'}
{'taxon': '196627'}
{'GOA': 'Q6M5I5', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q6M5I5'}
{'taxon': '196627'}
{'InterPro': 'IPR011637', 'UniProtKB/TrEMBL': 'Q8NQQ2'}
{'taxon': '196627'}
{'GOA': 'Q8NQQ1', 'InterPro': 'IPR001279', 'UniProtKB/TrEMBL': 'Q8NQQ1'}
{'taxon': '196627'}
{'GOA': 'Q8NQQ0', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQQ0'}
{'taxon': '196627'}
{'InterPro': 'IPR019286', 'UniProtKB/TrEMBL': 'Q8NQP9'}
{'taxon': '196627'}
{'GOA': 'Q8NQP8', 'InterPro': 'IPR019815'}
{'taxon': '196627'}
{'GOA': 'Q8NQP7', 'InterPro': 'IPR021137'}
{'taxon': '196627'}
{'GOA': 'Q8NQP6', 'InterPro': 'IPR005813'}
{'taxon': '196627'}
{'InterPro': 'IPR027299', 'UniProtKB/TrEMBL': 'Q6M5I0'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5H9'}
{'taxon': '196627'}
{'GOA': 'Q6M5H8', 'InterPro': 'IPR000515', 'UniProtKB/TrEMBL': 'Q6M5H8'}
{'taxon': '196627'}
{'GOA': 'Q8NQP2', 'InterPro': 'IPR000515', 'UniProtKB/TrEMBL': 'Q8NQP2'}
{'taxon': '196627'}
{'InterPro': 'IPR019546', 'UniProtKB/TrEMBL': 'Q8NQP1'}
{'taxon': '196627'}
{'GOA': 'Q8NQP0', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQP0'}
{'taxon': '196627'}
{'GOA': 'Q6M5H4', 'InterPro': 'IPR017946', 'UniProtKB/TrEMBL': 'Q6M5H4'}
{'taxon': '196627'}
{'GOA': 'Q6M5H3', 'InterPro': 'IPR029064', 'UniProtKB/TrEMBL': 'Q6M5H3'}
{'taxon': '196627'}
{'GOA': 'Q8NQN7', 'InterPro': 'IPR022911'}
{'taxon': '196627'}
{'GOA': 'Q8NQN6', 'InterPro': 'IPR020825'}
{'taxon': '196627'}
{'GOA': 'Q8NQN5', 'InterPro': 'IPR013831', 'UniProtKB/TrEMBL': 'Q8NQN5'}
{'taxon': '196627'}
{'GOA': 'Q8NQN4', 'InterPro': 'IPR002656', 'UniProtKB/TrEMBL': 'Q8NQN4'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQN3'}
{'taxon': '196627'}
{'GOA': 'Q59279', 'InterPro': 'IPR023013'}
{'taxon': '196627'}
{'GOA': 'Q59280', 'InterPro': 'IPR016117'}
{'taxon': '196627'}
{'GOA': 'Q59281', 'InterPro': 'IPR004662'}
{'taxon': '196627'}
{'GOA': 'Q59282', 'InterPro': 'IPR015424'}
{'taxon': '196627'}
{'GOA': 'Q59283', 'InterPro': 'IPR024904'}
{'taxon': '196627'}
{'GOA': 'O85175', 'InterPro': 'IPR024946'}
{'taxon': '196627'}
{'GOA': 'O85176', 'InterPro': 'IPR024074'}
{'taxon': '196627'}
{'GOA': 'O88101', 'InterPro': 'IPR029419'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQN2'}
{'taxon': '196627'}
{'InterPro': 'IPR002035', 'UniProtKB/TrEMBL': 'Q8NQN1'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQN0'}
{'taxon': '196627'}
{'InterPro': 'IPR005651', 'PDB': '2JNY', 'UniProtKB/TrEMBL': 'Q8NQM9'}
{'taxon': '196627'}
{'GOA': 'Q8NQM8', 'InterPro': 'IPR024107'}
{'taxon': '196627'}
{'GOA': 'Q8NQM7', 'InterPro': 'IPR014729', 'UniProtKB/TrEMBL': 'Q8NQM7'}
{'taxon': '196627'}
{'InterPro': 'IPR011990', 'UniProtKB/TrEMBL': 'Q6M5G3'}
{'taxon': '196627'}
{'InterPro': 'IPR023215', 'UniProtKB/TrEMBL': 'Q8NQM4'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQM3'}
{'taxon': '196627'}
{'GOA': 'Q8NQM2', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q8NQM2'}
{'taxon': '196627'}
{'GOA': 'Q8NQM1', 'InterPro': 'IPR017438'}
{'taxon': '196627'}
{'GOA': 'Q8NQM0', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQM0'}
{'taxon': '196627'}
{'GOA': 'Q8NQL9', 'InterPro': 'IPR022215', 'UniProtKB/TrEMBL': 'Q8NQL9'}
{'taxon': '196627'}
{'InterPro': 'IPR021522', 'UniProtKB/TrEMBL': 'Q8NQL8'}
{'taxon': '196627'}
{'GOA': 'Q8NQL7', 'InterPro': 'IPR029062'}
{'taxon': '196627'}
{'GOA': 'Q6M5F6', 'InterPro': 'IPR015797', 'UniProtKB/TrEMBL': 'Q6M5F6'}
{'taxon': '196627'}
{'GOA': 'Q8NQL5', 'InterPro': 'IPR023109'}
{'taxon': '196627'}
{'GOA': 'Q8NQL4', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQL4'}
{'taxon': '196627'}
{'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q6M5F4'}
{'taxon': '196627'}
{'InterPro': 'IPR003768', 'UniProtKB/TrEMBL': 'Q8NQL2'}
{'taxon': '196627'}
{'GOA': 'Q8NQL1', 'InterPro': 'IPR016181', 'UniProtKB/TrEMBL': 'Q8NQL1'}
{'taxon': '196627'}
{'GOA': 'Q8NQL0', 'InterPro': 'IPR001763', 'UniProtKB/TrEMBL': 'Q8NQL0'}
{'taxon': '196627'}
{'GOA': 'Q6M5F0', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q6M5F0'}
{'taxon': '196627'}
{'GOA': 'Q6M5E9', 'InterPro': 'IPR020103', 'UniProtKB/TrEMBL': 'Q6M5E9'}
{'taxon': '196627'}
{'GOA': 'Q8NQK7', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q8NQK6', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'InterPro': 'IPR001646', 'UniProtKB/TrEMBL': 'Q8NQK5'}
{'taxon': '196627'}
{'InterPro': 'IPR029442', 'UniProtKB/TrEMBL': 'Q8NQK4'}
{'taxon': '196627'}
{'GOA': 'Q8NQK3', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q8NQK3'}
{'taxon': '196627'}
{'GOA': 'Q8NQK2', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQK2'}
{'taxon': '196627'}
{'GOA': 'Q8NQK1', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQK1'}
{'taxon': '196627'}
{'GOA': 'Q8NQK0', 'InterPro': 'IPR023498'}
{'taxon': '196627'}
{'GOA': 'Q8NQJ9', 'InterPro': 'IPR018422', 'UniProtKB/TrEMBL': 'Q8NQJ9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQJ7'}
{'taxon': '196627'}
{'InterPro': 'IPR023006'}
{'taxon': '196627'}
{'GOA': 'Q6M5E1', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q6M5E1'}
{'taxon': '196627'}
{'GOA': 'Q8NQJ4', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q8NQJ3', 'InterPro': 'IPR008984', 'PDB': '4QCJ'}
{'taxon': '196627'}
{'GOA': 'Q8NQJ2', 'InterPro': 'IPR009061', 'UniProtKB/TrEMBL': 'Q8NQJ2'}
{'taxon': '196627'}
{'GOA': 'Q8NQJ1', 'InterPro': 'IPR003729', 'UniProtKB/TrEMBL': 'Q8NQJ1'}
{'taxon': '196627'}
{'GOA': 'Q8NQJ0', 'InterPro': 'IPR009061', 'UniProtKB/TrEMBL': 'Q8NQJ0'}
{'taxon': '196627'}
{'InterPro': 'IPR012551', 'UniProtKB/TrEMBL': 'Q8NQI9'}
{'taxon': '196627'}
{'InterPro': 'IPR002035', 'UniProtKB/TrEMBL': 'Q8NQI8'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5D3'}
{'taxon': '196627'}
{'GOA': 'Q8NQI6', 'InterPro': 'IPR002550', 'UniProtKB/TrEMBL': 'Q8NQI6'}
{'taxon': '196627'}
{'GOA': 'Q8NQI5', 'InterPro': 'IPR016169', 'UniProtKB/TrEMBL': 'Q8NQI5'}
{'taxon': '196627'}
{'GOA': 'Q8NQI4', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQI4'}
{'taxon': '196627'}
{'GOA': 'Q8NQI3', 'InterPro': 'IPR017938', 'UniProtKB/TrEMBL': 'Q8NQI3'}
{'taxon': '196627'}
{'GOA': 'Q8NQI2', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q8NQI2'}
{'taxon': '196627'}
{'InterPro': 'IPR029069', 'UniProtKB/TrEMBL': 'Q8NQI1'}
{'taxon': '196627'}
{'GOA': 'Q6M5C6', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q6M5C6'}
{'taxon': '196627'}
{'GOA': 'Q8NQH9', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQH9'}
{'taxon': '196627'}
{'GOA': 'Q8NQH8', 'InterPro': 'IPR013525', 'UniProtKB/TrEMBL': 'Q8NQH8'}
{'taxon': '196627'}
{'GOA': 'Q6M5C3', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q6M5C3'}
{'taxon': '196627'}
{'GOA': 'Q8NQH6', 'InterPro': 'IPR005769', 'UniProtKB/TrEMBL': 'Q8NQH6'}
{'taxon': '196627'}
{'GOA': 'Q8NQH5', 'InterPro': 'IPR005769', 'UniProtKB/TrEMBL': 'Q8NQH5'}
{'taxon': '196627'}
{'GOA': 'Q8NQH4', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q8NQH3', 'InterPro': 'IPR005770', 'UniProtKB/TrEMBL': 'Q8NQH3'}
{'taxon': '196627'}
{'InterPro': 'IPR023214', 'UniProtKB/TrEMBL': 'Q8NQH2'}
{'taxon': '196627'}
{'GOA': 'Q8NQH1', 'InterPro': 'IPR029056'}
{'taxon': '196627'}
{'GOA': 'Q8NQH0', 'InterPro': 'IPR029056'}
{'taxon': '196627'}
{'GOA': 'Q79VG1', 'InterPro': 'IPR023753', 'UniProtKB/TrEMBL': 'Q79VG1'}
{'taxon': '196627'}
{'GOA': 'Q8NQG9', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q8NQG9'}
{'taxon': '196627'}
{'GOA': 'Q8NQG8', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NQG8'}
{'taxon': '196627'}
{'GOA': 'Q8NQG7', 'InterPro': 'IPR029057', 'UniProtKB/TrEMBL': 'Q8NQG7'}
{'taxon': '196627'}
{'GOA': 'Q8NQG6', 'InterPro': 'IPR022929'}
{'taxon': '196627'}
{'InterPro': 'IPR016833', 'UniProtKB/TrEMBL': 'Q8NQG5'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQG4'}
{'taxon': '196627'}
{'InterPro': 'IPR016024', 'UniProtKB/TrEMBL': 'Q8NQG3'}
{'taxon': '196627'}
{'GOA': 'Q6M5A9', 'InterPro': 'IPR011547', 'UniProtKB/TrEMBL': 'Q6M5A9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQG1'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQG0'}
{'taxon': '196627'}
{'InterPro': 'IPR007372', 'UniProtKB/TrEMBL': 'Q6M5A6'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M5A5'}
{'taxon': '196627'}
{'GOA': 'Q8NQF8', 'InterPro': 'IPR025182', 'UniProtKB/TrEMBL': 'Q8NQF8'}
{'taxon': '196627'}
{'GOA': 'Q8NQF7', 'InterPro': 'IPR029044', 'UniProtKB/TrEMBL': 'Q8NQF7'}
{'taxon': '196627'}
{'GOA': 'Q8NQF6', 'InterPro': 'IPR004563', 'UniProtKB/TrEMBL': 'Q8NQF6'}
{'taxon': '196627'}
{'GOA': 'Q6M5A1', 'InterPro': 'IPR007313', 'UniProtKB/TrEMBL': 'Q6M5A1'}
{'taxon': '196627'}
{'GOA': 'Q6M5A0', 'InterPro': 'IPR029058', 'UniProtKB/TrEMBL': 'Q6M5A0'}
{'taxon': '196627'}
{'GOA': 'Q8NQF3', 'InterPro': 'IPR005117', 'UniProtKB/TrEMBL': 'Q8NQF3'}
{'taxon': '196627'}
{'GOA': 'Q6M598', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q6M598'}
{'taxon': '196627'}
{'GOA': 'Q8NQE9', 'InterPro': 'IPR020904', 'UniProtKB/TrEMBL': 'Q8NQE9'}
{'taxon': '196627'}
{'GOA': 'Q8NQE8', 'InterPro': 'IPR029149', 'UniProtKB/TrEMBL': 'Q8NQE8'}
{'taxon': '196627'}
{'GOA': 'Q8NQE7', 'InterPro': 'IPR009003', 'UniProtKB/TrEMBL': 'Q8NQE7'}
{'taxon': '196627'}
{'GOA': 'Q8NQE6', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQE6'}
{'taxon': '196627'}
{'GOA': 'Q6M593', 'InterPro': 'IPR019820', 'UniProtKB/TrEMBL': 'Q6M593'}
{'taxon': '196627'}
{'GOA': 'Q8NQE4', 'InterPro': 'IPR006312'}
{'taxon': '196627'}
{'InterPro': 'IPR028349', 'UniProtKB/TrEMBL': 'Q8NQE3'}
{'taxon': '196627'}
{'InterPro': 'IPR028349', 'UniProtKB/TrEMBL': 'Q6M591'}
{'taxon': '196627'}
{'GOA': 'Q8NQE1', 'InterPro': 'IPR022279', 'PDB': '4BJR'}
{'taxon': '196627'}
{'GOA': 'Q8NQE0', 'InterPro': 'IPR008515', 'PDB': '4BJR'}
{'taxon': '196627'}
{'GOA': 'Q8NQD9', 'InterPro': 'IPR022366', 'UniProtKB/TrEMBL': 'Q8NQD9'}
{'taxon': '196627'}
{'GOA': 'Q8NQD8', 'InterPro': 'IPR027417'}
{'taxon': '196627'}
{'GOA': 'Q8NQD7', 'InterPro': 'IPR029063', 'UniProtKB/TrEMBL': 'Q8NQD7'}
{'taxon': '196627'}
{'GOA': 'Q6M585', 'InterPro': 'IPR023358', 'UniProtKB/TrEMBL': 'Q6M585'}
{'taxon': '196627'}
{'GOA': 'Q8NQD5', 'InterPro': 'IPR011335', 'UniProtKB/TrEMBL': 'Q8NQD5'}
{'taxon': '196627'}
{'GOA': 'Q6M583', 'InterPro': 'IPR013430', 'UniProtKB/TrEMBL': 'Q6M583'}
{'taxon': '196627'}
{'GOA': 'Q8NQD3', 'InterPro': 'IPR020846', 'UniProtKB/TrEMBL': 'Q8NQD3'}
{'taxon': '196627'}
{'GOA': 'Q59200', 'InterPro': 'IPR024083'}
{'taxon': '196627'}
{'GOA': 'Q9Z472', 'InterPro': 'IPR020621'}
{'taxon': '196627'}
{'GOA': 'Q9Z471', 'InterPro': 'IPR021130'}
{'taxon': '196627'}
{'GOA': 'Q8NQD2', 'InterPro': 'IPR023214', 'UniProtKB/TrEMBL': 'Q8NQD2'}
{'taxon': '196627'}
{'GOA': 'Q6M580', 'InterPro': 'IPR011822', 'UniProtKB/TrEMBL': 'Q6M580'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQD0'}
{'taxon': '196627'}
{'GOA': 'Q8NQC9', 'InterPro': 'IPR013027', 'UniProtKB/TrEMBL': 'Q8NQC9'}
{'taxon': '196627'}
{'GOA': 'Q6M577', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q6M577'}
{'taxon': '196627'}
{'GOA': 'Q8NQC8', 'InterPro': 'IPR004706'}
{'taxon': '196627'}
{'GOA': 'P0DKS5', 'InterPro': 'IPR023485'}
{'taxon': '196627'}
{'GOA': 'Q8NQC6', 'InterPro': 'IPR023485', 'PDB': '3T38', 'UniProtKB/TrEMBL': 'Q8NQC6'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQC5'}
{'taxon': '196627'}
{'GOA': 'Q8NQC4', 'InterPro': 'IPR024909'}
{'taxon': '196627'}
{'GOA': 'Q8NQC3', 'InterPro': 'IPR003824'}
{'taxon': '196627'}
{'InterPro': 'IPR023210', 'UniProtKB/TrEMBL': 'Q6M571'}
{'taxon': '196627'}
{'InterPro': 'IPR011042', 'UniProtKB/TrEMBL': 'Q6M570'}
{'taxon': '196627'}
{'GOA': 'Q8NQC0', 'InterPro': 'IPR013785'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQB9'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQB8'}
{'taxon': '196627'}
{'GOA': 'Q6M567', 'InterPro': 'IPR012337', 'UniProtKB/TrEMBL': 'Q6M567'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M566'}
{'taxon': '196627'}
{'InterPro': 'IPR008914', 'UniProtKB/TrEMBL': 'Q8NQB5'}
{'taxon': '196627'}
{'GOA': 'Q8NQB4', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQB4'}
{'taxon': '196627'}
{'GOA': 'Q8NQB3', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQB3'}
{'taxon': '196627'}
{'GOA': 'Q8NQB1', 'InterPro': 'IPR016181', 'PDB': '2QEC', 'UniProtKB/TrEMBL': 'Q8NQB1'}
{'taxon': '196627'}
{'GOA': 'Q8NQB0', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQB0'}
{'taxon': '196627'}
{'GOA': 'Q8NQA9', 'InterPro': 'IPR016176', 'UniProtKB/TrEMBL': 'Q8NQA9'}
{'taxon': '196627'}
{'GOA': 'Q8NQA8', 'InterPro': 'IPR016176', 'UniProtKB/TrEMBL': 'Q8NQA8'}
{'taxon': '196627'}
{'InterPro': 'IPR015414', 'UniProtKB/TrEMBL': 'Q6M558'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQA6'}
{'taxon': '196627'}
{'GOA': 'Q8NQA5', 'InterPro': 'IPR018080', 'UniProtKB/TrEMBL': 'Q8NQA5'}
{'taxon': '196627'}
{'GOA': 'Q6M555', 'InterPro': 'IPR012340', 'UniProtKB/TrEMBL': 'Q6M555'}
{'taxon': '196627'}
{'InterPro': 'IPR021447', 'UniProtKB/TrEMBL': 'Q8NQA3'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQA2'}
{'taxon': '196627'}
{'GOA': 'Q8NQA1', 'InterPro': 'IPR001015'}
{'taxon': '196627'}
{'GOA': 'Q6M552', 'InterPro': 'IPR000064', 'UniProtKB/TrEMBL': 'Q6M552'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQ99'}
{'taxon': '196627'}
{'GOA': 'Q8NQ98', 'InterPro': 'IPR018136'}
{'taxon': '196627'}
{'GOA': 'Q8NQ97', 'InterPro': 'IPR015893', 'PDB': '4AF5'}
{'taxon': '196627'}
{'GOA': 'Q8NQ96', 'InterPro': 'IPR029062', 'UniProtKB/TrEMBL': 'Q8NQ96'}
{'taxon': '196627'}
{'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q6M547'}
{'taxon': '196627'}
{'InterPro': 'IPR027379', 'UniProtKB/TrEMBL': 'Q6M546'}
{'taxon': '196627'}
{'GOA': 'Q8NQ94', 'InterPro': 'IPR022986'}
{'taxon': '196627'}
{'InterPro': 'IPR007841'}
{'taxon': '196627'}
{'GOA': 'Q8NQ92', 'InterPro': 'IPR023299', 'UniProtKB/TrEMBL': 'Q8NQ92'}
{'taxon': '196627'}
{'InterPro': 'IPR018960', 'UniProtKB/TrEMBL': 'Q6M544'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQ90'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQ88'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQ87'}
{'taxon': '196627'}
{'InterPro': 'IPR011434', 'UniProtKB/TrEMBL': 'Q6M540'}
{'taxon': '196627'}
{'GOA': 'Q8NQ85', 'InterPro': 'IPR013762', 'UniProtKB/TrEMBL': 'Q8NQ85'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q6M538'}
{'taxon': '196627'}
{'GOA': 'Q8NQ84', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQ84'}
{'taxon': '196627'}
{'InterPro': 'IPR018905', 'UniProtKB/TrEMBL': 'Q8NQ83'}
{'taxon': '196627'}
{'GOA': 'Q6M535', 'InterPro': 'IPR026856', 'UniProtKB/TrEMBL': 'Q6M535'}
{'taxon': '196627'}
{'GOA': 'Q8NL43', 'InterPro': 'IPR001584', 'UniProtKB/TrEMBL': 'Q8NL43'}
{'taxon': '196627'}
{'UniProtKB/TrEMBL': 'Q8NQ81'}
{'taxon': '196627'}
{'InterPro': 'IPR002744', 'UniProtKB/TrEMBL': 'Q3V7Q5'}
{'taxon': '196627'}
{'GOA': 'Q8NQ79', 'InterPro': 'IPR002871', 'UniProtKB/TrEMBL': 'Q8NQ79'}
{'taxon': '196627'}
{'GOA': 'Q8NQ78', 'InterPro': 'IPR015424', 'UniProtKB/TrEMBL': 'Q8NQ78'}
{'taxon': '196627'}
{'GOA': 'Q8NQ77', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQ77'}
{'taxon': '196627'}
{'GOA': 'Q8NQ76', 'InterPro': 'IPR011542', 'UniProtKB/TrEMBL': 'Q8NQ76'}
{'taxon': '196627'}
{'GOA': 'Q8NQ75', 'InterPro': 'IPR010231', 'UniProtKB/TrEMBL': 'Q8NQ75'}
{'taxon': '196627'}
{'GOA': 'Q6M527', 'InterPro': 'IPR011991', 'UniProtKB/TrEMBL': 'Q6M527'}
{'taxon': '196627'}
{'GOA': 'Q8NQ73'}
{'taxon': '196627'}
{'GOA': 'Q8NQ72', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q8NQ72'}
{'taxon': '196627'}
{'GOA': 'Q8NQ71', 'InterPro': 'IPR000412', 'UniProtKB/TrEMBL': 'Q8NQ71'}
{'taxon': '196627'}
{'GOA': 'Q6M523', 'InterPro': 'IPR003780', 'UniProtKB/TrEMBL': 'Q6M523'}
{'taxon': '196627'}
{'GOA': 'Q6M522', 'InterPro': 'IPR027417', 'UniProtKB/TrEMBL': 'Q6M522'}
{'taxon': '196627'}
{'GOA': 'Q6M521', 'InterPro': 'IPR016040', 'UniProtKB/TrEMBL': 'Q6M521'}
{'taxon': '196627'}
{'GOA': 'Q8NQ66', 'InterPro': 'IPR006369'}
{'taxon': '196627'}
{'GOA': 'Q6M519', 'InterPro': 'IPR029061', 'UniProtKB/TrEMBL': 'Q6M519'}
{'taxon': '196627'}
{'GOA': 'Q8NQ64', 'InterPro': 'IPR018225', 'PDB': '3R5E', 'UniProtKB/TrEMBL': 'Q8NQ64'}
{'taxon': '196627'}
{'GOA': 'Q6M517', 'InterPro': 'IPR022675', 'UniProtKB/TrEMBL': 'Q6M517'}
{'taxon': '196627'}
{'InterPro': 'IPR004555', 'UniProtKB/TrEMBL': 'Q8NQ62'}
{'taxon': '196627'}
{'GOA': 'Q8NQ61', 'InterPro': 'IPR006148', 'UniProtKB/TrEMBL': 'Q8NQ61'}
{'taxon': '196627'}
{'GOA': 'Q8NQ60', 'InterPro': 'IPR006076', 'UniProtKB/TrEMBL': 'Q8NQ60'}
{'taxon': '196627'}
{'GOA': 'Q79VF9', 'InterPro': 'IPR002559', 'UniProtKB/TrEMBL': 'Q79VF9'}
{'taxon': '196627'}

In [6]:
gene_mapper = {}

for gene in model.genes:
    if 'kegg.genes' in gene.annotation:
        gene_mapper[gene.id] = gene.annotation['kegg.genes'][4:]

In [7]:
#replace the ncbi gene names in the GPR relation
def replace_ids(gpr, mapper):
    if pd.isna(gpr):  # Handle missing values
        return gpr
    for old_id, new_id in mapper.items():
        gpr = gpr.replace(old_id, new_id)
    return gpr

id_mapper_icg_gpr = id_mapper_icg.copy()
# Apply the replacement function to the GPR column
id_mapper_icg_gpr["GPR"] = id_mapper_icg_gpr["GPR"].apply(lambda x: replace_ids(x, gene_mapper))
id_mapper_icg_gpr

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR
0,2AGPEAT160,NaN,NaN,MNXR94760,[],[],2.3.1.40,
1,2AGPEAT180,NaN,NaN,MNXR94762,[],[],2.3.1.40,
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...
3,3HAD140,R04568,NaN,MNXR94879,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[4.2.1.61, 2.3.1.86, 2.3.1.-, 2.3.1.85, 4.2.1.59]",
4,3MBt2pp,NaN,NaN,MNXR94916,"[C00080, C08262]","[C08262, C00080]",NaN,cg0953
...,...,...,...,...,...,...,...,...
1142,Ca2t2,NaN,NaN,NaN,"[C00076, C00080]","[C00076, C00080]",NaN,WP_011014107_1
1143,CAT,R00009,"[20309, 20310, 20311, 20312]",MNXR96455,"[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[1.11.1.21, 1.11.1.6]",WP_011013509_1
1144,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1
1145,PRFGS_1,NaN,"[17129, 17131, 17130, 17132]",MNXR138721,"[[C00002, C00002;D08646], C04376, [C00064, C00...","[[C00008, C00008;G11113], C04640, [C00025, C00...",6.3.5.3,cg2865
1146,PYRt,NaN,NaN,MNXR103384,[C00022],[C00022],NaN,WP_011014733_1

## 2. Get all the protein information

Besides information about the reactions, we need the relation to the proteins in order to establish a protein allocation model. We do this using the gene-protein-reaction association obtained from the BIGG model. The genes is the model can be mapped to the Uniprot accessions, which can be mapped to the KEGG reactions using the Rhea database.

### 2.1 Parse the BIGG gene-protein-reaction associations

In [8]:
#You need to adjust this to find the geneid/locustag for your microbe
#locustag_regex =r'\b([b|s]\d{4})\b'
def extract_b_numbers(text):
    if pd.isna(text):
        return text
    return re.findall(locustag_regex, text)
id_mapper_df = id_mapper_icg_gpr.copy()

id_mapper_df['b_number'] = id_mapper_df['GPR'].apply(extract_b_numbers)
id_mapper_df = id_mapper_df.explode('b_number', ignore_index=True)
id_mapper_df = id_mapper_df.explode('EC', ignore_index=True)
id_mapper_df

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number
0,2AGPEAT160,NaN,NaN,MNXR94760,[],[],2.3.1.40,,NaN
1,2AGPEAT180,NaN,NaN,MNXR94762,[],[],2.3.1.40,,NaN
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949
3,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,cg3199
4,3HAD140,R04568,NaN,MNXR94879,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...",4.2.1.61,,NaN
...,...,...,...,...,...,...,...,...,...
2449,CAT,R00009,"[20309, 20310, 20311, 20312]",MNXR96455,"[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...",1.11.1.6,WP_011013509_1,WP_011013509_1
2450,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013606_1
2451,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013607_1
2452,PRFGS_1,NaN,"[17129, 17131, 17130, 17132]",MNXR138721,"[[C00002, C00002;D08646], C04376, [C00064, C00...","[[C00008, C00008;G11113], C04640, [C00025, C00...",6.3.5.3,cg2865,cg2865
2453,PYRt,NaN,NaN,MNXR103384,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1

### 2.2 Parse the Uniprot data for merging

In [9]:
def extract_kegg_gene_ids(text):
    if pd.isna(text):
        return text
    return re.findall(r'Cgl\d{4}', text)

# load the uniprot information
uniprot_df = pd.read_excel(UNIPROT_FILE_PATH)
#get the gene id from the gene names
uniprot_df['b_number'] = uniprot_df['Gene Names'].apply(extract_b_numbers)
# uniprot_df['kegg_gene'] = uniprot_df['Gene Names'].apply(extract_kegg_gene_ids)
uniprot_df = uniprot_df.explode('b_number', ignore_index=True)
# uniprot_df = uniprot_df.explode('kegg_gene', ignore_index=True)

uniprot_df = uniprot_df.drop(['Gene Names'], axis=1)
uniprot_df_genemapper = uniprot_df.dropna(subset='b_number')[['Entry', 'b_number', 'Mass', 'Length']]
uniprot_df_ecmapper = uniprot_df.dropna(subset='EC number')[['Entry', 'EC number', 'Mass', 'Length', 'b_number']]

### 2.3 Match Uniprot to BIGG data

In [10]:
# Merge first on b_number
id_mapper_with_protein = pd.merge(
    id_mapper_df, 
    uniprot_df_genemapper, 
    on='b_number', 
    how='left'
)

# Merge on EC number for rows where b_number-based merge failed
fallback_merge = pd.merge(
    id_mapper_df, 
    uniprot_df_ecmapper, 
    left_on='EC', 
    right_on='EC number', 
    how='left'
)

# Combine the two merges: prefer the first merge, fill missing values from the second
id_mapper_with_protein['Entry'] = id_mapper_with_protein['Entry'].fillna(fallback_merge['Entry'])
id_mapper_with_protein

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number,Entry,Mass,Length
0,2AGPEAT160,NaN,NaN,MNXR94760,[],[],2.3.1.40,,NaN,NaN,NaN,NaN
1,2AGPEAT180,NaN,NaN,MNXR94762,[],[],2.3.1.40,,NaN,NaN,NaN,NaN
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,NaN,NaN,NaN
3,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,cg3199,NaN,NaN,NaN
4,3HAD140,R04568,NaN,MNXR94879,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...",4.2.1.61,,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2450,CAT,R00009,"[20309, 20310, 20311, 20312]",MNXR96455,"[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...",1.11.1.6,WP_011013509_1,WP_011013509_1,Q8NLR8,NaN,NaN
2451,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013606_1,NaN,NaN,NaN
2452,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013607_1,NaN,NaN,NaN
2453,PRFGS_1,NaN,"[17129, 17131, 17130, 17132]",MNXR138721,"[[C00002, C00002;D08646], C04376, [C00064, C00...","[[C00008, C00008;G11113], C04640, [C00025, C00...",6.3.5.3,cg2865,cg2865,Q8NQV9,NaN,NaN
2454,PYRt,NaN,NaN,MNXR103384,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,NaN,NaN,NaN

## 3. Match the BiGG model reaction and enzymes to the kcats from GotEnzymes
Find first all enzymes for a reaction, then for each enzyme determine if the kcats from GotEnzymes are for a forward or reverse reaction

In [11]:
id_mapper_final = id_mapper_with_protein
id_mapper_final = id_mapper_final.rename({'Entry':'enzyme_id'}, axis=1)
id_mapper_final = id_mapper_final.explode('kegg_id', ignore_index=True)

# id_mapper_final = id_mapper_final.drop_duplicates(subset = ['kegg_id'])
id_mapper_final.head()

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number,enzyme_id,Mass,Length
0,2AGPEAT160,NaN,NaN,MNXR94760,[],[],2.3.1.40,,NaN,NaN,NaN,NaN
1,2AGPEAT180,NaN,NaN,MNXR94762,[],[],2.3.1.40,,NaN,NaN,NaN,NaN
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,NaN,NaN,NaN
3,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,cg3199,NaN,NaN,NaN
4,3HAD140,R04568,NaN,MNXR94879,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...",4.2.1.61,,NaN,NaN,NaN,NaN

In [12]:
#get the json file from GotEnzymes and parse into workable format
#read in the json file obtained from gotEnzymes (for 'eco')
eco_enzymes_json = pd.read_json(GOTENZYMES_FILE_PATH)
#convert to a readible format
eco_enzymes = eco_enzymes_json.enzymes.to_list()
eco_enzymes_df = pd.DataFrame(eco_enzymes)

#ensure there is only one ec number per row
eco_enzymes_df['ec_number'] = eco_enzymes_df['ec_number'].str.split(pat=';')
eco_enzymes_df = eco_enzymes_df.explode('ec_number', ignore_index=True)
eco_enzymes_df = eco_enzymes_df.dropna(axis=0, subset=['ec_number'])
eco_enzymes_df = eco_enzymes_df.drop(['organism', 'domain'], axis = 1)
eco_enzymes_df.head()

      gene reaction_id ec_number compound  kcat_values
0  Cgl0023      R01664   3.1.3.5   C00239       5.4287
1  Cgl0023      R01664  3.1.3.89   C00239       5.4287
2  Cgl0023      R01664   3.1.3.-   C00239       5.4287
3  Cgl0023      R00511   3.1.3.5   C00475       5.9248
4  Cgl0023      R00511  3.1.3.91   C00475       5.9248

In [21]:
# match BiGG and GotEnzymes based on gene id
eco_enzymes_merged = id_mapper_final.merge(eco_enzymes_df, 
                              left_on =['b_number', 'kegg_id'], 
                              right_on = ['gene', 'reaction_id'],
                             how = 'left').drop(['gene', 'reaction_id'], axis=1).rename({'b_number':'gene'}, axis=1)
eco_enzymes_merged

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,Mass,Length,ec_number,compound,kcat_values
0,2AGPEAT160,NaN,NaN,MNXR94760,[],[],2.3.1.40,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2AGPEAT180,NaN,NaN,MNXR94762,[],[],2.3.1.40,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,NaN,NaN,NaN,NaN,NaN,NaN
3,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,cg3199,NaN,NaN,NaN,NaN,NaN,NaN
4,3HAD140,R04568,NaN,MNXR94879,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...",4.2.1.61,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2480,CAT,R00009,"[20309, 20310, 20311, 20312]",MNXR96455,"[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...",1.11.1.6,WP_011013509_1,WP_011013509_1,Q8NLR8,NaN,NaN,NaN,NaN,NaN
2481,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013606_1,NaN,NaN,NaN,NaN,NaN,NaN
2482,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013607_1,NaN,NaN,NaN,NaN,NaN,NaN
2483,PRFGS_1,NaN,"[17129, 17131, 17130, 17132]",MNXR138721,"[[C00002, C00002;D08646], C04376, [C00064, C00...","[[C00008, C00008;G11113], C04640, [C00025, C00...",6.3.5.3,cg2865,cg2865,Q8NQV9,NaN,NaN,NaN,NaN,NaN
2484,PYRt,NaN,NaN,MNXR103384,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,NaN,NaN,NaN,NaN,NaN,NaN

### 6. Extract directionalities and gapfill
Reactions which are associated with an enzyme, but not with a kcat from GotEnzymes will be assignes
a default kcat and if required a default molmass.

In [22]:
# Get directionalities and fill in the gaps
eco_enzymes_merged['direction'] = 'f'
                                              
for index, row in eco_enzymes_merged.iterrows():
    #there is a kegg id and kcat associated to this reaction
    if not isinstance(row.kcat_values, float):
        if row.compound in row.Products:
            eco_enzymes_merged.direction.iloc[index] = 'b'
        elif not row.compound in row.Reactants:
            print(f'Compound {row["compound"]} is not associated to reaction {row["kegg_id"]}')
            continue
    #there is no kcat associated to this reaction, try to use EC number to get a kcat value
    else: 
        got_enzyme_info = eco_enzymes_df[eco_enzymes_df['ec_number']==row.EC]
        for i, info in got_enzyme_info.iterrows():
            #is there any enzyme association if we look at the metabolites in the reaction and the EC number?
            if info.compound in row.Products:
                direction = 'b'
            elif info.compound in row.Reactants:
                direction = 'f'
            else:
                continue
            #change the kcat if it is not there already or create a new enzyme association
            if np.isnan(row.kcat_values):
                eco_enzymes_merged.direction.iloc[index] = 'b'
                eco_enzymes_merged.kcat_values.iloc[index] = info.kcat_values
            else:
                eco_enzymes_merged.loc[len(eco_enzymes_merged)] = row.to_list()[:-2]+[info.kcat_values, 'b']
        #add default information for unmappable proteins
        
        if (row.GPR == '') and not isinstance(row.EC, float): 
            eco_enzymes_merged.gene[index] = [f'Gene_{row.rxn_id}_{row.EC}']
            eco_enzymes_merged.GPR[index] = f'Gene_{row.rxn_id}_{row.EC}'
            eco_enzymes_merged.enzyme_id[index] = f'Enzyme_{row.rxn_id}_{row.EC}'
        if isinstance(row.gene, float) and len(row.GPR)>0:
            eco_enzymes_merged.gene[index] = [row.GPR]
        if not isinstance(row.enzyme_id, str) and len(row.GPR)>0:
            eco_enzymes_merged.enzyme_id[index] = f'Enzyme_{row.gene}'
        
        if np.isnan(row.kcat_values) & (isinstance(row.enzyme_id, str)) & (row.GPR!= 's0001'):
            eco_enzymes_merged.direction.iloc[index] = 'f'
            eco_enzymes_merged.kcat_values.iloc[index] = DEFAULT_KCAT
        if np.isnan(row.Mass) & (len(row.GPR)>2) & (row.GPR!= 's0001'):
            eco_enzymes_merged.Mass.iloc[index] = DEFAULT_PROT_MW
        
        
eco_enzymes_mapped = eco_enzymes_merged.drop(['ec_number', 'compound'], axis=1).rename({'Mass':'molMass',
                                                                                       'b_number': 'gene'}, axis =1)
eco_enzymes_mapped

/tmp/ipykernel_689443/253922216.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.gene[index] = [f'Gene_{row.rxn_id}_{row.EC}']
/tmp/ipykernel_689443/253922216.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.GPR[index] = f'Gene_{row.rxn_id}_{row.EC}'
/tmp/ipykernel_689443/253922216.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.enzyme_id[index] = f'Enzyme_{row.rxn_id}_{row.EC}'
/tmp/ipykernel_689443/253922216.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.enzyme_id[index] = f'Enzyme_{row.gene}'
/tmp/ipykernel_689443/253922216.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.Mass.iloc[index] = DEFAULT_PROT_MW
/tmp/ipykernel_689443/253922216.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.direction.iloc[index] = 'f'
/tmp/ipykernel_689443/253922216.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.kcat_values.iloc[index] = DEFAULT_KCAT
/tmp/ipykernel_689443/253922216.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.direction.iloc[index] = 'b'
/tmp/ipykernel_689443/253922216.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.kcat_values.iloc[index] = info.kcat_values
/tmp/ipykernel_689443/253922216.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.gene[index] = [row.GPR]

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,molMass,Length,kcat_values,direction
0,2AGPEAT160,NaN,NaN,MNXR94760,[],[],2.3.1.40,Gene_2AGPEAT160_2.3.1.40,[Gene_2AGPEAT160_2.3.1.40],Enzyme_2AGPEAT160_2.3.1.40,NaN,NaN,NaN,f
1,2AGPEAT180,NaN,NaN,MNXR94762,[],[],2.3.1.40,Gene_2AGPEAT180_2.3.1.40,[Gene_2AGPEAT180_2.3.1.40],Enzyme_2AGPEAT180_2.3.1.40,NaN,NaN,NaN,f
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Enzyme_lcl_NC_006958_1_prot_WP_003855288_1_2949,39959.4825,NaN,NaN,f
3,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,cg3199,Enzyme_cg3199,39959.4825,NaN,NaN,f
4,3HAD140,R04568,NaN,MNXR94879,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...",4.2.1.61,Gene_3HAD140_4.2.1.61,[Gene_3HAD140_4.2.1.61],Enzyme_3HAD140_4.2.1.61,NaN,NaN,NaN,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2480,CAT,R00009,"[20309, 20310, 20311, 20312]",MNXR96455,"[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...",1.11.1.6,WP_011013509_1,WP_011013509_1,Q8NLR8,39959.4825,NaN,13.7,f
2481,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013606_1,Enzyme_WP_011013606_1,39959.4825,NaN,NaN,f
2482,SUCDi,NaN,"[29187, 29188, 29189, 29190]",MNXR99641,[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013607_1,Enzyme_WP_011013607_1,39959.4825,NaN,NaN,f
2483,PRFGS_1,NaN,"[17129, 17131, 17130, 17132]",MNXR138721,"[[C00002, C00002;D08646], C04376, [C00064, C00...","[[C00008, C00008;G11113], C04640, [C00025, C00...",6.3.5.3,cg2865,cg2865,Q8NQV9,39959.4825,NaN,13.7,f
2484,PYRt,NaN,NaN,MNXR103384,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,Enzyme_WP_011014733_1,39959.4825,NaN,NaN,f

In [23]:
eco_enzymes_mapped.gene = [[g] for g in eco_enzymes_mapped.gene]
protein2gene, gene2protein = get_protein_gene_mapping(eco_enzymes_mapped, model)


# Ensure the enzyme complexes are merged on one row
eco_enzymes_mapped = merge_enzyme_complexes(eco_enzymes_mapped, gene2protein)

# Save the adjusted dataframe or continue processing
eco_enzymes_mapped

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,molMass,Length,kcat_values,direction
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,[lcl_NC_006958_1_prot_WP_003855288_1_2949],Enzyme_lcl_NC_006958_1_prot_WP_003855288_1_2949,39959.4825,NaN,NaN,f
3,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,[cg3199],Enzyme_cg3199,39959.4825,NaN,NaN,f
9,3MBt2pp,NaN,NaN,MNXR94916,"[C00080, C08262]","[C08262, C00080]",NaN,cg0953,[cg0953],Q8NMS0,39959.4825,NaN,13.7,f
10,3MBt4pp,NaN,NaN,MNXR94917,"[C01330, C08262]","[C01330, C08262]",NaN,cg0953,[cg0953],Q8NS46,39959.4825,NaN,13.7,f
12,3OXCOAT,R00829,"[19482, 19483, 19481, 19484]",MNXR94967,"[C02232, C00010]","[C00091, C00024]",2.3.1.174,cg2625,[cg2625],Enzyme_cg2625,39959.4825,NaN,NaN,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2439,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,[cg2912],Enzyme_cg2912,39959.4825,NaN,NaN,f
2440,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,"[cg0042, cg0043]",Enzyme_cg0042,39959.4825,NaN,NaN,f
2441,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,"[cg0042, cg0043]",Enzyme_cg0043,39959.4825,NaN,NaN,f
2442,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,"[cg0042, cg0043]",Enzyme_cg0042,39959.4825,NaN,NaN,f
2443,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,"[cg0042, cg2695]",Enzyme_cg2695,39959.4825,NaN,NaN,f

In [24]:
#save the dataframe
eco_enzymes_mapped = eco_enzymes_mapped.drop_duplicates(subset = ['rxn_id', 'enzyme_id', 'direction'],
                                                       ignore_index=True)
eco_enzymes_mapped.to_excel(AE_OUTPUT_FILE_PATH)

### 7. Save the dataframe to the proper format for building PAMs

In [25]:
# Get the information about the enzyme sectors
unused_enzymes_df = pd.read_excel(PAM_DATA_FILE_PATH,
                                 sheet_name = 'ExcessEnzymes')
translational_protein_df = pd.read_excel(PAM_DATA_FILE_PATH,
                                 sheet_name = 'Translational')

In [26]:
# Save it to a new excel file
with pd.ExcelWriter(OUTPUT_FILE_PATH) as writer:
    eco_enzymes_mapped.to_excel(writer, sheet_name='ActiveEnzymes')
    translational_protein_df.to_excel(writer, sheet_name='Translational')
    unused_enzymes_df.to_excel(writer, sheet_name = 'UnusedEnzyme')