# Initializing kcat values for PAMparametrizer

In this notebook, we give an overview of how an initial set of turnover number can be obtained. To enable this, we use multiple databases to map kcat values obtained from machine learning (from the [GotEnzymes](https://metabolicatlas.org/gotenzymes) database) to the proteins and reactions in the model using the gene-protein-reaction associations.

Before we start, we have to set up all the package and files required. Adjust the filenames and paths as desired.

In [25]:
import pandas as pd
import os
from cobra.io import read_sbml_model
import matplotlib.pyplot as plt
import re
import numpy as np
import datetime

from PAModelpy.utils.pam_generation import merge_enzyme_complexes, get_protein_gene_mapping

if os.path.split(os.getcwd())[1]=='i1_preprocessing':
    os.chdir('../..')

DEFAULT_PROT_MW = 39959.4825 #g/mol
DEFAULT_KCAT =  11.0 #/s median value from BRENDA

PAM_DATA_FILE_PATH = os.path.join('Data', 'proteinAllocationModel_iJN1463_EnzymaticData_240807.xlsx')
UNIPROT_FILE_PATH = os.path.join('Data', 'Databases','uniprotkb_pputidakt2240_240807.xlsx')

GOTENZYMES_FILE_PATH = os.path.join('Data','Databases', 'GotEnzymes_ppu_240807.json')

In [2]:
#output file path
# Create a datetime object for the current date
current_date = datetime.datetime.now()
# Format the date as yymmdd
formatted_date = current_date.strftime('%y%m%d')

OUTPUT_FILE_PATH = os.path.join('Results', '1_preprocessing', f'proteinAllocationModel_iJN1463_EnzymaticData_{formatted_date}.xlsx')
AE_OUTPUT_FILE_PATH = os.path.join('Results', '1_preprocessing', f'{formatted_date}_ppu_ActiveEnzymeInformation_GotEnzymes.xlsx')

## 0. Download information from different databases
1. **Metabolic model stoichiometries and reactions: [BiGG database](http://bigg.ucsd.edu/)**
- Get your model! Or use your own reaction identifiers
- In this example we will use the iJN1463 model for [*Pseudomonas putida* KT2240](http://bigg.ucsd.edu/models/iJN1463)
- Important: the identifiers must me mappable to uniprot (or another enzyme identifier database) and KEGG (for mapping to GotEnzymes)

2. **Turnover numbers: [GotEnzymes](https://metabolicatlas.org/gotenzymes)**
- Go to the [API of the Metabolic Atlas](https://metabolicatlas.org/api/v2/#/GotEnzymes/gotEnzymes)
- Use the `GET\gotenzymes\enzymes?` functionality, click `Try it out`
- Here we filled in `ppu` (*P. putida* strain KT2240) for `organism` and `10000` for `pagination[pageSize]`. The rest was left empty
- Click execute and a json file with all the information will be generated
- Once the webpage is finished processing your query, scroll down and copy/download the resulting json file
- Note: GotEnzymes gives the locus tag, ec number, reaction id and compound for each protein. The latter 2 are given as KEGG identifiers, which we subsequently have to map to BiGG identifiers in order to match with the model. Therefore, we need to use other databases

3. **Gene-Protein-Reaction relations: [UniprotKB](https://www.uniprot.org/)**
- Got to the [Uniprot knowledge base](https://www.uniprot.org/) and used advanced search to query for your organism. For *P. putida* we used [this](https://www.uniprot.org/uniprotkb?query=%22pseudomonas+putida%22+AND+%28organism_id%3A160488%29) (strain: *Pseudomonas putida (strain ATCC 47054 / DSM 6125 / CFBP 8728 / NCIMB 11950 / KT2440)*) webpage
- Click download, select `format`:`Excel` and select the following: 
    - `Uniprot Data -> Names & Taxonomy`: `Gene Names`
    - `Uniprot Data -> Sequences`: `length`, `mass`
    - `Uniprot Data -> Function`: `RheaID`
- Mark `Compressed` as `No`
- Download the resulting Excel file

## 1. Get information from the BiGG model

In the metabolic model itself is already quite some information stored. In order to obtain up-to-date information on the enzymes related to the reaction, we will need to obtain the kegg reaction ID, the reactants, the product and the gene-protein relation.

In [3]:
#load the model
model = read_sbml_model(os.path.join('Models', 'iJN1463.xml'))

expand=False

#make a id mapping and create a mapping dataframe
id_mapper_df = pd.DataFrame(columns = ['rxn_id', 'kegg_id', 'rhea_id', 'mnx_id','Reactants','Products','EC', 'GPR'])
for rxn in model.reactions:
    #skip transport reactions and ATP maintenance requirement
    if 'ex' in rxn.id or 'EX' in rxn.id or rxn.id == 'ATPM':
        continue
    to_append= []   
    to_append.append(rxn.annotation['bigg.reaction'])
    #not all reactions are annotated with a KEGG ID in the model
    try: 
        to_append.append(rxn.annotation['kegg.reaction'])
    except:
        to_append.append(np.nan)
    try: 
        to_append.append(rxn.annotation['rhea'])
    except:
        to_append.append(np.nan)
    try: 
        to_append.append(rxn.annotation['metanetx.reaction'])
    except:
        to_append.append(np.nan)
    try:
        to_append.append([reac.annotation['kegg.compound'] for reac in rxn.reactants])
    except:
        to_append.append([])
    try: 
        to_append.append([prod.annotation['kegg.compound'] for prod in rxn.products])
    except:
        to_append.append([])
    if 'ec-code' in rxn.annotation.keys():
        #if there are multiple enzymes make seperate lists
        if isinstance(rxn.annotation['ec-code'], list) and expand:
            info = to_append.copy()
            for i in range(len(rxn.annotation['ec-code'])):
                #make a new row for each enzyme by copying the previous information
                info = to_append.copy()
                ec= rxn.annotation['ec-code'][i]
                info.append(ec)
                #add gpr
                info.append(rxn.gene_reaction_rule)
                #add to df
                id_mapper_df.loc[len(id_mapper_df)] = info
        else:
            to_append.append(rxn.annotation['ec-code'])
            to_append.append(rxn.gene_reaction_rule)
            id_mapper_df.loc[len(id_mapper_df)] = to_append
    else:
        to_append.append(np.nan)
        #ignore entries without enzyme and gpr relation
        if rxn.gene_reaction_rule =='':
            continue
        else:
            to_append.append(rxn.gene_reaction_rule)
        id_mapper_df.loc[len(id_mapper_df)] = to_append
        
#remove entries without GRP relation or Ec number


print('Number of reactions in the mapping dataframe: ',len(id_mapper_df))
print('Number of reactions mapped to KEGG identifier: ', len(id_mapper_df.kegg_id.dropna()))
print('Number of reactions mapped to rhea identifier: ', len(id_mapper_df.rhea_id.dropna()))
print('Number of reactions mapped to MetaNetX identifier: ', len(id_mapper_df.mnx_id.dropna()))
id_mapper_df.head()

Set parameter Username
Academic license - for non-commercial use only - expires 2025-03-06
Number of reactions in the mapping dataframe:  2007
Number of reactions mapped to KEGG identifier:  698
Number of reactions mapped to rhea identifier:  777
Number of reactions mapped to MetaNetX identifier:  1375

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174
1,1P2CBXLCYCL,NaN,NaN,NaN,[C01110],[],NaN,PP_s0001
2,1P2CBXLR,NaN,NaN,NaN,[],"[C00006, [C00148, C16435]]",NaN,PP_3591
3,1PPDCRc,R02203,"[12525, 12526, 12527, 12524]",MNXR94711,"[C04092, C00080, C00005]","[C00408, C00006]","[1.5.1.1, 1.5.1.25, 1.5.1.21]",PP_3591
4,1PY4h3cAH,NaN,NaN,NaN,[],[],NaN,PP_1257

## 2. Get all the protein information

Besides information about the reactions, we need the relation to the proteins in order to establish a protein allocation model. We do this using the gene-protein-reaction association obtained from the BIGG model. The genes is the model can be mapped to the Uniprot accessions, which can be mapped to the KEGG reactions using the Rhea database.

### 2.1 Parse the BIGG gene-protein-reaction associations

In [4]:
#You need to adjust this to find the geneid/locustag for your microbe
locustag_regex =r'\b(PP_\d{4})\b'
def extract_locustag_numbers(text):
    return re.findall(locustag_regex, text)

id_mapper_df['b_number'] = id_mapper_df['GPR'].apply(extract_locustag_numbers)
id_mapper_df = id_mapper_df.explode('b_number', ignore_index=True)
id_mapper_df

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174,PP_1602
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174,PP_4174
2,1P2CBXLCYCL,NaN,NaN,NaN,[C01110],[],NaN,PP_s0001,NaN
3,1P2CBXLR,NaN,NaN,NaN,[],"[C00006, [C00148, C16435]]",NaN,PP_3591,PP_3591
4,1PPDCRc,R02203,"[12525, 12526, 12527, 12524]",MNXR94711,"[C04092, C00080, C00005]","[C00408, C00006]","[1.5.1.1, 1.5.1.25, 1.5.1.21]",PP_3591,PP_3591
...,...,...,...,...,...,...,...,...,...
3760,4HTHRS,R05086,"[30659, 30662, 30660, 30661]",MNXR95024,"[[C00001, C01328], C06055]","[C06056, C00009]","[4.2.3.1, 4.2.3]",PP_1471 or PP_0662,PP_0662
3761,4MBZALDH,R05282,NaN,MNXR95030,"[C06757, C00003]","[C06758, C00080, C00004]","[1.1.1.90, 1.1.1.21]",pWW0_128,NaN
3762,4MBZDH,NaN,NaN,MNXR95031,"[C06758, [C00001, C01328], C00003]","[C00080, C00004, C01454]","[1.2.1.3, 1.2.1.28, 1.2.1.7]",pWW0_131,NaN
3763,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN
3764,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN

### 2.2 Parse the Uniprot data for merging

In [5]:
# load the uniprot information
uniprot_df = pd.read_excel(UNIPROT_FILE_PATH)
#get the gene id from the gene names
uniprot_df['b_number'] = uniprot_df['Gene Names'].str.extract(locustag_regex)
uniprot_df = uniprot_df.drop('Gene Names', axis=1)
uniprot_df

/home/samiralvdb/Software/anaconda3/envs/PAModelpy/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Entry,Protein names,Length,Mass,Rhea ID,b_number
0,Q88CC1,2-oxoadipate dioxygenase/decarboxylase (EC 1.1...,464,51372,RHEA:71787,PP_5260
1,Q88E10,Methyl-accepting chemotaxis protein McpS,639,68764,NaN,PP_4658
2,Q88E47,"Homogentisate 1,2-dioxygenase (HGDO) (EC 1.13....",433,48011,RHEA:15449,PP_4621
3,Q88F88,Pyoverdine export ATP-binding/permease protein...,654,69687,NaN,PP_4210
4,Q88FF8,Quinone reductase (EC 1.6.5.2) (Chromate reduc...,186,20354,RHEA:46160 RHEA:46164 RHEA:44372 RHEA:44368,PP_4138
...,...,...,...,...,...,...
5524,Q88RW2,Transcriptional regulator,119,13492,NaN,PP_0017
5525,Q88RW3,TniQ family protein,638,71170,NaN,PP_0016
5526,Q88RW4,Transposon protein,319,36304,NaN,PP_0015
5527,Q88RW5,Transposase,652,74345,NaN,PP_0014
5528,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14,1529,NaN,NaN

### 2.3 Match Uniprot to BIGG data

In [6]:
id_mapper_with_protein = pd.merge(id_mapper_df, uniprot_df, on='b_number', how='left')

id_mapper_with_protein

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number,Entry,Protein names,Length,Mass,Rhea ID
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]","[2.3.1.85, 2.3.1.86, 4.2.1.61, 4.2.1.59, 2.3.1.-]",PP_1602 or PP_4174,PP_4174,Q88FC4,3-hydroxydecanoyl-[acyl-carrier-protein] dehyd...,171.0,18791.0,RHEA:13097 RHEA:41860 RHEA:23568
2,1P2CBXLCYCL,NaN,NaN,NaN,[C01110],[],NaN,PP_s0001,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN
3,1P2CBXLCYCL,NaN,NaN,NaN,[C01110],[],NaN,PP_s0001,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN
4,1P2CBXLR,NaN,NaN,NaN,[],"[C00006, [C00148, C16435]]",NaN,PP_3591,PP_3591,Q88GX6,Delta 1-piperideine-2-carboxylate reductase (E...,332.0,35143.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,4MBZDH,NaN,NaN,MNXR95031,"[C06758, [C00001, C01328], C00003]","[C00080, C00004, C01454]","[1.2.1.3, 1.2.1.28, 1.2.1.7]",pWW0_131,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN
3866,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN
3867,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN
3868,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN
3869,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN

### 3. Match the BiGG model reactiona and enzymes to the kcats from GotEnzymes
Find first all enzymes for a reaction, then for each enzyme determine if the kcats from GotEnzymes are for a forward or reverse reaction

In [7]:
id_mapper_final = id_mapper_with_protein
id_mapper_final = id_mapper_final.rename({'Entry':'enzyme_id'}, axis=1)
id_mapper_final = id_mapper_final.explode('kegg_id', ignore_index=True)
id_mapper_final = id_mapper_final.explode('EC', ignore_index=True)

# id_mapper_final = id_mapper_final.drop_duplicates(subset = ['kegg_id'])
id_mapper_final.head()

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,b_number,enzyme_id,Protein names,Length,Mass,Rhea ID
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.85,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.86,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
2,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.61,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
3,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.59,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097
4,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.-,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097

In [8]:
#get the json file from GotEnzymes and parse into workable format
#read in the json file obtained from gotEnzymes (for 'eco')
eco_enzymes_json = pd.read_json(GOTENZYMES_FILE_PATH)
#convert to a readible format
eco_enzymes = eco_enzymes_json.enzymes.to_list()
eco_enzymes_df = pd.DataFrame(eco_enzymes)

#ensure there is only one ec number per row
eco_enzymes_df['ec_number'] = eco_enzymes_df['ec_number'].str.split(pat=';')
eco_enzymes_df = eco_enzymes_df.explode('ec_number', ignore_index=True)
eco_enzymes_df = eco_enzymes_df.dropna(axis=0, subset=['ec_number'])
eco_enzymes_df = eco_enzymes_df.drop(['organism', 'domain'], axis = 1)
eco_enzymes_df.head()

      gene reaction_id ec_number compound  kcat_values
0  PP_0004      R08701             C00101       3.6784
1  PP_0004      R08701             C00037       1.4164
2  PP_0004      R08701             C03479       3.2723
3  PP_0005      R08701             C00101       2.4913
4  PP_0005      R08701             C03479       2.1913

In [9]:
# match BiGG and GotEnzymes based on gene id
eco_enzymes_merged = id_mapper_final.merge(eco_enzymes_df, 
                              left_on =['b_number', 'kegg_id'], 
                              right_on = ['gene', 'reaction_id'],
                             how = 'left').drop(['gene', 'reaction_id'], axis=1).rename({'b_number':'gene'}, axis=1)
eco_enzymes_merged

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,Protein names,Length,Mass,Rhea ID,ec_number,compound,kcat_values
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.85,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.86,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
2,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.61,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
3,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.59,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
4,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.-,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8279,4MBZDH,NaN,NaN,MNXR95031,"[C06758, [C00001, C01328], C00003]","[C00080, C00004, C01454]",1.2.1.7,pWW0_131,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,NaN,NaN,NaN
8280,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN,NaN,NaN,NaN
8281,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,NaN,NaN,NaN
8282,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN,NaN,NaN,NaN
8283,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,NaN,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,NaN,NaN,NaN

### 6. Extract directionalities and gapfill
Reactions which are associated with an enzyme, but not with a kcat from GotEnzymes will be assignes
a default kcat and if required a default molmass.

In [18]:
# Get directionalities and fill in the gaps
eco_enzymes_mapped = eco_enzymes_merged.copy()
eco_enzymes_mapped['direction'] = 'f'
for index, row in eco_enzymes_mapped.iterrows():
    #there is a kegg id and kcat associated to this reaction
    if not isinstance(row.kcat_values, float):
        if row.compound in row.Products:
            eco_enzymes_mapped.direction[index] = 'b'
        elif not row.compound in row.Reactants:
            print(f'Compound {row["compound"]} is not associated to reaction {row["kegg_id"]}')
            continue
    #there is no kcat associated to this reaction, try to use EC number to get a kcat value
    else: 
        got_enzyme_info = eco_enzymes_df[eco_enzymes_df['ec_number']==row.EC]
        for i, info in got_enzyme_info.iterrows():
            #is there any enzyme association if we look at the metabolites in the reaction and the EC number?
            if info.compound in row.Products:
                direction = 'b'
            elif info.compound in row.Reactants:
                direction = 'f'
            else:
                continue
            #change the kcat if it is not there already or create a new enzyme association
            if np.isnan(row.kcat_values):
                eco_enzymes_mapped.direction[index] = 'b'
                eco_enzymes_mapped.kcat_values[index] = info.kcat_values
#             else:
#                 eco_enzymes_mapped[len(eco_enzymes_mapped)] = row.to_list()[:-2]+[info.kcat_values, 'b']
        #add default information for unmappable proteins
        if (row.GPR == '') and not isinstance(row.EC, float): 
            eco_enzymes_mapped.gene[index] = f'Gene_{row.rxn_id}'
            eco_enzymes_mapped.GPR[index] = f'Gene_{row.rxn_id}'
            eco_enzymes_mapped.enzyme_id[index] = f'Enzyme_{row.rxn_id}'
        if isinstance(row.gene, float) and len(row.GPR)>0:
            eco_enzymes_mapped.gene[index] = row.GPR
        if not isinstance(row.enzyme_id, str) and len(row.GPR)>0:
            eco_enzymes_mapped.enzyme_id[index] = f'Enzyme_{row.rxn_id}'
        
        if row.GPR == 'PP_s0001':
            eco_enzymes_mapped.gene.loc[index] = f'Gene_{row.rxn_id}'
            eco_enzymes_mapped.enzyme_id[index] = f'Enzyme_{row.rxn_id}'
        elif 'pWW0' in row.GPR:
            eco_enzymes_mapped.gene[index] = row.GPR
        if np.isnan(row.kcat_values) & (isinstance(row.enzyme_id, str)):
            eco_enzymes_mapped.direction[index] = 'f'
            eco_enzymes_mapped.kcat_values.loc[index] = DEFAULT_KCAT
        if np.isnan(row.Mass) & (len(row.GPR)>2):
            eco_enzymes_mapped.Mass[index] = DEFAULT_PROT_MW
        
        
eco_enzymes_mapped = eco_enzymes_mapped.drop(['ec_number', 'compound'], axis=1).rename({'Mass':'molMass'}, axis =1)
eco_enzymes_mapped

/tmp/ipykernel_328014/3896603511.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.direction[index] = 'f'
/tmp/ipykernel_328014/3896603511.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.kcat_values.loc[index] = DEFAULT_KCAT
/tmp/ipykernel_328014/3896603511.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.gene[index] = row.GPR
/tmp/ipykernel_328014/3896603511.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.gene.loc[index] = f'Gene_{row.rxn_id}'
/tmp/ipykernel_328014/3896603511.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.enzyme_id[index] = f'Enzyme_{row.rxn_id}'
/tmp/ipykernel_328014/3896603511.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.direction[index] = 'b'
/tmp/ipykernel_328014/3896603511.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.kcat_values[index] = info.kcat_values
/tmp/ipykernel_328014/3896603511.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.gene[index] = f'Gene_{row.rxn_id}'
/tmp/ipykernel_328014/3896603511.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.GPR[index] = f'Gene_{row.rxn_id}'
/tmp/ipykernel_328014/3896603511.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.enzyme_id[index] = f'Enzyme_{row.rxn_id}'
/tmp/ipykernel_328014/3896603511.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.gene[index] = row.GPR
/tmp/ipykernel_328014/3896603511.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.enzyme_id[index] = f'Enzyme_{row.rxn_id}'
/tmp/ipykernel_328014/3896603511.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_mapped.Mass[index] = DEFAULT_PROT_MW

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,Protein names,Length,molMass,Rhea ID,kcat_values,direction
0,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.85,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,11.0,f
1,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.86,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,11.0,f
2,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.61,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,11.0,f
3,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",4.2.1.59,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,11.0,f
4,3HAD160,R04544,NaN,MNXR94881,[C04633],"[[C00001, C01328], C05763]",2.3.1.-,PP_1602 or PP_4174,PP_1602,Q88MG9,3-hydroxyacyl-[acyl-carrier-protein] dehydrata...,146.0,16583.0,RHEA:13097,11.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8279,4MBZDH,NaN,NaN,MNXR95031,"[C06758, [C00001, C01328], C00003]","[C00080, C00004, C01454]",1.2.1.7,pWW0_131,pWW0_131,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,11.0,f
8280,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,pWW0_097,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN,11.0,f
8281,4MCAT23DOX,R05295,NaN,MNXR95032,"[C06730, C00007]","[C00080, C06760]",1.13.11.2,pWW0_097,pWW0_097,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,11.0,f
8282,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,pWW0_091,G1JLS8,Phosphatidylcholine synthase (EC 2.7.8.24),205.0,21908.0,NaN,11.0,f
8283,4OD,NaN,NaN,MNXR126192,"[C00080, C03453]",[],NaN,pWW0_091,pWW0_091,V6C0L5,Proteolysis tag peptide encoded by tmRNA Psmon...,14.0,1529.0,NaN,11.0,f

In [19]:
eco_enzymes_mapped[eco_enzymes_mapped.gene== 'PP_3365']

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,Protein names,Length,molMass,Rhea ID,kcat_values,direction
7191,ACLS,R00226,"[25252, 25251, 25249, 25250]",MNXR95271,"[C00080, C00022]","[C06010, C00011]",2.2.1.6,(PP_4679 and PP_4680) or PP_1157 or PP_3365,PP_3365,Enzyme_ACLS,NaN,NaN,39959.4825,NaN,52.0251,f
7192,ACLS,R00226,"[25252, 25251, 25249, 25250]",MNXR95271,"[C00080, C00022]","[C06010, C00011]",2.2.1.6,(PP_4679 and PP_4680) or PP_1157 or PP_3365,PP_3365,Enzyme_ACLS,NaN,NaN,39959.4825,NaN,154.0210,f
7193,ACLS,R00226,"[25252, 25251, 25249, 25250]",MNXR95271,"[C00080, C00022]","[C06010, C00011]",2.2.1.6,(PP_4679 and PP_4680) or PP_1157 or PP_3365,PP_3365,Enzyme_ACLS,NaN,NaN,39959.4825,NaN,125.3000,f

In [12]:
import pandas as pd
import numpy as np
import cobra
from typing import TypedDict, Literal, Union, Tuple, Iterable
import re
import os

from collections import defaultdict
from dataclasses import dataclass, field


def parse_gpr_information(gpr_info:str,
                          genes:list=None,
                          enzyme_id:str=None,
                          gene2protein: dict[str, str] = None) -> tuple[list,list]:
    #filter out nan entries
    if not isinstance(gpr_info, str):
        return None, None

    # #only get the genes associated with this enzyme
    print(gpr_info)
    gpr_list = _parse_gpr(gpr_info)
    print(gpr_list)
    gpr_list = _filter_sublists(gpr_list, genes)

    if genes is None: return gpr_list

    #convert the genes to the associated proteins
    enzyme_relations = []
    print('enz', enzyme_id)
    if '_'in enzyme_id:
        enzyme_relations = [enzyme_id.split('_')]
    for sublist in gpr_list:
        enz_sublist = []
        for item in sublist:
            if item in gene2protein.keys():
                if '_' not in gene2protein[item]:
                    enz_sublist.append(gene2protein[item])
                    enzyme_relations += [enz_sublist]
                elif gene2protein[item].split('_') not in enzyme_relations:
                    enzyme_relations += [gene2protein[item].split('_')]
        enzyme_relations = _filter_sublists(enzyme_relations, enzyme_id.split('_'))
    return sorted(gpr_list), sorted(enzyme_relations)

def get_protein_gene_mapping(enzyme_db: pd.DataFrame, model) -> tuple[dict, dict]:
    protein2gene = defaultdict(list)
    gene2protein = {}
    for index, row in enzyme_db.iterrows():
        # Parse data from the row
        rxn_id = row['rxn_id']
        if rxn_id not in model.reactions: continue
        rxn = model.reactions.get_by_id(rxn_id)
        # get the identifiers and replace nan values by dummy placeholders
        enzyme_id = row['enzyme_id']
        gene_id = row['gene']

        # check if there are genes associates with the reaction
        if len(rxn.genes) > 0 or isinstance(gene_id, str):
            if not isinstance(enzyme_id, str):
                enzyme_id = 'Enzyme_' + rxn_id
            if not isinstance(gene_id, str):
                gene_id = [gene.id for gene in rxn.genes][0]

            gene2protein[gene_id] = enzyme_id

            # Create gene-protein-reaction associations
            if enzyme_id not in protein2gene:
                protein2gene[enzyme_id].append(gene_id)

    return dict(protein2gene), gene2protein

def _parse_gpr(gpr_info):
    # Split the string by 'or' first
    or_groups = gpr_info.split(' or ')
    parsed_gpr = []
    for group in or_groups:
        # Within each 'or' group, split by 'and'
        and_genes = group.split(' and ')
        # Clean up each gene string
        and_genes = [gene.strip(' ()') for gene in and_genes]
        parsed_gpr.append(and_genes)
    return parsed_gpr

def _filter_sublists(nested_list:list[list[str]], target_list:list[str]) -> list[str]:
    """
    Keeps only sublists from `nested_list` that contain at least one identifier present in `target_list`.

    Args:
        nested_list (list of lists): The main list of sublists to filter.
        target_list (list of str): The flat list of identifiers to include.

    Returns:
        list of lists: The filtered nested list.
    """
    print(nested_list, target_list)
    filtered_list = [sublist for sublist in nested_list if any([item in target_list for item in sublist])]

    return filtered_list



def _get_kcat_value_from_catalytic_reaction_df(catalytic_reaction_df: pd.DataFrame,
                                               direction:str) -> float:
    if direction not in catalytic_reaction_df.direction.values:
        return 0
    else:
        return catalytic_reaction_df.kcat_values[
            catalytic_reaction_df.direction == direction].iloc[0]



# Function to parse GPR and determine multimer
def merge_enzyme_complexes(df, gene2protein):
    collapsed_rows = []

    for rxn_id, group in df.groupby('rxn_id'):
        for _, row in group.iterrows():
            # Parse GPR
            gpr_list, enzyme_relations = parse_gpr_information(
                row['GPR'], row['gene'], row['enzyme_id'], gene2protein
            )
            # Collapse "and" relationships into multimer ID
            if enzyme_relations:
                for gene_list, enzyme_list in zip(gpr_list, enzyme_relations):
                    row_copy = row.copy()
                    row_copy['enzyme_id'] = "_".join(enzyme_list)  # Replace gene with multimer
                    row_copy['gene'] = gene_list  # add all the annotations to the corresponding gene

                    collapsed_rows.append(row_copy)
            else:
                collapsed_rows.append(row)

    # Create a new dataframe with collapsed rows
    collapsed_df = pd.DataFrame(collapsed_rows)
    return collapsed_df

def increase_kcats_in_parameter_file(kcat_increase_factor: int,
                                     pam_info_file_path_ori: str,
                                     pam_info_file_path_out: str = None):

    if pam_info_file_path_out is None:
        pam_info_file_path_out= f'{pam_info_file_path_ori.split(".")[0]}_multi.xlsx'

    pam_info_dfs = pd.read_excel(pam_info_file_path_ori, sheet_name=None)

    pam_info_file_ori = pam_info_dfs.pop('ActiveEnzymes')
    pam_info_file_new = pam_info_file_ori.rename({'kcat_values': 'kcat_values_ori'})
    pam_info_file_new['kcat_values'] = pam_info_file_ori['kcat_values']*kcat_increase_factor

    write_mode = 'w'
    kwargs = {}
    if os.path.isfile(pam_info_file_path_out):
        write_mode = 'a'
        kwargs = {'if_sheet_exists': 'replace'}

    with pd.ExcelWriter(pam_info_file_path_out, engine = 'openpyxl',
                        mode = write_mode, **kwargs) as writer:
        pam_info_file_new.to_excel(writer, sheet_name = 'ActiveEnzymes', index=False)
        for sheet_name, df in pam_info_dfs.items():
            df.to_excel(writer, sheet_name = sheet_name, index=False)

In [20]:
protein2gene, gene2protein = get_protein_gene_mapping(eco_enzymes_mapped, model)


# Ensure the enzyme complexes are merged on one row
eco_enzymes_mapped = merge_enzyme_complexes(eco_enzymes_mapped, gene2protein)

# Save the adjusted dataframe or continue processing
eco_enzymes_mapped

PP_2492
[['PP_2492']]
[['PP_2492']] PP_2492
enz Q88K01
[['Q88K01']] ['Q88K01']
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_1P2CBXLCYCL
enz Enzyme_1P2CBXLCYCL
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_1P2CBXLCYCL
enz Enzyme_1P2CBXLCYCL
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_3591
[['PP_3591']]
[['PP_3591']] PP_3591
enz Q88GX6
[['Q88GX6']] ['Q88GX6']
PP_1257
[['PP_1257']]
[['PP_1257']] PP_1257
enz Q88NF4
[['Q88NF4']] ['Q88NF4']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2008
[['PP_2008']]
[['PP_2008']] PP_2008
enz Q88LC7
[['Q88LC7']] ['Q88LC7']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_1700
[['PP_1700']]
[['PP_1700']] PP_1700
enz Q88M74
[['Q88M74']] ['Q88M74']
PP_3378
[['PP_3378']]
[['PP_3378']] PP_3378
enz Q88HH9
[['Q88HH9']] ['Q88HH9']
PP_3378
[['PP_3378']]
[['PP_3378']] PP_3378
enz Q88HH9
[['Q88HH9']] ['Q88HH9']
PP_3377
[['PP_3377']]
[['PP_3377']] PP_3377
enz Q88HI0
[['Q88HI0']] ['Q88HI0']
PP_2933
[['PP_2933']]
[['PP_2933']] PP_2933
enz Q88IR6
[['Q88IR6']] ['Q88IR6']
PP_3433
[['PP_3433']]
[['PP_3433']] PP_3433
enz Q88HC7
[['Q88HC7']] ['Q88HC7']
PP_3433
[['PP_3433']]
[['PP_3433']] PP_3433
enz Q88HC7
[['Q88HC7']] ['Q88HC7']
PP_3433
[['PP_3433']]
[['PP_3433']] PP_3433
enz Q88HC7
[['Q88HC7']] ['Q88HC7']
PP_0596
[['PP_0596']]
[['PP_0596']] PP_0596
enz Q88Q98
[['Q88Q98']] ['Q88Q98']
PP_1408
[['PP_1408']]
[['PP_1408']] PP_1408
enz O85207
[['O85207']] ['O85207']
PP_1408
[['PP_1408']]
[['PP_1408']] PP_1408
enz O85207
[['O85207']] ['O85207']
PP_1408
[['PP_1408']]
[['PP_1408']] PP_1408
enz O85207
[['O85207']] ['O85207']
PP_1408
[['PP_1408']]
[['PP_1408']] PP_1408
enz O85207
[['O85207']] ['O85207']
PP_1408
[['PP_1408']]
[['PP_1408']] PP_1408
enz O85207
[['O85207']] ['O85207']
PP_1408
[['PP_1408']]
[['PP_1408']] PP_1408
enz O85207
[['O85207']] ['O85207']
PP_1408
[['PP_1408']]
[['PP_1408']] PP_1408
enz O85207
[['O85207']] ['O85207']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_4174 or PP_1602
[['PP_4174'], ['PP_1602']]
[['PP_4174'], ['PP_1602']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_1602
enz Q88MG9
[['Q88MG9']] ['Q88MG9']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
PP_1602 or PP_4174
[['PP_1602'], ['PP_4174']]
[['PP_1602'], ['PP_4174']] PP_4174
enz Q88FC4
[['Q88FC4']] ['Q88FC4']
Gene_3HBCOAHL
[['Gene_3HBCOAHL']]
[['Gene_3HBCOAHL']] Gene_3HBCOAHL
enz Enzyme_3HBCOAHL
[['Enzyme', '3HBCOAHL']] ['Enzyme', '3HBCOAHL']
Gene_3HBCOAHL
[['Gene_3HBCOAHL']]
[['Gene_3HBCOAHL']] Gene_3HBCOAHL
enz Enzyme_3HBCOAHL
[['Enzyme', '3HBCOAHL']] ['Enzyme', '3HBCOAHL']
PP_2552
[['PP_2552']]
[['PP_2552']] PP_2552
enz Q88JU5
[['Q88JU5']] ['Q88JU5']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
pWW0_128
[['pWW0_128']]
[['pWW0_128']] pWW0_128
enz G1JLS8
[['V6C0L5']] ['G1JLS8']
pWW0_128
[['pWW0_128']]
[['pWW0_128']] pWW0_128
enz G1JLS8
[['V6C0L5']] ['G1JLS8']
pWW0_128
[['pWW0_128']]
[['pWW0_128']] pWW0_128
enz V6C0L5
[['V6C0L5']] ['V6C0L5']
pWW0_128
[['pWW0_128']]
[['pWW0_128']] pWW0_128
enz V6C0L5
[['V6C0L5']] ['V6C0L5']
pWW0_131
[['pWW0_131']]
[['pWW0_131']] pWW0_131
enz G1JLS8
[['V6C0L5']] ['G1JLS8']
pWW0_131
[['pWW0_131']]
[['pWW0_131']] pWW0_131
enz G1JLS8
[['V6C0L5']] ['G1JLS8']
pWW0_131
[['pWW0_131']]
[['pWW0_131']] pWW0_131
enz G1JLS8
[['V6C0L5']] ['G1JLS8']
pWW0_131
[['pWW0_131']]
[['pWW0_131']] pWW0_131
enz V6C0L5
[['V6C0L5']] ['V6C0L5']
pWW0_131
[['pWW0_131']]
[['pWW0_131']] pWW0_131
enz V6C0L5
[['V6C0L5']] ['V6C0L5']
pWW0_131
[['pWW0_131']]
[['pWW0_131']] pWW0_131
enz V6C0L5
[['V6C0L5']] ['V6C0L5']
pWW0_097
[['pWW0_097']]
[['pWW0_097']] pWW0_097
enz G1JLS8
[['V6C0L5']] ['G1JLS8']
pWW0_097
[['pWW0_097']]
[['pWW0_097']] pWW0_097
enz G1JLS8
[['V6C0L5']] ['G1JLS8']
pWW0_097
[['pWW0_097']]
[['pWW0_097']] pWW0_097
enz G1JLS8
[['V6C0L5']] ['G1JLS8']
pWW0_097
[['pWW0_097']]
[['pWW0_097']] pWW0_097
enz V6C0L5
[['V6C0L5']] ['V6C0L5']
pWW0_097
[['pWW0_097']]
[['pWW0_097']] pWW0_097
enz V6C0L5
[['V6C0L5']] ['V6C0L5']
pWW0_097
[['pWW0_097']]
[['pWW0_097']] pWW0_097
enz V6C0L5
[['V6C0L5']] ['V6C0L5']
PP_3951 and PP_3952
[['PP_3951', 'PP_3952']]
[['PP_3951', 'PP_3952']] PP_3951
enz Q88FX5
[['Q88FX5', 'P0A101'], ['Q88FX5', 'P0A101']] ['Q88FX5']
PP_3951 and PP_3952
[['PP_3951', 'PP_3952']]
[['PP_3951', 'PP_3952']] PP_3951
enz Q88FX5
[['Q88FX5', 'P0A101'], ['Q88FX5', 'P0A101']] ['Q88FX5']
PP_3951 and PP_3952
[['PP_3951', 'PP_3952']]
[['PP_3951', 'PP_3952']] PP_3951
enz Q88FX5
[['Q88FX5', 'P0A101'], ['Q88FX5', 'P0A101']] ['Q88FX5']
PP_3951 and PP_3952
[['PP_3951', 'PP_3952']]
[['PP_3951', 'PP_3952']] PP_3951
enz Q88FX5
[['Q88FX5', 'P0A101'], ['Q88FX5', 'P0A101']] ['Q88FX5']
PP_3951 and PP_3952
[['PP_3951', 'PP_3952']]
[['PP_3951', 'PP_3952']] PP_3952
enz P0A101
[['Q88FX5', 'P0A101'], ['Q88FX5', 'P0A101']] ['P0A101']
PP_3951 and PP_3952
[['PP_3951', 'PP_3952']]
[['PP_3951', 'PP_3952']] PP_3952
enz P0A101
[['Q88FX5', 'P0A101'], ['Q88FX5', 'P0A101']] ['P0A101']
PP_3951 and PP_3952
[['PP_3951', 'PP_3952']]
[['PP_3951', 'PP_3952']] PP_3952
enz P0A101
[['Q88FX5', 'P0A101'], ['Q88FX5', 'P0A101']] ['P0A101']
PP_3951 and PP_3952
[['PP_3951', 'PP_3952']]
[['PP_3951', 'PP_3952']] PP_3952
enz P0A101
[['Q88FX5', 'P0A101'], ['Q88FX5', 'P0A101']] ['P0A101']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1914
[['PP_1914']]
[['PP_1914']] PP_1914
enz Q88LL6
[['Q88LL6']] ['Q88LL6']
PP_1916 or PP_4175 or PP_3303
[['PP_1916'], ['PP_4175'], ['PP_3303']]
[['PP_1916'], ['PP_4175'], ['PP_3303']] PP_1916
enz Q88LL4
[['Q88LL4']] ['Q88LL4']
PP_1916 or PP_4175 or PP_3303
[['PP_1916'], ['PP_4175'], ['PP_3303']]
[['PP_1916'], ['PP_4175'], ['PP_3303']] PP_4175
enz Q88FC3
[['Q88FC3']] ['Q88FC3']
PP_1916 or PP_4175 or PP_3303
[['PP_1916'], ['PP_4175'], ['PP_3303']]
[['PP_1916'], ['PP_4175'], ['PP_3303']] PP_3303
enz Q88HQ0
[['Q88HQ0']] ['Q88HQ0']
PP_1916 or PP_4175 or PP_3303
[['PP_1916'], ['PP_4175'], ['PP_3303']]
[['PP_1916'], ['PP_4175'], ['PP_3303']] PP_1916
enz Q88LL4
[['Q88LL4']] ['Q88LL4']

PP_1769
[['PP_1769']]
[['PP_1769']] PP_1769
enz Q88M06
[['Q88M06']] ['Q88M06']
PP_1769
[['PP_1769']]
[['PP_1769']] PP_1769
enz Q88M06
[['Q88M06']] ['Q88M06']
PP_1769
[['PP_1769']]
[['PP_1769']] PP_1769
enz Q88M06
[['Q88M06']] ['Q88M06']
PP_1769
[['PP_1769']]
[['PP_1769']] PP_1769
enz Q88M06
[['Q88M06']] ['Q88M06']
PP_1769
[['PP_1769']]
[['PP_1769']] PP_1769
enz Q88M06
[['Q88M06']] ['Q88M06']
PP_1769
[['PP_1769']]
[['PP_1769']] PP_1769
enz Q88M06
[['Q88M06']] ['Q88M06']
PP_1769
[['PP_1769']]
[['PP_1769']] PP_1769
enz Q88M06
[['Q88M06']] ['Q88M06']
PP_3721
[['PP_3721']]
[['PP_3721']] PP_3721
enz Q88GK0
[['Q88GK0']] ['Q88GK0']
PP_3721
[['PP_3721']]
[['PP_3721']] PP_3721
enz Q88GK0
[['Q88GK0']] ['Q88GK0']
PP_3721
[['PP_3721']]
[['PP_3721']] PP_3721
enz Q88GK0
[['Q88GK0']] ['Q88GK0']
PP_3721
[['PP_3721']]
[['PP_3721']] PP_3721
enz Q88GK0
[['Q88GK0']] ['Q88GK0']
PP_1989
[['PP_1989']]
[['PP_1989']] PP_1989
enz Q88LE4
[['Q88LE4']] ['Q88LE4']
PP_1989
[['PP_1989']]
[['PP_1989']] PP_1989
enz Q88LE4
[['Q88LE4']] ['Q88LE4']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_0495
enz Q88QJ6
[['Q88QJ6']] ['Q88QJ6']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_0495 or PP_1160
[['PP_0495'], ['PP_1160']]
[['PP_0495'], ['PP_1160']] PP_1160
enz Q88NP7
[['Q88NP7']] ['Q88NP7']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_2453
[['PP_2453']]
[['PP_2453']] PP_2453
enz Q88K39
[['Q88K39']] ['Q88K39']
PP_1750
[['PP_1750']]
[['PP_1750']] PP_1750
enz Q88M25
[['Q88M25']] ['Q88M25']
PP_1750
[['PP_1750']]
[['PP_1750']] PP_1750
enz Q88M25
[['Q88M25']] ['Q88M25']
PP_1750
[['PP_1750']]
[['PP_1750']] PP_1750
enz Q88M25
[['Q88M25']] ['Q88M25']
PP_1750
[['PP_1750']]
[['PP_1750']] PP_1750
enz Q88M25
[['Q88M25']] ['Q88M25']
PP_1929 or PP_2717
[['PP_1929'], ['PP_2717']]
[['PP_1929'], ['PP_2717']] PP_1929
enz Q88LK2
[['Q88LK2']] ['Q88LK2']
PP_1929 or PP_2717
[['PP_1929'], ['PP_2717']]
[['PP_1929'], ['PP_2717']] PP_2717
enz Q88JD2
[['Q88JD2']] ['Q88JD2']
PP_1373 or PP_4103
[['PP_1373'], ['PP_4103']]
[['PP_1373'], ['PP_4103']] PP_1373
enz Q88N43
[['Q88N43']] ['Q88N43']
PP_1373 or PP_4103
[['PP_1373'], ['PP_4103']]
[['PP_1373'], ['PP_4103']] PP_4103
enz Q88FJ2
[['Q88FJ2']] ['Q88FJ2']
PP_4222
[['PP_4222']]
[['PP_4222']] PP_4222
enz Q88F76
[['Q88F76']] ['Q88F76']
PP_4998 and PP_4999
[['PP_4998', 'PP_4999']]
[['PP_4998', 'PP_4999']] PP_4998
enz Q88D30
[['Q88D30', 'Q88D29'], ['Q88D30', 'Q88D29']] ['Q88D30']
PP_4998 and PP_4999
[['PP_4998', 'PP_4999']]
[['PP_4998', 'PP_4999']] PP_4998
enz Q88D30
[['Q88D30', 'Q88D29'], ['Q88D30', 'Q88D29']] ['Q88D30']
PP_4998 and PP_4999
[['PP_4998', 'PP_4999']]
[['PP_4998', 'PP_4999']] PP_4998
enz Q88D30
[['Q88D30', 'Q88D29'], ['Q88D30', 'Q88D29']] ['Q88D30']
PP_4998 and PP_4999
[['PP_4998', 'PP_4999']]
[['PP_4998', 'PP_4999']] PP_4999
enz Q88D29
[['Q88D30', 'Q88D29'], ['Q88D30', 'Q88D29']] ['Q88D29']
PP_4473
[['PP_4473']]
[['PP_4473']] PP_4473
enz Q88EI9
[['Q88EI9']] ['Q88EI9']
PP_4473
[['PP_4473']]
[['PP_4473']] PP_4473
enz Q88EI9
[['Q88EI9']] ['Q88EI9']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_1426
[['PP_1426']]
[['PP_1426']] PP_1426
enz Q88MZ2
[['Q88MZ2']] ['Q88MZ2']
PP_4422
[['PP_4422']]
[['PP_4422']] PP_4422
enz Q88EN2
[['Q88EN2']] ['Q88EN2']
PP_5338
[['PP_5338']]
[['PP_5338']] PP_5338
enz Q88C45
[['Q88C45']] ['Q88C45']
PP_5338
[['PP_5338']]
[['PP_5338']] PP_5338
enz Q88C45
[['Q88C45']] ['Q88C45']
PP_5338
[['PP_5338']]
[['PP_5338']] PP_5338
enz Q88C45
[['Q88C45']] ['Q88C45']
PP_3721 or PP_1972
[['PP_3721'], ['PP_1972']]
[['PP_3721'], ['PP_1972']] PP_3721
enz Q88GK0
[['Q88GK0']] ['Q88GK0']
PP_3721 or PP_1972
[['PP_3721'], ['PP_1972']]
[['PP_3721'], ['PP_1972']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1213
[['PP_1213']]
[['PP_1213']] PP_1213
enz Q88NJ4
[['Q88NJ4']] ['Q88NJ4']
PP_1213
[['PP_1213']]
[['PP_1213']] PP_1213
enz Q88NJ4
[['Q88NJ4']] ['Q88NJ4']
PP_1213
[['PP_1213']]
[['PP_1213']] PP_1213
enz Q88NJ4
[['Q88NJ4']] ['Q88NJ4']
PP_1213
[['PP_1213']]
[['PP_1213']] PP_1213
enz Q88NJ4
[['Q88NJ4']] ['Q88NJ4']
(PP_1297 and PP_1299 and PP_1300 and PP_1298) or (PP_1071 and PP_1070 and PP_1068 and PP_1069)
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']]
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']] PP_1297
enz Q88NB5
[['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4']] ['Q88NB5']
(PP_1297 and PP_1299 and PP_1300 and PP_1298) or (PP_1071 and PP_1070 and PP_1068 and PP_1069)
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']]
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']] PP_1299
enz Q88NB3
[['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4']] ['Q88NB3']
(PP_1297 and PP_1299 and PP_1300 and PP_1298) or (PP_1071 and PP_1070 and PP_1068 and PP_1069)
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']]
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']] PP_1300
enz Q88NB2
[['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4']] ['Q88NB2']
(PP_1297 and PP_1299 and PP_1300 and PP_1298) or (PP_1071 and PP_1070 and PP_1068 and PP_1069)
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']]
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']] PP_1298
enz Q88NB4
[['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4'], ['Q88NB5', 'Q88NB3', 'Q88NB2', 'Q88NB4']] ['Q88NB4']
(PP_1297 and PP_1299 and PP_1300 and PP_1298) or (PP_1071 and PP_1070 and PP_1068 and PP_1069)
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']]
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']] PP_1071
enz Q88NY2
[['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4']] ['Q88NY2']
(PP_1297 and PP_1299 and PP_1300 and PP_1298) or (PP_1071 and PP_1070 and PP_1068 and PP_1069)
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']]
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']] PP_1070
enz Q88NY3
[['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4']] ['Q88NY3']
(PP_1297 and PP_1299 and PP_1300 and PP_1298) or (PP_1071 and PP_1070 and PP_1068 and PP_1069)
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']]
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']] PP_1068
enz Q88NY5
[['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4']] ['Q88NY5']
(PP_1297 and PP_1299 and PP_1300 and PP_1298) or (PP_1071 and PP_1070 and PP_1068 and PP_1069)
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']]
[['PP_1297', 'PP_1299', 'PP_1300', 'PP_1298'], ['PP_1071', 'PP_1070', 'PP_1068', 'PP_1069']] PP_1069
enz Q88NY4
[['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4'], ['Q88NY2', 'Q88NY3', 'Q88NY5', 'Q88NY4']] ['Q88NY4']
PP_0137
[['PP_0137']]
[['PP_0137']] PP_0137
enz Q88RJ2
[['Q88RJ2']] ['Q88RJ2']
PP_1645 or PP_1928 or PP_2716
[['PP_1645'], ['PP_1928'], ['PP_2716']]
[['PP_1645'], ['PP_1928'], ['PP_2716']] PP_1645
enz Q88MC8
[['Q88MC8']] ['Q88MC8']
PP_1645 or PP_1928 or PP_2716
[['PP_1645'], ['PP_1928'], ['PP_2716']]
[['PP_1645'], ['PP_1928'], ['PP_2716']] PP_1928
enz Q88LK3
[['Q88LK3']] ['Q88LK3']
PP_1645 or PP_1928 or PP_2716
[['PP_1645'], ['PP_1928'], ['PP_2716']]
[['PP_1645'], ['PP_1928'], ['PP_2716']] PP_2716
enz Q88JD3
[['Q88JD3']] ['Q88JD3']
PP_4479 and PP_4480
[['PP_4479', 'PP_4480']]
[['PP_4479', 'PP_4480']] PP_4479
enz Q88EI3
[['Q88EI3', 'Q88EI2'], ['Q88EI3', 'Q88EI2']] ['Q88EI3']
PP_4479 and PP_4480
[['PP_4479', 'PP_4480']]
[['PP_4479', 'PP_4480']] PP_4479
enz Q88EI3
[['Q88EI3', 'Q88EI2'], ['Q88EI3', 'Q88EI2']] ['Q88EI3']
PP_4479 and PP_4480
[['PP_4479', 'PP_4480']]
[['PP_4479', 'PP_4480']] PP_4479
enz Q88EI3
[['Q88EI3', 'Q88EI2'], ['Q88EI3', 'Q88EI2']] ['Q88EI3']
PP_4479 and PP_4480
[['PP_4479', 'PP_4480']]
[['PP_4479', 'PP_4480']] PP_4480
enz Q88EI2
[['Q88EI3', 'Q88EI2'], ['Q88EI3', 'Q88EI2']] ['Q88EI2']
PP_4479 and PP_4480
[['PP_4479', 'PP_4480']]
[['PP_4479', 'PP_4480']] PP_4480
enz Q88EI2
[['Q88EI3', 'Q88EI2'], ['Q88EI3', 'Q88EI2']] ['Q88EI2']
PP_4479 and PP_4480
[['PP_4479', 'PP_4480']]
[['PP_4479', 'PP_4480']] PP_4480
enz Q88EI2
[['Q88EI3', 'Q88EI2'], ['Q88EI3', 'Q88EI2']] ['Q88EI2']
PP_4862
[['PP_4862']]
[['PP_4862']] PP_4862
enz Q88DG3
[['Q88DG3']] ['Q88DG3']
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_ATPHs
enz Enzyme_ATPHs
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_ATPHs
enz Enzyme_ATPHs
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_ATPHs
enz Enzyme_ATPHs
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_ATPHs
enz Enzyme_ATPHs
PP_0965 and PP_4890
[['PP_0965', 'PP_4890']]
[['PP_0965', 'PP_4890']] PP_0965
enz Q88P87
[['Q88P87', 'Q88DD7'], ['Q88P87', 'Q88DD7']] ['Q88P87']
PP_0965 and PP_4890
[['PP_0965', 'PP_4890']]
[['PP_0965', 'PP_4890']] PP_0965
enz Q88P87
[['Q88P87', 'Q88DD7'], ['Q88P87', 'Q88DD7']] ['Q88P87']
PP_0965 and PP_4890
[['PP_0965', 'PP_4890']]
[['PP_0965', 'PP_4890']] PP_4890
enz Q88DD7
[['Q88P87', 'Q88DD7'], ['Q88P87', 'Q88DD7']] ['Q88DD7']
PP_0965 and PP_4890
[['PP_0965', 'PP_4890']]
[['PP_0965', 'PP_4890']] PP_4890
enz Q88DD7
[['Q88P87', 'Q88DD7'], ['Q88P87', 'Q88DD7']] ['Q88DD7']
(PP_5417 and PP_5418 and PP_5419) and (PP_5412 and PP_5413 and PP_5414 and PP_5415 and PP_5416) and PP_5420
[['PP_5417', 'PP_5418', 'PP_5419', 'PP_5412', 'PP_5413', 'PP_5414', 'PP_5415', 'PP_5416', 'PP_5420']]

PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_3535
enz Q88H30
[['Q88H30']] ['Q88H30']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_3535
enz Q88H30
[['Q88H30']] ['Q88H30']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_3535
enz Q88H30
[['Q88H30']] ['Q88H30']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_3535
enz Q88H30
[['Q88H30']] ['Q88H30']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_3535
enz Q88H30
[['Q88H30']] ['Q88H30']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_3535
enz Q88H30
[['Q88H30']] ['Q88H30']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_4659
enz Q88E09
[['Q88E09']] ['Q88E09']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_4659
enz Q88E09
[['Q88E09']] ['Q88E09']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_4659
enz Q88E09
[['Q88E09']] ['Q88E09']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_4659
enz Q88E09
[['Q88E09']] ['Q88E09']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_4659
enz Q88E09
[['Q88E09']] ['Q88E09']
PP_3535 or PP_4659
[['PP_3535'], ['PP_4659']]
[['PP_3535'], ['PP_4659']] PP_4659
enz Q88E09
[['Q88E09']] ['Q88E09']
PP_4993
[['PP_4993']]
[['PP_4993']] PP_4993
enz Q88D35
[['Q88D35']] ['Q88D35']
PP_4993
[['PP_4993']]
[['PP_4993']] PP_4993
enz Q88D35
[['Q88D35']] ['Q88D35']
PP_4993
[['PP_4993']]
[['PP_4993']] PP_4993
enz Q88D35
[['Q88D35']] ['Q88D35']
PP_2512 or PP_1823 or PP_3324
[['PP_2512'], ['PP_1823'], ['PP_3324']]
[['PP_2512'], ['PP_1823'], ['PP_3324']] PP_2512
enz Q88JY1
[['Q88JY1']] ['Q88JY1']
PP_2512 or PP_1823 or PP_3324
[['PP_2512'], ['PP_1823'], ['PP_3324']]
[['PP_2512'], ['PP_1823'], ['PP_3324']] PP_2512
enz Q88JY1
[['Q88JY1']] ['Q88JY1']
PP_2512 or PP_1823 or PP_3324
[['PP_2512'], ['PP_1823'], ['PP_3324']]
[['PP_2512'], ['PP_1823'], ['PP_3324']] PP_1823
enz Q88LV4
[['Q88LV4']] ['Q88LV4']
PP_2512 or PP_1823 or PP_3324
[['PP_2512'], ['PP_1823'], ['PP_3324']]
[['PP_2512'], ['PP_1823'], ['PP_3324']] PP_1823
enz Q88LV4
[['Q88LV4']] ['Q88LV4']
PP_2512 or PP_1823 or PP_3324
[['PP_2512'], ['PP_1823'], ['PP_3324']]
[['PP_2512'], ['PP_1823'], ['PP_3324']] PP_3324
enz Q88HM9
[['Q88HM9']] ['Q88HM9']
PP_2512 or PP_1823 or PP_3324
[['PP_2512'], ['PP_1823'], ['PP_3324']]
[['PP_2512'], ['PP_1823'], ['PP_3324']] PP_3324
enz Q88HM9
[['Q88HM9']] ['Q88HM9']
PP_0522 or PP_0516 or PP_3813
[['PP_0522'], ['PP_0516'], ['PP_3813']]
[['PP_0522'], ['PP_0516'], ['PP_3813']] PP_0522
enz Q88QH1
[['Q88QH1']] ['Q88QH1']
PP_0522 or PP_0516 or PP_3813
[['PP_0522'], ['PP_0516'], ['PP_3813']]
[['PP_0522'], ['PP_0516'], ['PP_3813']] PP_0522
enz Q88QH1
[['Q88QH1']] ['Q88QH1']
PP_0522 or PP_0516 or PP_3813
[['PP_0522'], ['PP_0516'], ['PP_3813']]
[['PP_0522'], ['PP_0516'], ['PP_3813']] PP_0516
enz Q88QH7
[['Q88QH7']] ['Q88QH7']
PP_0522 or PP_0516 or PP_3813
[['PP_0522'], ['PP_0516'], ['PP_3813']]
[['PP_0522'], ['PP_0516'], ['PP_3813']] PP_0516
enz Q88QH7
[['Q88QH7']] ['Q88QH7']
PP_0522 or PP_0516 or PP_3813
[['PP_0522'], ['PP_0516'], ['PP_3813']]
[['PP_0522'], ['PP_0516'], ['PP_3813']] PP_3813
enz Q88GB1
[['Q88GB1']] ['Q88GB1']
PP_0522 or PP_0516 or PP_3813
[['PP_0522'], ['PP_0516'], ['PP_3813']]
[['PP_0522'], ['PP_0516'], ['PP_3813']] PP_3813
enz Q88GB1
[['Q88GB1']] ['Q88GB1']
PP_5216
[['PP_5216']]
[['PP_5216']] PP_5216
enz Q88CG5
[['Q88CG5']] ['Q88CG5']
PP_5216
[['PP_5216']]
[['PP_5216']] PP_5216
enz Q88CG5
[['Q88CG5']] ['Q88CG5']
PP_5216
[['PP_5216']]
[['PP_5216']] PP_5216
enz Q88CG5
[['Q88CG5']] ['Q88CG5']
PP_5216
[['PP_5216']]
[['PP_5216']] PP_5216
enz Q88CG5
[['Q88CG5']] ['Q88CG5']
PP_5216
[['PP_5216']]
[['PP_5216']] PP_5216
enz Q88CG5
[['Q88CG5']] ['Q88CG5']
PP_5216
[['PP_5216']]
[['PP_5216']] PP_5216
enz Q88CG5
[['Q88CG5']] ['Q88CG5']
PP_5216
[['PP_5216']]
[['PP_5216']] PP_5216
enz Q88CG5
[['Q88CG5']] ['Q88CG5']
PP_5216
[['PP_5216']]
[['PP_5216']] PP_5216
enz Q88CG5
[['Q88CG5']] ['Q88CG5']
PP_1656
[['PP_1656']]
[['PP_1656']] PP_1656
enz Q88MB8
[['Q88MB8']] ['Q88MB8']
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_GTPHs
enz Enzyme_GTPHs
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_GTPHs
enz Enzyme_GTPHs
PP_0343
[['PP_0343']]
[['PP_0343']] PP_0343
enz Q88QZ1
[['Q88QZ1']] ['Q88QZ1']
PP_4943
[['PP_4943']]
[['PP_4943']] PP_4943
enz Q88D84
[['Q88D84']] ['Q88D84']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_4405
enz Q88EP8
[['Q88EP8']] ['Q88EP8']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_4405
enz Q88EP8
[['Q88EP8']] ['Q88EP8']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_0165
enz Q88RG5
[['Q88RG5']] ['Q88RG5']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_0165
enz Q88RG5
[['Q88RG5']] ['Q88RG5']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_3581
enz Q88GY4
[['Q88GY4']] ['Q88GY4']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_3581
enz Q88GY4
[['Q88GY4']] ['Q88GY4']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_1494
enz Q88MS4
[['Q88MS4']] ['Q88MS4']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_1494
enz Q88MS4
[['Q88MS4']] ['Q88MS4']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_0129
enz Q88RK0
[['Q88RK0']] ['Q88RK0']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_0129
enz Q88RK0
[['Q88RK0']] ['Q88RK0']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_4670
enz Q88DZ8
[['Q88DZ8']] ['Q88DZ8']
PP_4405 or PP_0165 or PP_3581 or PP_1494 or PP_0129 or PP_4670
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']]
[['PP_4405'], ['PP_0165'], ['PP_3581'], ['PP_1494'], ['PP_0129'], ['PP_4670']] PP_4670
enz Q88DZ8
[['Q88DZ8']] ['Q88DZ8']
PP_4281
[['PP_4281']]
[['PP_4281']] PP_4281
enz Q88F18
[['Q88F18']] ['Q88F18']
PP_4281
[['PP_4281']]
[['PP_4281']] PP_4281
enz Q88F18
[['Q88F18']] ['Q88F18']
PP_4281
[['PP_4281']]
[['PP_4281']] PP_4281
enz Q88F18
[['Q88F18']] ['Q88F18']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_0747
[['PP_0747']]
[['PP_0747']] PP_0747
enz Q88PV1
[['Q88PV1']] ['Q88PV1']
PP_4290 or PP_4284
[['PP_4290'], ['PP_4284']]
[['PP_4290'], ['PP_4284']] PP_4290
enz Q88F10
[['Q88F10']] ['Q88F10']
PP_4290 or PP_4284
[['PP_4290'], ['PP_4284']]
[['PP_4290'], ['PP_4284']] PP_4284
enz Q88F15
[['Q88F15']] ['Q88F15']
PP_4523
[['PP_4523']]
[['PP_4523']] PP_4523
enz Q88EE2
[['Q88EE2']] ['Q88EE2']
PP_4523
[['PP_4523']]
[['PP_4523']] PP_4523
enz Q88EE2
[['Q88EE2']] ['Q88EE2']
PP_4523
[['PP_4523']]
[['PP_4523']] PP_4523
enz Q88EE2
[['Q88EE2']] ['Q88EE2']
PP_0100
[['PP_0100']]
[['PP_0100']] PP_0100
enz Q88RM9
[['Q88RM9']] ['Q88RM9']
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_H2CO3D2
enz Enzyme_H2CO3D2
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_H2CO3D2
enz Enzyme_H2CO3D2
PP_4282 or PP_s0001
[['PP_4282'], ['PP_s0001']]
[['PP_4282'], ['PP_s0001']] PP_4282
enz Q88F17
[['Q88F17']] ['Q88F17']
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_H2SO
enz Enzyme_H2SO
PP_s0001
[['PP_s0001']]
[['PP_s0001']] Gene_H2SO
enz Enzyme_H2SO
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136
[['PP_2136']]
[['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214 or PP_3755
[['PP_2136'], ['PP_2214'], ['PP_3755']]
[['PP_2136'], ['PP_2214'], ['PP_3755']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214 or PP_3755
[['PP_2136'], ['PP_2214'], ['PP_3755']]
[['PP_2136'], ['PP_2214'], ['PP_3755']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214 or PP_3755
[['PP_2136'], ['PP_2214'], ['PP_3755']]
[['PP_2136'], ['PP_2214'], ['PP_3755']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214 or PP_3755
[['PP_2136'], ['PP_2214'], ['PP_3755']]
[['PP_2136'], ['PP_2214'], ['PP_3755']] PP_3755
enz Q88GG9
[['Q88GG9']] ['Q88GG9']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2214 or PP_2136
[['PP_2214'], ['PP_2136']]
[['PP_2214'], ['PP_2136']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2136
enz Q88L02
[['Q88L02']] ['Q88L02']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214
[['PP_2136'], ['PP_2214']]
[['PP_2136'], ['PP_2214']] PP_2214
enz Q88KS5
[['Q88KS5']] ['Q88KS5']
PP_2136 or PP_2214

PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5004
[['PP_5004']]
[['PP_5004']] PP_5004
enz Q88D24
[['Q88D24']] ['Q88D24']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5005 or PP_5003
[['PP_5005'], ['PP_5003']]
[['PP_5005'], ['PP_5003']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5005 or PP_5003
[['PP_5005'], ['PP_5003']]
[['PP_5005'], ['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5005 or PP_5003
[['PP_5005'], ['PP_5003']]
[['PP_5005'], ['PP_5003']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5005 or PP_5003
[['PP_5005'], ['PP_5003']]
[['PP_5005'], ['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5005 or PP_5003
[['PP_5005'], ['PP_5003']]
[['PP_5005'], ['PP_5003']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5005 or PP_5003
[['PP_5005'], ['PP_5003']]
[['PP_5005'], ['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5005 or PP_5003
[['PP_5005'], ['PP_5003']]
[['PP_5005'], ['PP_5003']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5005 or PP_5003
[['PP_5005'], ['PP_5003']]
[['PP_5005'], ['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003
[['PP_5003']]
[['PP_5003']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5003
enz Q88D25
[['Q88D25']] ['Q88D25']
PP_5003 or PP_5005
[['PP_5003'], ['PP_5005']]
[['PP_5003'], ['PP_5005']] PP_5005
enz Q88D23
[['Q88D23']] ['Q88D23']
PP_4689 and PP_4687 and PP_4688 and PP_4686
[['PP_4689', 'PP_4687', 'PP_4688', 'PP_4686']]
[['PP_4689', 'PP_4687', 'PP_4688', 'PP_4686']] PP_4689
enz Q88DX9
[['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2']] ['Q88DX9']
PP_4689 and PP_4687 and PP_4688 and PP_4686
[['PP_4689', 'PP_4687', 'PP_4688', 'PP_4686']]
[['PP_4689', 'PP_4687', 'PP_4688', 'PP_4686']] PP_4687
enz Q88DY1
[['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2']] ['Q88DY1']
PP_4689 and PP_4687 and PP_4688 and PP_4686
[['PP_4689', 'PP_4687', 'PP_4688', 'PP_4686']]
[['PP_4689', 'PP_4687', 'PP_4688', 'PP_4686']] PP_4688
enz Q88DY0
[['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2']] ['Q88DY0']
PP_4689 and PP_4687 and PP_4688 and PP_4686
[['PP_4689', 'PP_4687', 'PP_4688', 'PP_4686']]
[['PP_4689', 'PP_4687', 'PP_4688', 'PP_4686']] PP_4686
enz Q88DY2
[['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2'], ['Q88DX9', 'Q88DY1', 'Q88DY0', 'Q88DY2']] ['Q88DY2']
PP_4327 and PP_4326 and PP_4325
[['PP_4327', 'PP_4326', 'PP_4325']]
[['PP_4327', 'PP_4326', 'PP_4325']] PP_4327
enz Q88EX5
[['Q88EX5', 'Q88EX6', 'Q88EX7'], ['Q88EX5', 'Q88EX6', 'Q88EX7'], ['Q88EX5', 'Q88EX6', 'Q88EX7']] ['Q88EX5']
PP_4327 and PP_4326 and PP_4325
[['PP_4327', 'PP_4326', 'PP_4325']]
[['PP_4327', 'PP_4326', 'PP_4325']] PP_4326
enz Q88EX6
[['Q88EX5', 'Q88EX6', 'Q88EX7'], ['Q88EX5', 'Q88EX6', 'Q88EX7'], ['Q88EX5', 'Q88EX6', 'Q88EX7']] ['Q88EX6']
PP_4327 and PP_4326 and PP_4325
[['PP_4327', 'PP_4326', 'PP_4325']]
[['PP_4327', 'PP_4326', 'PP_4325']] PP_4325
enz Q88EX7
[['Q88EX5', 'Q88EX6', 'Q88EX7'], ['Q88EX5', 'Q88EX6', 'Q88EX7'], ['Q88EX5', 'Q88EX6', 'Q88EX7']] ['Q88EX7']
PP_5270 or PP_4434 or PP_2246
[['PP_5270'], ['PP_4434'], ['PP_2246']]
[['PP_5270'], ['PP_4434'], ['PP_2246']] PP_5270
enz Q88CB1
[['Q88CB1']] ['Q88CB1']
PP_5270 or PP_4434 or PP_2246
[['PP_5270'], ['PP_4434'], ['PP_2246']]
[['PP_5270'], ['PP_4434'], ['PP_2246']] PP_4434
enz Q88EM0
[['Q88EM0']] ['Q88EM0']
PP_5270 or PP_4434 or PP_2246
[['PP_5270'], ['PP_4434'], ['PP_2246']]
[['PP_5270'], ['PP_4434'], ['PP_2246']] PP_2246
enz Q88KP4
[['Q88KP4']] ['Q88KP4']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_1972
enz Q88LG1
[['Q88LG1']] ['Q88LG1']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7
[['Q88GX7']] ['Q88GX7']
PP_1972 or PP_3590
[['PP_1972'], ['PP_3590']]
[['PP_1972'], ['PP_3590']] PP_3590
enz Q88GX7

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,Protein names,Length,molMass,Rhea ID,kcat_values,direction
6987,13PPDH2_1,NaN,NaN,NaN,"[C00080, [C05999, C00424], C00005]","[C02457, C00006]",NaN,PP_2492,[PP_2492],Q88K01,"Alcohol dehydrogenase, NAD(P)-dependent (EC 1....",385.0,42414.0,NaN,11.0000,f
12,1P2CBXLR,NaN,NaN,NaN,[],"[C00006, [C00148, C16435]]",NaN,PP_3591,[PP_3591],Q88GX6,Delta 1-piperideine-2-carboxylate reductase (E...,332.0,35143.0,NaN,11.0000,f
13,1PPDCRc,R02203,"[12525, 12526, 12527, 12524]",MNXR94711,"[C04092, C00080, C00005]","[C00408, C00006]",1.5.1.1,PP_3591,[PP_3591],Q88GX6,Delta 1-piperideine-2-carboxylate reductase (E...,332.0,35143.0,NaN,86.6017,f
14,1PPDCRc,R02203,"[12525, 12526, 12527, 12524]",MNXR94711,"[C04092, C00080, C00005]","[C00408, C00006]",1.5.1.1,PP_3591,[PP_3591],Q88GX6,Delta 1-piperideine-2-carboxylate reductase (E...,332.0,35143.0,NaN,86.6017,f
15,1PPDCRc,R02203,"[12525, 12526, 12527, 12524]",MNXR94711,"[C04092, C00080, C00005]","[C00408, C00006]",1.5.1.1,PP_3591,[PP_3591],Q88GX6,Delta 1-piperideine-2-carboxylate reductase (E...,332.0,35143.0,NaN,1422.1744,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6855,pentso3abcpp,NaN,NaN,MNXR105297,[],[],NaN,(PP_0237 and PP_0240 and PP_0239) or (PP_0233 ...,"[PP_0237, PP_0240, PP_0239]",Q88R96_Q88R93_Q88R94,Aliphatic sulfonates import ATP-binding protei...,270.0,29370.0,NaN,11.0000,f
6856,pentso3abcpp,NaN,NaN,MNXR105297,[],[],NaN,(PP_0237 and PP_0240 and PP_0239) or (PP_0233 ...,"[PP_0237, PP_0240, PP_0239]",Q88R96_Q88R93_Q88R94,Aliphatic sulfonate ABC transporter-permease s...,265.0,28665.0,NaN,11.0000,f
6857,pentso3abcpp,NaN,NaN,MNXR105297,[],[],NaN,(PP_0237 and PP_0240 and PP_0239) or (PP_0233 ...,"[PP_0233, PP_0232, PP_0231]",Q88RA0_Q88RA1_Q88RA2,Taurine ABC transporter periplasmic binding su...,323.0,34324.0,NaN,11.0000,f
6858,pentso3abcpp,NaN,NaN,MNXR105297,[],[],NaN,(PP_0237 and PP_0240 and PP_0239) or (PP_0233 ...,"[PP_0233, PP_0232, PP_0231]",Q88RA0_Q88RA1_Q88RA2,Taurine import ATP-binding protein TauB (EC 7....,262.0,28444.0,RHEA:14613,11.0000,f
6859,pentso3abcpp,NaN,NaN,MNXR105297,[],[],NaN,(PP_0237 and PP_0240 and PP_0239) or (PP_0233 ...,"[PP_0233, PP_0232, PP_0231]",Q88RA0_Q88RA1_Q88RA2,Taurine ABC transporter permease subunit (EC 3...,279.0,29859.0,NaN,11.0000,f

In [22]:
#save the dataframe
# eco_enzymes_mapped = eco_enzymes_mapped.drop_duplicates(subset = ['rxn_id', 'gene', 'direction'],
#                                                        ignore_index=True)
eco_enzymes_mapped.to_excel(AE_OUTPUT_FILE_PATH)

### 7. Save the dataframe to the proper format for building PAMs

In [31]:
other_sheets = pd.read_excel(PAM_DATA_FILE_PATH, sheet_name = None)

# Save it to a new excel file
with pd.ExcelWriter(OUTPUT_FILE_PATH) as writer:
    eco_enzymes_mapped.to_excel(writer, sheet_name='ActiveEnzymes', index=False)
    for sheet_name, sheet in other_sheets.items():
        if sheet_name != 'ActiveEnzymes':
            sheet.to_excel(writer, sheet_name = sheet_name, index=False)