# Initializing kcat values for PAMparametrizer

In this notebook, we give an overview of how an initial set of turnover number can be obtained. To enable this, we use multiple databases to map kcat values obtained from machine learning (from the [GotEnzymes](https://metabolicatlas.org/gotenzymes) database) to the proteins and reactions in the model using the gene-protein-reaction associations.

Before we start, we have to set up all the package and files required. Adjust the filenames and paths as desired. Importantly, make sure to **adjust the regular expression in the cell below** in order to find the gene names associated with the organism you want to model.

In [1]:
import pandas as pd
import os
from cobra.io import load_json_model, read_sbml_model
import matplotlib.pyplot as plt
import re
import numpy as np
import datetime

if os.path.split(os.getcwd())[1]=='i1_preprocessing':
    os.chdir('../..')
    
from PAModelpy.utils.pam_generation import merge_enzyme_complexes, get_protein_gene_mapping, _parse_gpr


DEFAULT_PROT_MW = 39959.4825 #g/mol
DEFAULT_KCAT =  13.7 #/s median value from BRENDA

PAM_DATA_FILE_PATH = os.path.join('Data', 'proteinAllocationModel_iML1515_EnzymaticData_new.xls')
UNIPROT_FILE_PATH = os.path.join('Data', 'Databases','uniprotkb_cglutamicumATCC13032_250124.xlsx')
NCBI_FILE_PATH = os.path.join('Data','Cglutanicum_phenotypes','NCBI_genes_corynglutatcc13032_250207.tsv')
GOTENZYMES_FILE_PATH = os.path.join('Data','Databases', 'GotEnzymes_cgl_250124.json')
MODEL_FILE_PATH = os.path.join('Models', 'iCGB21FR_annotated.xml')

Loading PAModelpy modules version 0.0.4.6

In [2]:
#output file path
# Create a datetime object for the current date
current_date = datetime.datetime.now()
# Format the date as yymmdd
formatted_date = current_date.strftime('%y%m%d')

OUTPUT_FILE_PATH = os.path.join('Results', '1_preprocessing', f'proteinAllocationModel_iCGB21FR_EnzymaticData_{formatted_date}.xlsx')
AE_OUTPUT_FILE_PATH = os.path.join('Results', '1_preprocessing', f'{formatted_date}_cgl_ActiveEnzymeInformation_GotEnzymes.xlsx')

Relatively complicated regex because of complex gene names

1. WP_\d+_\d+: Matches identifiers starting with WP_ followed by digits (\d+), an underscore, and more digits.
2. |: Alternation operator to separate different patterns.
3. lcl_NC_\d+_\d+_prot_: Matches strings starting with lcl_NC_, followed by digits, an underscore, more digits, _prot_, and then:

    - WP_\d+_\d+_\d+: Matches WP_ identifiers with an additional _ and digits at the end.
    - |\d+: Matches a plain numeric sequence following _prot_.

4. |: Alternation operator for the next part.
5. cgl\d{4}: Matches strings starting with cgl followed by exactly 4 digits.

In [3]:
#You need to adjust this to find the geneid/locustag for your microbe
locustag_regex =r'(?:WP_\d+_\d+|lcl_NC_\d+_\d+_prot_(?:WP_\d+_\d+_\d+|\d+)|[cC]gl\d{4}|[cC]g\d{4})'

## 0. Download information from different databases
1. **Metabolic model stoichiometries and reactions: [BioModels](https://www.ebi.ac.uk/biomodels/)**
- Get your model! Or use your own reaction identifiers
- In this example we will use the iCGB21FR model for [*Corynebacterium glutamicum* ATCC 13032](https://www.ebi.ac.uk/biomodels/MODEL2102050001#Overview)

2. **Turnover numbers: [GotEnzymes](https://metabolicatlas.org/gotenzymes)**
- Go to the [API of the Metabolic Atlas](https://metabolicatlas.org/api/v2/#/GotEnzymes/gotEnzymes)
- Use the `GET\gotenzymes\enzymes?` functionality, click `Try it out`
- Here we filled in `cgl` (*C. glutanicum* ATCC 13032) for `organism` and `10000` for `pagination[pageSize]`. The rest was left empty
- Click execute and a json file with all the information will be downloaded

3. **Gene-Protein-Reaction relations: [UniprotKB](https://www.uniprot.org/)**
- Go to the [Uniprot knowledge base](https://www.uniprot.org/) and used advanced search to query for your organism. For *C. glutanicum* we used [this](https://www.uniprot.org/uniprotkb?query=(taxonomy_id:196627)) webpage
- Click download, select `format`:`Excel` and select the following: 
    - `Uniprot Data -> Names & Taxonomy`: `Gene Names`
    - `Uniprot Data -> Sequences`: `length`, `mass`
    - `Uniprot Data -> Function`: `RheaID`
- Download the resulting Excel file

4. **NCBI gene id to KEGG gene id mapping**: [NCBI database](https://www.ncbi.nlm.nih.gov/)
- The model identifiers for this model are in NCBI format, but we need the KEGG locus tag ids to map the genes to the corresponding Uniprot ids. Therefore, we use the mapping provided by NCBI.
- Go to the NCBI gene list for *C. glutanicum* on [NCBI genes](https://www.ncbi.nlm.nih.gov/gene/?term=Corynebacterium+glutamicum+ATCC+13032)
- On the top left click `send to`, select `file` and `text`

## 1. Get information from the model

In the metabolic model itself is already quite some information stored. In order to obtain up-to-date information on the enzymes related to the reaction, we will need to obtain the kegg reaction ID, the reactants, the product and the gene-protein relation.

In [27]:
def create_id_mapper_from_model(model):
    expand=False

    #make a id mapping and create a mapping dataframe
    id_mapper_df = pd.DataFrame(columns = ['rxn_id', 'kegg_id', 'rhea_id', 'Reactants','Products','EC', 'GPR'])
    for rxn in model.reactions:
        #skip transport reactions and ATP maintenance requirement
        if 'ex' in rxn.id or 'EX' in rxn.id or rxn.id == 'ATPM':
            continue
        to_append= []   

        to_append.append(rxn.id)
        #not all reactions are annotated with a KEGG ID in the model
        try: 
            to_append.append(rxn.annotation['kegg.reaction'])
        except:
            to_append.append(np.nan)
        try: 
            to_append.append(rxn.annotation['rhea'])
        except:
            to_append.append(np.nan)
        try:
            to_append.append([reac.annotation['kegg.compound'] for reac in rxn.reactants])
        except:
            to_append.append([])
        try: 
            to_append.append([prod.annotation['kegg.compound'] for prod in rxn.products])
        except:
            to_append.append([])
        if 'ec-code' in rxn.annotation.keys():
            #if there are multiple enzymes make seperate lists
            if isinstance(rxn.annotation['ec-code'], list) and expand:
                info = to_append.copy()
                for i in range(len(rxn.annotation['ec-code'])):
                    #make a new row for each enzyme by copying the previous information
                    info = to_append.copy()
                    ec= rxn.annotation['ec-code'][i]
                    info.append(ec)
                    #add gpr
                    info.append(rxn.gene_reaction_rule)
                    #add to df
                    id_mapper_df.loc[len(id_mapper_df)] = info
            else:
                to_append.append(rxn.annotation['ec-code'])
                to_append.append(rxn.gene_reaction_rule)
                id_mapper_df.loc[len(id_mapper_df)] = to_append
        else:
            to_append.append(np.nan)
            #ignore entries without enzyme and gpr relation
            if rxn.gene_reaction_rule =='':
                continue
            else:
                to_append.append(rxn.gene_reaction_rule)
            id_mapper_df.loc[len(id_mapper_df)] = to_append

    #remove entries without GRP relation or Ec number


    print('Number of reactions in the mapping dataframe: ',len(id_mapper_df))
    print('Number of reactions mapped to KEGG identifier: ', len(id_mapper_df.kegg_id.dropna()))
    return id_mapper_df

def create_gene_id_mapper_df(model):
    mapper_df = pd.DataFrame(columns = ['rxn_id', 'gene_id', 'uniprot_id', 'kegg_gene', 'NCBI_protein'])
    for rxn in model.reactions:
        for gene in rxn.genes:
            row = [rxn.id, gene.id]
            for dbxref in ['uniprot', 'kegg.genes','ncbiprotein']:
                if dbxref in gene.annotation:
                    row.append(gene.annotation[dbxref])
                else:
                    row.append(np.nan)
            mapper_df.loc[len(mapper_df)] = row
            
    #need to split of cgb: in front of kegg.gene id
    mapper_df['kegg_gene'] = mapper_df['kegg_gene'].apply(
    lambda gene: gene.split(':')[1] if isinstance(gene, str) and ':' in gene else gene
    )    
    print('Number of genes in the mapping dataframe: ',len(mapper_df))
    print('Number of genes mapped to KEGG identifier: ', len(mapper_df.kegg_gene.dropna()))
    print('Number of genes mapped to uniprot identifier: ', len(mapper_df.uniprot_id.dropna()))
    return mapper_df
            

print('mapping the ids from the iCGB21FR model')
model =read_sbml_model(MODEL_FILE_PATH)
id_mapper = create_id_mapper_from_model(model)
print('\nmapping gene ids')
gene_id_mapper = create_gene_id_mapper_df(model)
id_mapper

mapping the ids from the iCGB21FR model
Number of reactions in the mapping dataframe:  1152
Number of reactions mapped to KEGG identifier:  531

mapping gene ids
Number of genes in the mapping dataframe:  1659
Number of genes mapped to KEGG identifier:  1516
Number of genes mapped to uniprot identifier:  1595

,rxn_id,kegg_id,rhea_id,Reactants,Products,EC,GPR
0,2AGPEAT160,NaN,NaN,[],[],2.3.1.40,
1,2AGPEAT180,NaN,NaN,[],[],2.3.1.40,
2,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or lc...
3,3HAD140,R04568,NaN,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[4.2.1.61, 2.3.1.86, 2.3.1.-, 2.3.1.85, 4.2.1.59]",
4,3MBt2pp,NaN,NaN,"[C00080, C08262]","[C08262, C00080]",NaN,lcl_NC_006958_1_prot_WP_011013917_1_810
...,...,...,...,...,...,...,...
1147,Ca2t2,NaN,NaN,"[C00076, C00080]","[C00076, C00080]",NaN,WP_011014107_1
1148,CAT,R00009,"[20309, 20310, 20311, 20312]","[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[1.11.1.21, 1.11.1.6]",WP_011013509_1
1149,SUCDi,NaN,"[29187, 29188, 29189, 29190]",[],[],NaN,WP_011013606_1 and WP_011013607_1
1150,PRFGS_1,R04463,"[17129, 17131, 17130, 17132]","[[C00002, C00002;D08646], C04376, [C00064, C00...","[[C00008, C00008;G11113], C04640, [C00025, C00...",6.3.5.3,lcl_NC_006958_1_prot_WP_003854010_1_2470
1151,PYRt,NaN,NaN,[C00022],[C00022],NaN,WP_011014733_1

In [28]:
gene_id_mapper

,rxn_id,gene_id,uniprot_id,kegg_gene,NCBI_protein
0,2MAHMP,lcl_NC_006958_1_prot_WP_011015468_1_2761,Q8NLP8,cg3199,WP_011015468.1
1,2MAHMP,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,NaN,WP_003855288.1
2,3MBt2pp,lcl_NC_006958_1_prot_WP_011013917_1_810,Q8NS49,cg0953,WP_011013917.1
3,3MBt4pp,lcl_NC_006958_1_prot_WP_011013917_1_810,Q8NS49,cg0953,WP_011013917.1
4,3OXCOAT,lcl_NC_006958_1_prot_WP_003859251_1_2275,Q8NN21,cg2625,WP_003859251.1
...,...,...,...,...,...
1654,SUCDi,WP_011013607_1,NaN,NaN,NaN
1655,SUCDi,WP_011013606_1,NaN,NaN,NaN
1656,PRFGS_1,lcl_NC_006958_1_prot_WP_003854010_1_2470,Q8NMI3,cg2865,WP_003854010.1
1657,PYRt,WP_011014733_1,NaN,NaN,NaN
1658,L_LACtex,WP_011014733_1,NaN,NaN,NaN

### Map the NCBI gene names to KEGG gene names

In the iCGB21FR model, the gene names are by default the ncbi gene names. To map the gene-protein-reaction associations to the corresponding uniprot peptide identifiers, we need to map the model gene names to the kegg gene names.

In [33]:
gene_mapper = gene_id_mapper[['gene_id', 'kegg_gene']].set_index('gene_id').to_dict()['kegg_gene']
gene_mapper

{'lcl_NC_006958_1_prot_WP_011015468_1_2761': 'cg3199',
 'lcl_NC_006958_1_prot_WP_003855288_1_2949': nan,
 'lcl_NC_006958_1_prot_WP_011013917_1_810': 'cg0953',
 'lcl_NC_006958_1_prot_WP_003859251_1_2275': 'cg2625',
 'lcl_NC_006958_1_prot_WP_011015386_1_2669': 'cg3096',
 'lcl_NC_006958_1_prot_WP_003859243_1_2278': 'cg2628',
 'lcl_NC_006958_1_prot_WP_011265680_1_1044': 'cg1226',
 'lcl_NC_006958_1_prot_WP_003857140_1_156': 'cg0196',
 'lcl_NC_006958_1_prot_WP_011014966_1_2112': nan,
 'lcl_NC_006958_1_prot_WP_011015481_1_2778': 'cg3216',
 'lcl_NC_006958_1_prot_WP_003859586_1_2138': 'cg2473',
 'lcl_NC_006958_1_prot_WP_011013682_1_467': 'cg0566',
 'lcl_NC_006958_1_prot_WP_011015122_1_2318': 'cg2680',
 'lcl_NC_006958_1_prot_WP_011013720_1_527': 'cg0637',
 'lcl_NC_006958_1_prot_WP_011013661_1_441': 'cg0535',
 'lcl_NC_006958_1_prot_WP_011015295_1_2545': 'cg2953',
 'lcl_NC_006958_1_prot_WP_011014125_1_1074': 'cg1257',
 'lcl_NC_006958_1_prot_WP_080558827_1_1134': 'cg1321',
 'lcl_NC_006958_1_prot_WP_011013915_1_808': 'cg0951',
 'lcl_NC_006958_1_prot_WP_003863615_1_684': 'cg0811',
 'lcl_NC_006958_1_prot_WP_011013744_1_562': 'cg0675',
 'lcl_NC_006958_1_prot_WP_011014763_1_1832': 'cg2117',
 'lcl_NC_006958_1_prot_WP_003858695_1_1357': 'cg1582',
 'lcl_NC_006958_1_prot_WP_011014333_1_1356': 'cg1581',
 'lcl_NC_006958_1_prot_WP_011013388_1_98': 'cg0127',
 'lcl_NC_006958_1_prot_WP_003853648_1_2634': 'cg3054',
 'lcl_NC_006958_1_prot_WP_003862874_1_2627': 'cg3047',
 'lcl_NC_006958_1_prot_WP_011014246_1_1234': 'cg1435',
 'lcl_NC_006958_1_prot_WP_006286979_1_1235': 'cg1436',
 'lcl_NC_006958_1_prot_WP_011014050_1_985': 'cg1153',
 'lcl_NC_006958_1_prot_WP_011015336_1_2602': 'cg3021',
 'lcl_NC_006958_1_prot_WP_003862306_1_1499': nan,
 'lcl_NC_006958_1_prot_WP_011014334_1_1358': 'cg1583',
 'lcl_NC_006958_1_prot_WP_011015298_1_2550': 'cg2958',
 'lcl_NC_006958_1_prot_WP_003855103_1_2863': 'cg3321',
 'lcl_NC_006958_1_prot_WP_004567959_1_2906': 'cg3367',
 'lcl_NC_006958_1_prot_WP_011013632_1_396': 'cg0486',
 'lcl_NC_006958_1_prot_WP_011015228_1_2459': 'cg2851',
 'lcl_NC_006958_1_prot_WP_011265665_1_967': 'cg1134',
 'lcl_NC_006958_1_prot_WP_011265630_1_801': nan,
 'lcl_NC_006958_1_prot_WP_003854403_1_537': 'cg0648',
 'lcl_NC_006958_1_prot_WP_020948500_1_308': nan,
 'lcl_NC_006958_1_prot_WP_003856253_1_1400': 'cg1630',
 'lcl_NC_006958_1_prot_WP_003859635_1_2107': 'cg2432',
 'lcl_NC_006958_1_prot_WP_011014349_1_1378': 'cg1607',
 'lcl_NC_006958_1_prot_WP_003854931_1_1118': 'cg1303',
 'lcl_NC_006958_1_prot_WP_011014097_1_1037': 'cg1218',
 'lcl_NC_006958_1_prot_WP_011014514_1_1607': 'cg1862',
 'lcl_NC_006958_1_prot_WP_011013584_1_339': 'cg0414',
 'lcl_NC_006958_1_prot_WP_011015403_1_2686': 'cg3115',
 'lcl_NC_006958_1_prot_WP_003862775_1_2685': 'cg3114',
 'lcl_NC_006958_1_prot_WP_011015238_1_2477': nan,
 'lcl_NC_006958_1_prot_WP_011015361_1_2640': 'cg3063',
 'lcl_NC_006958_1_prot_WP_011265984_1_2523': 'cg2929',
 'lcl_NC_006958_1_prot_WP_011014941_1_2077': 'cg2398',
 'lcl_NC_006958_1_prot_WP_003858698_1_1355': 'cg1580',
 'lcl_NC_006958_1_prot_WP_003858195_1_727': 'cg0860',
 'lcl_NC_006958_1_prot_WP_011015392_1_2675': 'cg3102',
 'lcl_NC_006958_1_prot_WP_011014273_1_1265': 'cg1476',
 'lcl_NC_006958_1_prot_WP_011265967_1_2441': 'cg2833',
 'lcl_NC_006958_1_prot_WP_011013935_1_837': 'cg0984',
 'lcl_NC_006958_1_prot_WP_011015145_1_2346': 'cg2714',
 'lcl_NC_006958_1_prot_WP_003858249_1_691': 'cg0820',
 'lcl_NC_006958_1_prot_WP_003863574_1_721': 'cg0854',
 'lcl_NC_006958_1_prot_WP_011265608_1_688': 'cg0816',
 'lcl_NC_006958_1_prot_WP_011014958_1_2098': 'cg2421',
 'lcl_NC_006958_1_prot_WP_042383473_1_2879': 'cg3339',
 'lcl_NC_006958_1_prot_WP_011014842_1_1941': 'cg2243',
 'lcl_NC_006958_1_prot_WP_003857230_1_111': 'cg0144',
 'lcl_NC_006958_1_prot_WP_011015136_1_2334': 'cg2700',
 'lcl_NC_006958_1_prot_WP_011014850_1_1952': 'cg2256',
 'lcl_NC_006958_1_prot_WP_003856680_1_904': 'cg1062',
 'lcl_NC_006958_1_prot_WP_011015284_1_2532': 'cg2940',
 'lcl_NC_006958_1_prot_WP_011015039_1_2205': 'cg2551',
 'lcl_NC_006958_1_prot_WP_003857497_1_1889': 'cg2182',
 'lcl_NC_006958_1_prot_WP_003853884_1_2530': 'cg2938',
 'lcl_NC_006958_1_prot_WP_011265986_1_2531': 'cg2939',
 'lcl_NC_006958_1_prot_WP_003863669_1_2314': 'cg2676',
 'lcl_NC_006958_1_prot_WP_011013810_1_657': nan,
 'lcl_NC_006958_1_prot_WP_011014285_1_1278': 'cg1493',
 'lcl_NC_006958_1_prot_WP_011013748_1_567': 'cg0681',
 'lcl_NC_006958_1_prot_WP_080558826_1_458': 'cg0555',
 'lcl_NC_006958_1_prot_WP_003863416_1_205': 'cg0254',
 'lcl_NC_006958_1_prot_WP_011014123_1_1070': 'cg1253',
 'lcl_NC_006958_1_prot_WP_011015597_1_2920': 'cg3386',
 'lcl_NC_006958_1_prot_WP_003858893_1_101': 'cg0131',
 'lcl_NC_006958_1_prot_WP_011015397_1_2680': 'cg3107',
 'lcl_NC_006958_1_prot_WP_011014164_1_1124': 'cg1310',
 'lcl_NC_006958_1_prot_WP_011013571_1_326': 'cg0400',
 'lcl_NC_006958_1_prot_WP_003863269_1_315': 'cg0387',
 'lcl_NC_006958_1_prot_WP_011265946_1_2345': 'cg2713',
 'lcl_NC_006958_1_prot_WP_011013705_1_507': 'cg0612',
 'lcl_NC_006958_1_prot_WP_011014239_1_1225': 'cg1423',
 'lcl_NC_006958_1_prot_WP_011265932_1_2242': 'cg2591',
 'lcl_NC_006958_1_prot_WP_011015019_1_2181': 'cg2523',
 'lcl_NC_006958_1_prot_WP_011015278_1_2526': 'cg2933',
 'lcl_NC_006958_1_prot_WP_011013674_1_459': 'cg0556',
 'lcl_NC_006958_1_prot_WP_011013978_1_898': 'cg1055',
 'lcl_NC_006958_1_prot_WP_011013386_1_96': 'cg0124',
 'lcl_NC_006958_1_prot_WP_011265897_1_2096': nan,
 'lcl_NC_006958_1_prot_WP_011015108_1_2305': 'cg2662',
 'lcl_NC_006958_1_prot_WP_011013948_1_864': 'cg1012',
 'lcl_NC_006958_1_prot_WP_003855178_1_2900': 'cg3361',
 'lcl_NC_006958_1_prot_WP_003855176_1_2899': 'cg3360',
 'lcl_NC_006958_1_prot_WP_011015581_1_2898': 'cg3359',
 'lcl_NC_006958_1_prot_WP_011015310_1_2562': 'cg2974',
 'lcl_NC_006958_1_prot_WP_003856367_1_1960': 'cg2266',
 'lcl_NC_006958_1_prot_WP_011014736_1_1795': 'cg2076',
 'lcl_NC_006958_1_prot_WP_011014301_1_1315': 'cg1528',
 'lcl_NC_006958_1_prot_WP_003854698_1_647': 'cg0772',
 'lcl_NC_006958_1_prot_WP_003858826_1_1288': nan,
 'lcl_NC_006958_1_prot_WP_011265847_1_1852': nan,
 'lcl_NC_006958_1_prot_WP_003857536_1_1910': 'cg2204',
 'lcl_NC_006958_1_prot_WP_011014778_1_1849': nan,
 'lcl_NC_006958_1_prot_WP_003858824_1_1289': 'cg1503',
 'lcl_NC_006958_1_prot_WP_011015128_1_2324': nan,
 'lcl_NC_006958_1_prot_WP_011014015_1_941': 'cg1105',
 'lcl_NC_006958_1_prot_WP_011014337_1_1362': 'cg1588',
 'lcl_NC_006958_1_prot_WP_003858678_1_1361': 'cg1586',
 'lcl_NC_006958_1_prot_WP_003854734_1_1226': 'cg1424',
 'lcl_NC_006958_1_prot_WP_011013506_1_251': 'cg0307',
 'lcl_NC_006958_1_prot_WP_003860401_1_2035': 'cg2352',
 'lcl_NC_006958_1_prot_WP_011014952_1_2088': 'cg2410',
 'lcl_NC_006958_1_prot_WP_011265757_1_1470': 'cg1705',
 'lcl_NC_006958_1_prot_WP_003857183_1_135': 'cg0172',
 'lcl_NC_006958_1_prot_WP_003862210_1_1567': 'cg1816',
 'lcl_NC_006958_1_prot_WP_003855724_1_250': 'cg0306',
 'lcl_NC_006958_1_prot_WP_011014409_1_1462': 'cg1697',
 'lcl_NC_006958_1_prot_WP_011015206_1_2431': 'cg2810',
 'lcl_NC_006958_1_prot_WP_003862691_1_2717': 'cg3149',
 'lcl_NC_006958_1_prot_WP_006285864_1_2478': 'cg2877',
 'lcl_NC_006958_1_prot_WP_011014416_1_1472': 'cg1707',
 'spontaneous': nan,
 'lcl_NC_006958_1_prot_WP_003856149_1_1463': 'cg1698',
 'lcl_NC_006958_1_prot_WP_003854856_1_1170': 'cg1362',
 'lcl_NC_006958_1_prot_WP_011015429_1_2715': 'cg3146',
 'lcl_NC_006958_1_prot_WP_003862394_1_821': 'cg0967',
 'lcl_NC_006958_1_prot_WP_003861135_1_73': 'cg0095',
 'lcl_NC_006958_1_prot_WP_011014211_1_1185': 'cg1377',
 'lcl_NC_006958_1_prot_WP_011015133_1_2331': 'cg2695',
 'lcl_NC_006958_1_prot_WP_011014212_1_1186': 'cg1379',
 'lcl_NC_006958_1_prot_WP_011014213_1_1187': 'cg1380',
 'lcl_NC_006958_1_prot_WP_011015095_1_2287': 'cg2638',
 'lcl_NC_006958_1_prot_WP_011015094_1_2286': 'cg2637',
 'lcl_NC_006958_1_prot_WP_003859226_1_2288': 'cg2639',
 'lcl_NC_006958_1_prot_WP_011015096_1_2289': 'cg2640',
 'lcl_NC_006958_1_prot_WP_011014103_1_1043': 'cg1225',
 'lcl_NC_006958_1_prot_WP_011014439_1_1506': 'cg1744',
 'lcl_NC_006958_1_prot_WP_011014107_1_1049': 'cg1231',
 'lcl_NC_006958_1_prot_WP_011015093_1_2285': 'cg2636',
 'lcl_NC_006958_1_prot_WP_011014478_1_1565': 'cg1814',
 'lcl_NC_006958_1_prot_WP_003862217_1_1564': 'cg1813',
 'lcl_NC_006958_1_prot_WP_011014176_1_1141': 'cg1329',
 'lcl_NC_006958_1_prot_WP_011015537_1_2842': 'cg3295',
 'lcl_NC_006958_1_prot_WP_011014254_1_1243': 'cg1447',
 'lcl_NC_006958_1_prot_WP_011014363_1_1394': 'cg1623',
 'lcl_NC_006958_1_prot_WP_011013524_1_270': 'cg0330',
 'lcl_NC_006958_1_prot_WP_011013452_1_182': 'cg0228',
 'lcl_NC_006958_1_prot_WP_011014067_1_1007': nan,
 'lcl_NC_006958_1_prot_WP_011013967_1_884': 'cg1039',
 'lcl_NC_006958_1_prot_WP_003859882_1_1621': 'cg1878',
 'lcl_NC_006958_1_prot_WP_011014378_1_1418': 'cg1650',
 'lcl_NC_006958_1_prot_WP_011265910_1_2133': 'cg2467',
 'lcl_NC_006958_1_prot_WP_011015032_1_2195': 'cg2539',
 'lcl_NC_006958_1_prot_WP_011014488_1_1578': nan,
 'lcl_NC_006958_1_prot_WP_011014417_1_1474': 'cg1709',
 'lcl_NC_006958_1_prot_WP_011013936_1_838': 'cg0985',
 'lcl_NC_006958_1_prot_2936': nan,
 'lcl_NC_006958_1_prot_WP_011265455_1_68': 'cg0088',
 'lcl_NC_006958_1_prot_WP_003853689_1_2617': 'cg3037',
 'lcl_NC_006958_1_prot_WP_011013359_1_64': nan,
 'lcl_NC_006958_1_prot_WP_011014785_1_1858': 'cg2148',
 'lcl_NC_006958_1_prot_WP_003862124_1_1046': 'cg1228',
 'lcl_NC_006958_1_prot_WP_003857456_1_1859': 'cg2149',
 'lcl_NC_006958_1_prot_WP_011014910_1_2033': 'cg2349',
 'lcl_NC_006958_1_prot_WP_011014540_1_1639': 'cg1903',
 'lcl_NC_006958_1_prot_WP_011013358_1_62': 'cg0080',
 'lcl_NC_006958_1_prot_WP_011015017_1_2176': 'cg2517',
 'lcl_NC_006958_1_prot_WP_011015605_1_2929': 'cg3395',
 'lcl_NC_006958_1_prot_WP_011013479_1_216': 'cg0265',
 'lcl_NC_006958_1_prot_WP_011015130_1_2326': 'cg2690',
 'lcl_NC_006958_1_prot_WP_011013914_1_806': 'cg0949',
 'lcl_NC_006958_1_prot_WP_011013823_1_673': 'cg0798',
 'lcl_NC_006958_1_prot_WP_011013369_1_77': 'cg0104',
 'lcl_NC_006958_1_prot_WP_003855650_1_228': 'cg0281',
 'lcl_NC_006958_1_prot_WP_003856281_1_1377': 'cg1606',
 'lcl_NC_006958_1_prot_WP_011013995_1_919': 'cg1080',
 'lcl_NC_006958_1_prot_WP_011265547_1_377': 'cg0464',
 'lcl_NC_006958_1_prot_WP_011013330_1_29': 'cg0042',
 'lcl_NC_006958_1_prot_WP_003861284_1_1140': 'cg1328',
 'lcl_NC_006958_1_prot_WP_011015526_1_2830': 'cg3281',
 'lcl_NC_006958_1_prot_WP_003856609_1_2082': 'cg2403',
 'lcl_NC_006958_1_prot_WP_011014947_1_2084': nan,
 'lcl_NC_006958_1_prot_WP_011014946_1_2083': 'cg2404',
 'lcl_NC_006958_1_prot_WP_011015188_1_2403': 'cg2780',
 'lcl_NC_006958_1_prot_WP_011014951_1_2087': 'cg2409',
 'lcl_NC_006958_1_prot_WP_003859659_1_2085': nan,
 'lcl_NC_006958_1_prot_WP_011014455_1_1528': 'cg1773',
 'lcl_NC_006958_1_prot_WP_011014907_1_2028': 'cg2344',
 'lcl_NC_006958_1_prot_WP_011014424_1_1484': 'cg1719',
 'lcl_NC_006958_1_prot_WP_011265869_1_1970': 'cg2277',
 'lcl_NC_006958_1_prot_WP_011014865_1_1971': 'cg2279',
 'lcl_NC_006958_1_prot_WP_011014220_1_1196': 'cg1388',
 'lcl_NC_006958_1_prot_WP_011015376_1_2659': 'cg3086',
 'lcl_NC_006958_1_prot_WP_003854667_1_631': 'cg0755',
 'lcl_NC_006958_1_prot_WP_011015029_1_2192': 'cg2536',
 'lcl_NC_006958_1_prot_WP_011014157_1_1116': 'cg1301',
 'lcl_NC_006958_1_prot_WP_041625656_1_1114': 'cg1299',
 'lcl_NC_006958_1_prot_WP_011014156_1_1115': 'cg1300',
 'lcl_NC_006958_1_prot_WP_011014154_1_1113': 'cg1298',
 'lcl_NC_006958_1_prot_WP_011014797_1_1875': 'cg2168',
 'lcl_NC_006958_1_prot_WP_011014308_1_1324': 'cg1543',
 'lcl_NC_006958_1_prot_WP_003863776_1_1387': 'cg1616',
 'lcl_NC_006958_1_prot_WP_011015567_1_2880': 'cg3340',
 'lcl_NC_006958_1_prot_WP_003855284_1_2947': 'cg3415',
 'lcl_NC_006958_1_prot_WP_011015227_1_2457': 'cg2849',
 'lcl_NC_006958_1_prot_WP_011265883_1_2027': 'cg2343',
 'lcl_NC_006958_1_prot_WP_011014180_1_1145': 'cg1334',
 'lcl_NC_006958_1_prot_WP_011014772_1_1842': 'cg2129',
 'lcl_NC_006958_1_prot_WP_011013448_1_178': 'cg0221',
 'lcl_NC_006958_1_prot_WP_011013439_1_166': 'cg0207',
 'lcl_NC_006958_1_prot_WP_011014801_1_1881': 'cg2174',
 'lcl_NC_006958_1_prot_WP_003857552_1_1919': 'cg2216',
 'lcl_NC_006958_1_prot_WP_003853460_1_2721': 'cg3155',
 'lcl_NC_006958_1_prot_WP_011014024_1_953': 'cg1118',
 'lcl_NC_006958_1_prot_WP_011014031_1_962': 'cg1129',
 'lcl_NC_006958_1_prot_WP_003856581_1_2071': 'cg2391',
 'lcl_NC_006958_1_prot_WP_003855988_1_1561': 'cg1810',
 'lcl_NC_006958_1_prot_WP_011013941_1_850': 'cg0997',
 'lcl_NC_006958_1_prot_WP_003863097_1_2486': 'cg2888',
 'lcl_NC_006958_1_prot_WP_011013940_1_849': 'cg0996',
 'lcl_NC_006958_1_prot_WP_003854128_1_1231': 'cg1432',
 'lcl_NC_006958_1_prot_WP_051090343_1_452': 'cg0549',
 'lcl_NC_006958_1_prot_WP_011014794_1_1871': 'cg2163',
 'lcl_NC_006958_1_prot_WP_011014792_1_1869': 'cg2161',
 'lcl_NC_006958_1_prot_WP_011015276_1_2524': 'cg2931',
 'WP_011013924_1': nan,
 'lcl_NC_006958_1_prot_WP_011013924_1_819': 'cg0965',
 'lcl_NC_006958_1_prot_WP_011265933_1_2258': 'cg2608',
 'lcl_NC_006958_1_prot_WP_011013659_1_437': 'cg0531',
 'lcl_NC_006958_1_prot_WP_003853806_1_2568': 'cg2981',
 'lcl_NC_006958_1_prot_WP_011014420_1_1478': 'cg1713',
 'lcl_NC_006958_1_prot_WP_011014479_1_1566': 'cg1815',
 'lcl_NC_006958_1_prot_WP_011014471_1_1552': 'cg1800',
 'lcl_NC_006958_1_prot_WP_003853803_1_2569': 'cg2982',
 'lcl_NC_006958_1_prot_WP_003855021_1_1078': 'cg1262',
 'lcl_NC_006958_1_prot_WP_011014486_1_1576': 'cg1827',
 'lcl_NC_006958_1_prot_WP_003860435_1_411': 'cg0503',
 'lcl_NC_006958_1_prot_WP_011013639_1_410': 'cg0502',
 'lcl_NC_006958_1_prot_WP_011014806_1_1888': 'cg2181',
 'lcl_NC_006958_1_prot_WP_011014814_1_1899': 'cg2192',
 'lcl_NC_006958_1_prot_WP_011013676_1_461': 'cg0559',
 'lcl_NC_006958_1_prot_WP_011265892_1_2065': 'cg2384',
 'lcl_NC_006958_1_prot_WP_011014303_1_1318': 'cg1531',
 'lcl_NC_006958_1_prot_WP_004568094_1_994': 'cg1164',
 'lcl_NC_006958_1_prot_WP_011013953_1_869': 'cg1018',
 'lcl_NC_006958_1_prot_WP_011014305_1_1320': 'cg1538',
 'lcl_NC_006958_1_prot_WP_011014114_1_1056': 'cg1239',
 'lcl_NC_006958_1_prot_WP_011014232_1_1215': 'cg1410',
 'lcl_NC_006958_1_prot_WP_011265708_1_1217': 'cg1412',
 'lcl_NC_006958_1_prot_WP_011014233_1_1216': 'cg1411',
 'lcl_NC_006958_1_prot_WP_011013617_1_374': nan,
 'lcl_NC_006958_1_prot_WP_003856628_1_2094': 'cg2417',
 'lcl_NC_006958_1_prot_WP_003858194_1_728': 'cg0861',
 'lcl_NC_006958_1_prot_WP_011014744_1_1804': 'cg2086',
 'lcl_NC_006958_1_prot_WP_011014016_1_943': 'cg1107',
 'lcl_NC_006958_1_prot_WP_011014825_1_1913': 'cg2208',
 'lcl_NC_006958_1_prot_WP_011014741_1_1801': 'cg2083',
 'lcl_NC_006958_1_prot_WP_003856756_1_947': 'cg1111',
 'lcl_NC_006958_1_prot_WP_003857486_1_1878': 'cg2171',
 'lcl_NC_006958_1_prot_WP_003860847_1_2351': 'cg2719',
 'lcl_NC_006958_1_prot_WP_003858506_1_891': 'cg1048',
 'lcl_NC_006958_1_prot_WP_011015231_1_2466': 'cg2860',
 'lcl_NC_006958_1_prot_WP_011265702_1_1162': 'cg1353',
 'lcl_NC_006958_1_prot_WP_011013532_1_281': 'cg0341',
 'lcl_NC_006958_1_prot_WP_003855494_1_390': 'cg0480',
 'lcl_NC_006958_1_prot_WP_003859440_1_2180': 'cg2521',
 'lcl_NC_006958_1_prot_WP_011014218_1_1194': 'cg1386',
 'lcl_NC_006958_1_prot_WP_011014219_1_1195': 'cg1387',
 'lcl_NC_006958_1_prot_WP_011014383_1_1423': 'cg1655',
 'lcl_NC_006958_1_prot_WP_011015170_1_2374': 'cg2743',
 'lcl_NC_006958_1_prot_WP_011013534_1_283': 'cg0344',
 'lcl_NC_006958_1_prot_WP_011013987_1_909': 'cg1068',
 'lcl_NC_006958_1_prot_WP_011015363_1_2644': 'cg3068',
 'lcl_NC_006958_1_prot_WP_003856830_1_987': 'cg1157',
 'lcl_NC_006958_1_prot_WP_011013898_1_776': 'cg0910',
 'lcl_NC_006958_1_prot_WP_011014434_1_1496': 'cg1734',
 'lcl_NC_006958_1_prot_WP_011014521_1_1616': 'cg1873',
 'lcl_NC_006958_1_prot_WP_011013707_1_509': 'cg0616',
 'lcl_NC_006958_1_prot_WP_011265574_1_511': 'cg0618',
 'lcl_NC_006958_1_prot_WP_011014210_1_1184': 'cg1376',
 'lcl_NC_006958_1_prot_WP_011015064_1_2240': 'cg2589',
 'lcl_NC_006958_1_prot_WP_011014372_1_1410': 'cg1642',
 'lcl_NC_006958_1_prot_WP_011265558_1_415': 'cg0507',
 'lcl_NC_006958_1_prot_WP_003856101_1_1500': 'cg1738',
 'lcl_NC_006958_1_prot_WP_011015011_1_2169': 'cg2510',
 'lcl_NC_006958_1_prot_WP_003856445_1_2004': 'cg2315',
 'lcl_NC_006958_1_prot_WP_011014490_1_1581': 'cg1832',
 'lcl_NC_006958_1_prot_WP_003859752_1_381': 'cg0468',
 'lcl_NC_006958_1_prot_WP_011014216_1_1190': 'cg1383',
 'lcl_NC_006958_1_prot_WP_011013642_1_414': 'cg0506',
 'lcl_NC_006958_1_prot_WP_003859878_1_1624': 'cg1881',
 'lcl_NC_006958_1_prot_WP_011013576_1_331': 'cg0405',
 'lcl_NC_006958_1_prot_WP_011013804_1_645': 'cg0770',
 'lcl_NC_006958_1_prot_WP_011013803_1_644': 'cg0769',
 'lcl_NC_006958_1_prot_WP_011014139_1_1097': 'cg1281',
 'lcl_NC_006958_1_prot_WP_011013698_1_486': 'cg0589',
 'lcl_NC_006958_1_prot_WP_011013700_1_488': 'cg0591',
 'lcl_NC_006958_1_prot_WP_011013699_1_487': 'cg0590',
 'lcl_NC_006958_1_prot_WP_011015224_1_2454': 'cg2846',
 'lcl_NC_006958_1_prot_WP_020948636_1_2521': 'cg2927',
 'lcl_NC_006958_1_prot_WP_011014131_1_1083': 'cg1267',
 'lcl_NC_006958_1_prot_WP_011014798_1_1876': 'cg2169',
 'lcl_NC_006958_1_prot_WP_011014506_1_1598': nan,
 'lcl_NC_006958_1_prot_WP_011015486_1_2783': 'cg3223',
 'lcl_NC_006958_1_prot_WP_080558841_1_2909': 'cg3370',
 'lcl_NC_006958_1_prot_WP_011015420_1_2706': 'cg3136',
 'lcl_NC_006958_1_prot_WP_003855465_1_361': 'cg0445',
 'lcl_NC_006958_1_prot_WP_011013606_1_362': 'cg0446',
 'lcl_NC_006958_1_prot_WP_011013607_1_363': 'cg0447',
 'lcl_NC_006958_1_prot_WP_011014765_1_1834': 'cg2119',
 'lcl_NC_006958_1_prot_WP_011014766_1_1835': 'cg2120',
 'lcl_NC_006958_1_prot_WP_011013616_1_373': 'cg0457',
 'lcl_NC_006958_1_prot_WP_003856814_1_978': 'cg1145',
 'lcl_NC_006958_1_prot_WP_003863112_1_2474': 'cg2870',
 'lcl_NC_006958_1_prot_WP_011013993_1_917': 'cg1076',
 'lcl_NC_006958_1_prot_WP_011013572_1_327': 'cg0401',
 'lcl_NC_006958_1_prot_WP_011013651_1_426': nan,
 'lcl_NC_006958_1_prot_WP_011014508_1_1600': nan,
 'lcl_NC_006958_1_prot_WP_003858849_1_1277': 'cg1492',
 'lcl_NC_006958_1_prot_WP_003859321_1_2237': 'cg2586',
 'lcl_NC_006958_1_prot_WP_011015274_1_2522': 'cg2928',
 'lcl_NC_006958_1_prot_WP_011014457_1_1531': 'cg1778',
 'lcl_NC_006958_1_prot_WP_011013333_1_33': 'cg0046',
 'lcl_NC_006958_1_prot_WP_003856970_1_2121': 'cg2452',
 'lcl_NC_006958_1_prot_WP_011014867_1_1975': 'cg2284',
 'lcl_NC_006958_1_prot_WP_003858460_1_857': 'cg1004',
 'lcl_NC_006958_1_prot_WP_011013988_1_910': 'cg1069',
 'lcl_NC_006958_1_prot_2828': nan,
 'lcl_NC_006958_1_prot_WP_003862250_1_1543': 'cg1791',
 'lcl_NC_006958_1_prot_WP_011265636_1_836': nan,
 'lcl_NC_006958_1_prot_WP_011014279_1_1272': 'cg1485',
 'lcl_NC_006958_1_prot_WP_011015000_1_2155': 'cg2492',
 'lcl_NC_006958_1_prot_WP_003856790_1_966': 'cg1133',
 'lcl_NC_006958_1_prot_WP_011014214_1_1188': 'cg1381',
 'lcl_NC_006958_1_prot_WP_011013848_1_702': 'cg0832',
 'lcl_NC_006958_1_prot_WP_011013847_1_701': 'cg0831',
 'lcl_NC_006958_1_prot_WP_011013851_1_705': 'cg0835',
 'lcl_NC_006958_1_prot_WP_011014871_1_1979': 'cg2289',
 'lcl_NC_006958_1_prot_WP_011014275_1_1268': 'cg1479',
 'lcl_NC_006958_1_prot_WP_011014885_1_1999': 'cg2310',
 'lcl_NC_006958_1_prot_WP_011014133_1_1085': 'cg1269',
 'lcl_NC_006958_1_prot_WP_011013931_1_832': 'cg0978',
 'lcl_NC_006958_1_prot_WP_011014780_1_1851': 'cg2138',
 'lcl_NC_006958_1_prot_WP_011014779_1_1850': 'cg2137',
 'lcl_NC_006958_1_prot_WP_011014960_1_2105': 'cg2429',
 'lcl_NC_006958_1_prot_WP_003856962_1_2117': 'cg2447',
 'lcl_NC_006958_1_prot_WP_003859315_1_2239': nan,
 'lcl_NC_006958_1_prot_WP_003856385_1_1972': nan,
 'lcl_NC_006958_1_prot_WP_003860838_1_2359': 'cg2728',
 'lcl_NC_006958_1_prot_WP_011014877_1_1989': 'cg2300',
 'lcl_NC_006958_1_prot_WP_011265975_1_2464': 'cg2857',
 'lcl_NC_006958_1_prot_WP_011015179_1_2390': 'cg2762',
 'lcl_NC_006958_1_prot_WP_011013454_1_184': 'cg0230',
 'lcl_NC_006958_1_prot_WP_011013453_1_183': 'cg0229',
 'lcl_NC_006958_1_prot_WP_011013686_1_471': 'cg0570',
 'lcl_NC_006958_1_prot_WP_004567745_1_2201': 'cg2546',
 'lcl_NC_006958_1_prot_WP_011014377_1_1417': 'cg1649',
 'lcl_NC_006958_1_prot_WP_011265645_1_867': 'cg1016',

In [40]:
#replace the ncbi gene names in the GPR relation
def replace_ids(gpr, mapper):
    if pd.isna(gpr):  # Handle missing values
        return gpr
    for old_id, new_id in mapper.items():
        if pd.isna(new_id): continue
        gpr = gpr.replace(old_id, new_id)
    return gpr

id_mapper_gpr = id_mapper.copy()
# Apply the replacement function to the GPR column
id_mapper_gpr["GPR_old"] = id_mapper_gpr["GPR"].copy()
id_mapper_gpr["GPR"] = id_mapper_gpr["GPR"].apply(lambda x: replace_ids(x, gene_mapper))
id_mapper_gpr["GPR_old"] = id_mapper_gpr["GPR"].apply(lambda x: replace_ids(x, gene_mapper))

id_mapper_gpr

,rxn_id,kegg_id,rhea_id,Reactants,Products,EC,GPR,GPR_old
0,2AGPEAT160,NaN,NaN,[],[],2.3.1.40,,
1,2AGPEAT180,NaN,NaN,[],[],2.3.1.40,,
2,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...
3,3HAD140,R04568,NaN,[C04688],"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[4.2.1.61, 2.3.1.86, 2.3.1.-, 2.3.1.85, 4.2.1.59]",,
4,3MBt2pp,NaN,NaN,"[C00080, C08262]","[C08262, C00080]",NaN,cg0953,cg0953
...,...,...,...,...,...,...,...,...
1147,Ca2t2,NaN,NaN,"[C00076, C00080]","[C00076, C00080]",NaN,WP_011014107_1,WP_011014107_1
1148,CAT,R00009,"[20309, 20310, 20311, 20312]","[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[1.11.1.21, 1.11.1.6]",WP_011013509_1,WP_011013509_1
1149,SUCDi,NaN,"[29187, 29188, 29189, 29190]",[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013606_1 and WP_011013607_1
1150,PRFGS_1,R04463,"[17129, 17131, 17130, 17132]","[[C00002, C00002;D08646], C04376, [C00064, C00...","[[C00008, C00008;G11113], C04640, [C00025, C00...",6.3.5.3,cg2865,cg2865
1151,PYRt,NaN,NaN,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1

## 2. Get all the protein information

Besides information about the reactions, we need the relation to the proteins in order to establish a protein allocation model. We do this using the gene-protein-reaction association obtained from the BIGG model. The genes is the model can be mapped to the Uniprot accessions, which can be mapped to the KEGG reactions using the Rhea database.

Parse the BIGG gene-protein-reaction associations

In [51]:
#You need to adjust this to find the geneid/locustag for your microbe
#locustag_regex =r'\b([b|s]\d{4})\b'
def extract_b_numbers(text):
    if pd.isna(text):
        return text
    return re.findall(locustag_regex, text)

id_mapper_df = id_mapper_gpr.copy()

id_mapper_df['b_number'] = id_mapper_df['GPR'].apply(extract_b_numbers)
id_mapper_df['gene_id_old'] = id_mapper_df['GPR_old'].apply(extract_b_numbers)
id_mapper_df = id_mapper_df.explode(['b_number', 'gene_id_old'], ignore_index=True)
id_mapper_df = id_mapper_df.explode('EC', ignore_index=True)
id_mapper_df = id_mapper_df.merge(
    gene_id_mapper[['uniprot_id', 'gene_id']], left_on='gene_id_old', right_on='gene_id'
).drop(['gene_id_old', 'GPR_old'], axis=1)
id_mapper_df

,rxn_id,kegg_id,rhea_id,Reactants,Products,EC,GPR,b_number,uniprot_id,gene_id
0,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
1,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
2,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.-,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
3,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.-,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
4,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.15,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
...,...,...,...,...,...,...,...,...,...,...
688,CAT,R00009,"[20309, 20310, 20311, 20312]","[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...",1.11.1.6,WP_011013509_1,WP_011013509_1,NaN,WP_011013509_1
689,SUCDi,NaN,"[29187, 29188, 29189, 29190]",[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013606_1,NaN,WP_011013606_1
690,SUCDi,NaN,"[29187, 29188, 29189, 29190]",[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013607_1,NaN,WP_011013607_1
691,PYRt,NaN,NaN,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,NaN,WP_011014733_1
692,PYRt,NaN,NaN,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,NaN,WP_011014733_1

In [56]:
def extract_kegg_gene_ids(text):
    if pd.isna(text):
        return text
    return re.findall(r'Cgl\d{4}', text)

# load the uniprot information
uniprot_df = pd.read_excel(UNIPROT_FILE_PATH)
#get the gene id from the gene names
uniprot_df['b_number'] = uniprot_df['Gene Names'].apply(extract_b_numbers)
# uniprot_df['kegg_gene'] = uniprot_df['Gene Names'].apply(extract_kegg_gene_ids)
uniprot_df = uniprot_df.explode('b_number', ignore_index=True)
# uniprot_df = uniprot_df.explode('kegg_gene', ignore_index=True)

uniprot_df = uniprot_df.drop(['Gene Names'], axis=1)
uniprot_df_genemapper = uniprot_df[['Entry', 'Mass', 'Length']]

### 2.3 Match Uniprot to BIGG data

In [61]:
# Merge first on b_number
id_mapper_with_protein = pd.merge(
    id_mapper_df, 
    uniprot_df_genemapper, 
    left_on='uniprot_id', 
    right_on = 'Entry',
    how='left'
)

# Combine the two merges: prefer the first merge, fill missing values from the second
id_mapper_with_protein['Entry'] = id_mapper_with_protein['Entry'].fillna(fallback_merge['Entry'])
id_mapper_with_protein = id_mapper_with_protein.drop('Entry', axis=1)
id_mapper_with_protein

,rxn_id,kegg_id,rhea_id,Reactants,Products,EC,GPR,b_number,uniprot_id,gene_id,Mass,Length
0,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,36654.0,322.0
1,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,36654.0,322.0
2,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.-,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,36654.0,322.0
3,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.-,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,36654.0,322.0
4,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.15,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,36654.0,322.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1176,CAT,R00009,"[20309, 20310, 20311, 20312]","[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...",1.11.1.6,WP_011013509_1,WP_011013509_1,NaN,WP_011013509_1,NaN,NaN
1177,SUCDi,NaN,"[29187, 29188, 29189, 29190]",[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013606_1,NaN,WP_011013606_1,NaN,NaN
1178,SUCDi,NaN,"[29187, 29188, 29189, 29190]",[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013607_1,NaN,WP_011013607_1,NaN,NaN
1179,PYRt,NaN,NaN,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,NaN,WP_011014733_1,NaN,NaN
1180,PYRt,NaN,NaN,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,NaN,WP_011014733_1,NaN,NaN

## 3. Match the BiGG model reaction and enzymes to the kcats from GotEnzymes
Find first all enzymes for a reaction, then for each enzyme determine if the kcats from GotEnzymes are for a forward or reverse reaction

In [52]:
id_mapper_final = id_mapper_df.copy()
id_mapper_final = id_mapper_final.rename({'uniprot_id':'enzyme_id'}, axis=1)
id_mapper_final = id_mapper_final.explode('kegg_id', ignore_index=True)

# id_mapper_final = id_mapper_final.drop_duplicates(subset = ['kegg_id'])
id_mapper_final.head()

,rxn_id,kegg_id,rhea_id,Reactants,Products,EC,GPR,b_number,enzyme_id,gene_id
0,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
1,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
2,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.-,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
3,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.-,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949
4,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.15,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949

In [53]:
#get the json file from GotEnzymes and parse into workable format
#read in the json file obtained from gotEnzymes (for 'eco')
eco_enzymes_json = pd.read_json(GOTENZYMES_FILE_PATH)
#convert to a readible format
eco_enzymes = eco_enzymes_json.enzymes.to_list()
eco_enzymes_df = pd.DataFrame(eco_enzymes)

#ensure there is only one ec number per row
eco_enzymes_df['ec_number'] = eco_enzymes_df['ec_number'].str.split(pat=';')
eco_enzymes_df = eco_enzymes_df.explode('ec_number', ignore_index=True)
eco_enzymes_df = eco_enzymes_df.dropna(axis=0, subset=['ec_number'])
eco_enzymes_df = eco_enzymes_df.drop(['organism', 'domain'], axis = 1)
eco_enzymes_df.head()

      gene reaction_id ec_number compound  kcat_values
0  Cgl0023      R01664   3.1.3.5   C00239       5.4287
1  Cgl0023      R01664  3.1.3.89   C00239       5.4287
2  Cgl0023      R01664   3.1.3.-   C00239       5.4287
3  Cgl0023      R00511   3.1.3.5   C00475       5.9248
4  Cgl0023      R00511  3.1.3.91   C00475       5.9248

In [54]:
# match BiGG and GotEnzymes based on gene id
eco_enzymes_merged = id_mapper_final.merge(eco_enzymes_df, 
                              left_on =['b_number', 'kegg_id'], 
                              right_on = ['gene', 'reaction_id'],
                             how = 'left').drop(['gene', 'reaction_id'], axis=1).rename({'b_number':'gene'}, axis=1)
eco_enzymes_merged

,rxn_id,kegg_id,rhea_id,Reactants,Products,EC,GPR,gene,enzyme_id,gene_id,ec_number,compound,kcat_values
0,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,NaN,NaN,NaN
1,2MAHMP,NaN,"[27915, 27914, 27916, 27917]","[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,NaN,NaN,NaN
2,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.-,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,NaN,NaN,NaN
3,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.-,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,NaN,NaN,NaN
4,TDP,R00615,"[27998, 28000, 28001, 27999]","[C00068, [C00001, C01328, C00001;C01328;D00001...","[C00080, C01081, [C00009, C00009;D05467]]",3.6.1.15,lcl_NC_006958_1_prot_WP_003855288_1_2949,lcl_NC_006958_1_prot_WP_003855288_1_2949,Q8NL63,lcl_NC_006958_1_prot_WP_003855288_1_2949,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,CAT,R00009,"[20309, 20310, 20311, 20312]","[[C00027, C00027;D00008]]","[[C00001, C01328, C00001;C01328;D00001;D03703;...",1.11.1.6,WP_011013509_1,WP_011013509_1,NaN,WP_011013509_1,NaN,NaN,NaN
700,SUCDi,NaN,"[29187, 29188, 29189, 29190]",[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013606_1,NaN,WP_011013606_1,NaN,NaN,NaN
701,SUCDi,NaN,"[29187, 29188, 29189, 29190]",[],[],NaN,WP_011013606_1 and WP_011013607_1,WP_011013607_1,NaN,WP_011013607_1,NaN,NaN,NaN
702,PYRt,NaN,NaN,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,NaN,WP_011014733_1,NaN,NaN,NaN
703,PYRt,NaN,NaN,[C00022],[C00022],NaN,WP_011014733_1,WP_011014733_1,NaN,WP_011014733_1,NaN,NaN,NaN

### 6. Extract directionalities and gapfill
Reactions which are associated with an enzyme, but not with a kcat from GotEnzymes will be assignes
a default kcat and if required a default molmass.

In [55]:
# Get directionalities and fill in the gaps
eco_enzymes_merged['direction'] = 'f'
                                              
for index, row in eco_enzymes_merged.iterrows():
    #there is a kegg id and kcat associated to this reaction
    if not isinstance(row.kcat_values, float):
        if row.compound in row.Products:
            eco_enzymes_merged.direction.iloc[index] = 'b'
        elif not row.compound in row.Reactants:
            print(f'Compound {row["compound"]} is not associated to reaction {row["kegg_id"]}')
            continue
    #there is no kcat associated to this reaction, try to use EC number to get a kcat value
    else: 
        got_enzyme_info = eco_enzymes_df[eco_enzymes_df['ec_number']==row.EC]
        for i, info in got_enzyme_info.iterrows():
            #is there any enzyme association if we look at the metabolites in the reaction and the EC number?
            if info.compound in row.Products:
                direction = 'b'
            elif info.compound in row.Reactants:
                direction = 'f'
            else:
                continue
            #change the kcat if it is not there already or create a new enzyme association
            if np.isnan(row.kcat_values):
                eco_enzymes_merged.direction.iloc[index] = 'b'
                eco_enzymes_merged.kcat_values.iloc[index] = info.kcat_values
            else:
                eco_enzymes_merged.loc[len(eco_enzymes_merged)] = row.to_list()[:-2]+[info.kcat_values, 'b']
        #add default information for unmappable proteins
        
        if (row.GPR == '') and not isinstance(row.EC, float): 
            eco_enzymes_merged.gene[index] = [f'Gene_{row.rxn_id}_{row.EC}']
            eco_enzymes_merged.GPR[index] = f'Gene_{row.rxn_id}_{row.EC}'
            eco_enzymes_merged.enzyme_id[index] = f'Enzyme_{row.rxn_id}_{row.EC}'
        if isinstance(row.gene, float) and len(row.GPR)>0:
            eco_enzymes_merged.gene[index] = [row.GPR]
        if not isinstance(row.enzyme_id, str) and len(row.GPR)>0:
            eco_enzymes_merged.enzyme_id[index] = f'Enzyme_{row.gene}'
        
        if np.isnan(row.kcat_values) & (isinstance(row.enzyme_id, str)) & (row.GPR!= 's0001'):
            eco_enzymes_merged.direction.iloc[index] = 'f'
            eco_enzymes_merged.kcat_values.iloc[index] = DEFAULT_KCAT
        if np.isnan(row.Mass) & (len(row.GPR)>2) & (row.GPR!= 's0001'):
            eco_enzymes_merged.Mass.iloc[index] = DEFAULT_PROT_MW
        
        
eco_enzymes_mapped = eco_enzymes_merged.drop(['ec_number', 'compound'], axis=1).rename({'Mass':'molMass',
                                                                                       'b_number': 'gene'}, axis =1)
eco_enzymes_mapped

/tmp/ipykernel_343616/253922216.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.direction.iloc[index] = 'f'
/tmp/ipykernel_343616/253922216.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eco_enzymes_merged.kcat_values.iloc[index] = DEFAULT_KCAT

AttributeError: 'Series' object has no attribute 'Mass'

In [23]:
eco_enzymes_mapped.gene = [[g] for g in eco_enzymes_mapped.gene]
protein2gene, gene2protein = get_protein_gene_mapping(eco_enzymes_mapped, model)


# Ensure the enzyme complexes are merged on one row
eco_enzymes_mapped = merge_enzyme_complexes(eco_enzymes_mapped, gene2protein)

# Save the adjusted dataframe or continue processing
eco_enzymes_mapped

,rxn_id,kegg_id,rhea_id,mnx_id,Reactants,Products,EC,GPR,gene,enzyme_id,molMass,Length,kcat_values,direction
2,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,[lcl_NC_006958_1_prot_WP_003855288_1_2949],Enzyme_lcl_NC_006958_1_prot_WP_003855288_1_2949,39959.4825,NaN,NaN,f
3,2MAHMP,NaN,NaN,MNXR142616,"[[C00001, C01328, C00001;C01328;D00001;D03703;...","[C04556, C00080, [C00009, C00009;D05467]]",NaN,lcl_NC_006958_1_prot_WP_003855288_1_2949 or cg...,[cg3199],Enzyme_cg3199,39959.4825,NaN,NaN,f
9,3MBt2pp,NaN,NaN,MNXR94916,"[C00080, C08262]","[C08262, C00080]",NaN,cg0953,[cg0953],Q8NMS0,39959.4825,NaN,13.7,f
10,3MBt4pp,NaN,NaN,MNXR94917,"[C01330, C08262]","[C01330, C08262]",NaN,cg0953,[cg0953],Q8NS46,39959.4825,NaN,13.7,f
12,3OXCOAT,R00829,"[19482, 19483, 19481, 19484]",MNXR94967,"[C02232, C00010]","[C00091, C00024]",2.3.1.174,cg2625,[cg2625],Enzyme_cg2625,39959.4825,NaN,NaN,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2439,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,[cg2912],Enzyme_cg2912,39959.4825,NaN,NaN,f
2440,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,"[cg0042, cg0043]",Enzyme_cg0042,39959.4825,NaN,NaN,f
2441,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,"[cg0042, cg0043]",Enzyme_cg0043,39959.4825,NaN,NaN,f
2442,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,"[cg0042, cg0043]",Enzyme_cg0042,39959.4825,NaN,NaN,f
2443,ZNabcpp,NaN,"[29795, 29796, 29797, 29798]",MNXR105281,"[[C00002, C00002;D08646], [C00001, C01328, C00...","[C00038, [C00008, C00008;G11113], C00080, [C00...",3.6.3.5,cg1040 or cg2912 or (cg0042 and cg0043) or (cg...,"[cg0042, cg2695]",Enzyme_cg2695,39959.4825,NaN,NaN,f

In [24]:
#save the dataframe
eco_enzymes_mapped = eco_enzymes_mapped.drop_duplicates(subset = ['rxn_id', 'enzyme_id', 'direction'],
                                                       ignore_index=True)
eco_enzymes_mapped.to_excel(AE_OUTPUT_FILE_PATH)

### 7. Save the dataframe to the proper format for building PAMs

In [25]:
# Get the information about the enzyme sectors
unused_enzymes_df = pd.read_excel(PAM_DATA_FILE_PATH,
                                 sheet_name = 'ExcessEnzymes')
translational_protein_df = pd.read_excel(PAM_DATA_FILE_PATH,
                                 sheet_name = 'Translational')

In [26]:
# Save it to a new excel file
with pd.ExcelWriter(OUTPUT_FILE_PATH) as writer:
    eco_enzymes_mapped.to_excel(writer, sheet_name='ActiveEnzymes')
    translational_protein_df.to_excel(writer, sheet_name='Translational')
    unused_enzymes_df.to_excel(writer, sheet_name = 'UnusedEnzyme')